FROM tutum/nginx
MAINTAINER benaduggan

# Add our nginx configuration
COPY ./build/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./build/nginx/thi-nginx.conf /etc/nginx/sites-enabled/default

# Make a directory for the nginx logs
RUN mkdir -p /data/static /data/dreamsuite/static /data/media/
COPY application/static /data/static/
COPY application/dreamsuite/static /data/dreamsuite/static/
COPY application/media /data/media

RUN mkdir /nginx
WORKDIR /nginx
RUN touch access.log
RUN touch error.log
RUN chown -R www-data:www-data /nginx/

EXPOSE 80
CMD service nginx start
