data:
  image: silintl/data-volume:latest
  container_name: data
  volumes:
      - ./application:/data

db:
  extends:
    file: common.yml
    service: db
  volumes:
    - /var/lib/mysql

web:
  extends:
    file: common.yml
    service: web
  image: "tusoftwarestudio/dreamsuite:${DREAMSUITE_TAG}"
  environment:
    - prod.env
  links:
    - db


nginx:
  extends:
    file: common.yml
    service: nginx
  image: "tusoftwarestudio/dreamsuite-nginx:${DREAMSUITE_TAG}"
  links:
    - web:web
