# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import static_border_stations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', static_border_stations.models.NullableEmailField(blank=True, default=None, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('receives_money_distribution_form', models.BooleanField(default=False)),
                ('border_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('border_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', static_border_stations.models.NullableEmailField(blank=True, default=None, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('receives_money_distribution_form', models.BooleanField(default=False)),
                ('border_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
