# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-21 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_border_stations', '0002_auto_20200630_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='first_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_date',
        ),
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
