# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0219_empowerment_vdf_number'),
        ('static_border_stations', '0003_auto_20200721_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksOnProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_percent', models.PositiveIntegerField()),
                ('border_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.Staff')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='worksonproject',
            unique_together=set([('staff', 'border_station')]),
        ),
        migrations.RunSQL("insert into static_border_stations_worksonproject (work_percent, border_station_id, staff_id) "\
                          "select 100, border_station_id, id "\
                          "from static_border_stations_staff "
                          "where border_station_id is not null"),
    ]
