# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-09 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0253_auto_20230419_1642'),
        ('static_border_stations', '0004_auto_20220316_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.CharField(max_length=127, blank=True)),
                ('receives_money_distribution_form', models.BooleanField(default=False)),
                ('border_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
            ],
        ),
        migrations.AddField(
            model_name='committeemember',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Country'),
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Country'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='staffproject',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staffproject',
            unique_together=set([('staff', 'border_station')]),
        ),
    ]
