# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-09 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_border_stations', '0005_auto_20230509_1732'),
    ]

    operations = [
        migrations.RunSQL("update static_border_stations_staff "\
                          "set country_id = (select operating_country_id from dataentry_borderstation db where db.id = border_station_id)"\
                          "where border_station_id is not null"),
        
        migrations.RunSQL("update static_border_stations_staff ss "\
                            "set country_id = ("\
                                "select db.operating_country_id "\
                                "from dataentry_borderstation db "\
                                    "inner join budget_staffbudgetitem di on db.id = di.work_project_id "\
                                "where di.staff_person_id = ss.id "\
                                "limit 1) " \
                            "where country_id is null"),
        #migrations.RunSQL("update static_border_stations_staff ss "\
        #                   "set last_date = first_date " \
        #                   "where border_station_id is null and last_date is null"),
        
        migrations.RunSQL("insert into static_border_stations_staffproject (staff_id, border_station_id, coordinator, receives_money_distribution_form) "\
                          "select sbss.staff_id, sbss.border_station_id, '', false "\
                          "from static_border_stations_worksonproject sbss "),
        migrations.RunSQL("insert into static_border_stations_staffproject (staff_id, border_station_id, coordinator, receives_money_distribution_form) "\
                          "select sbss.id, sbss.border_station_id, '', false "\
                          "from static_border_stations_staff sbss "\
                          " where sbss.last_date is null and border_station_id is not null "\
                            "and (sbss.id, sbss.border_station_id) not in "\
                                "(select staff_id, border_station_id from static_border_stations_staffproject)"),
        migrations.RunSQL("update static_border_stations_staffproject "\
                          "set receives_money_distribution_form = true "\
                          "where (staff_id, border_station_id) in "\
                            "(select id, border_station_id from static_border_stations_staff where receives_money_distribution_form=true)"),
    ]

