# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-29 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_border_stations', '0006_auto_20230509_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffKnowledgeAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='staff/knowledge', verbose_name='Attach scanned copy of form (pdf or image)')),
                ('option', models.CharField(max_length=126, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('leadership', models.FloatField(null=True)),
                ('obedience', models.FloatField(null=True)),
                ('faithfulness', models.FloatField(null=True)),
                ('alertness', models.FloatField(null=True)),
                ('questioning', models.FloatField(null=True)),
                ('awareness', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffReviewAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='staff/knowledge', verbose_name='Attach scanned copy of form (pdf or image)')),
                ('option', models.CharField(max_length=126, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.StaffReview')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='accounting',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='agreement',
            field=models.ImageField(blank=True, default='', upload_to='staff/agreement'),
        ),
        migrations.AddField(
            model_name='staff',
            name='awareness',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='contract',
            field=models.ImageField(blank=True, default='', upload_to='staff/contract'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contract_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='general',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='paralegal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pv_care',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='records',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='security',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staffreview',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.Staff'),
        ),
        migrations.AddField(
            model_name='staffknowledgeattachment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.Staff'),
        ),
    ]
