# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def populate_staff_totals(apps, schema_editor):
    mod = __import__('static_border_stations.models', fromlist=['Staff'])
    staff_class = getattr(mod, 'Staff', None)
    staff_class.set_all_totals()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0258_auto_20230509_1844'),
        ('static_border_stations', '0006_auto_20230509_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMiscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMiscellaneousTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('type', models.CharField(max_length=127)),
                ('choices', models.TextField(blank=True)),
                ('countries', models.ManyToManyField(to='dataentry.Country')),
            ],
        ),
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('leadership', models.FloatField(null=True)),
                ('obedience', models.FloatField(null=True)),
                ('faithfulness', models.FloatField(null=True)),
                ('alertness', models.FloatField(null=True)),
                ('questioning', models.FloatField(null=True)),
                ('awareness', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='accounting',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='agreement',
            field=models.ImageField(blank=True, default='', upload_to='staff/agreement'),
        ),
        migrations.AddField(
            model_name='staff',
            name='awareness',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='birth_date',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='staff',
            name='contract',
            field=models.ImageField(blank=True, default='', upload_to='staff/contract'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contract_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_month_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_month_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='staff',
            name='twelve_month_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='staff',
            name='twelve_month_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='general',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='paralegal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pv_care',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='records',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='security',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='shelter',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staffreview',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.Staff'),
        ),
        migrations.AddField(
            model_name='staffmiscellaneous',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.Staff'),
        ),
        migrations.AddField(
            model_name='staffmiscellaneous',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_border_stations.StaffMiscellaneousTypes'),
        ),
        
        migrations.RunSQL("update dataentry_permission set action='VIEW_BASIC', min_level='PROJECT' where permission_group = 'STAFF' and action='VIEW'"),
        migrations.RunSQL("update dataentry_permission set action='EDIT_BASIC', min_level='PROJECT' where permission_group = 'STAFF' and action='EDIT'"), 
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','VIEW_REVIEW','PROJECT',3)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','EDIT_REVIEW','PROJECT',4)"),
        migrations.RunSQL("update dataentry_permission set display_order=5, min_level='PROJECT' where permission_group = 'STAFF' and action='ADD'"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','VIEW_CONTRACT','PROJECT',6)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','EDIT_CONTRACT','PROJECT',7)"),
        migrations.RunSQL("update dataentry_permission set display_order=8 where permission_group = 'STAFF' and action='DELETE'"),
        
        migrations.RunSQL("insert into dataentry_userlocationpermission (account_id, country_id, station_id, permission_id) "\
                            "select du.account_id, du.country_id, du.station_id, dp2.id "\
                          "from dataentry_userlocationpermission du, dataentry_permission dp2 "\
                          "where du.permission_id = (select id from dataentry_permission dp where dp.permission_group='STAFF' and action='ADD') "\
                          "and dp2.permission_group='STAFF' and action='VIEW_REVIEW'"),
        migrations.RunSQL("insert into dataentry_userlocationpermission (account_id, country_id, station_id, permission_id) "\
                            "select du.account_id, du.country_id, du.station_id, dp2.id "\
                          "from dataentry_userlocationpermission du, dataentry_permission dp2 "\
                          "where du.permission_id = (select id from dataentry_permission dp where dp.permission_group='STAFF' and action='ADD') "\
                          "and dp2.permission_group='STAFF' and action='EDIT_REVIEW'"),
        migrations.RunSQL("insert into dataentry_userlocationpermission (account_id, country_id, station_id, permission_id) "\
                            "select du.account_id, du.country_id, du.station_id, dp2.id "\
                          "from dataentry_userlocationpermission du, dataentry_permission dp2 "\
                          "where du.permission_id = (select id from dataentry_permission dp where dp.permission_group='STAFF' and action='DELETE') "\
                          "and dp2.permission_group='STAFF' and action='VIEW_CONTRACT'"),
        migrations.RunSQL("insert into dataentry_userlocationpermission (account_id, country_id, station_id, permission_id) "\
                            "select du.account_id, du.country_id, du.station_id, dp2.id "\
                          "from dataentry_userlocationpermission du, dataentry_permission dp2 "\
                          "where du.permission_id = (select id from dataentry_permission dp where dp.permission_group='STAFF' and action='DELETE') "\
                          "and dp2.permission_group='STAFF' and action='EDIT_CONTRACT'"),
        
        migrations.RunPython(populate_staff_totals),
    ]
