# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0258_auto_20230509_1844'),
        ('static_border_stations', '0007_auto_20231205_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='member_projects',
            field=models.ManyToManyField(related_name='member_projects', to='dataentry.BorderStation'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='misconduct_agreement',
            field=models.ImageField(blank=True, default='', upload_to='committee/misconduct'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='sc_agreement',
            field=models.ImageField(blank=True, default='', upload_to='committee/sc_agreement'),
        ),
        
        migrations.RunSQL("insert into static_border_stations_committeemember_member_projects (committeemember_id, borderstation_id) "\
                          "select id, border_station_id from static_border_stations_committeemember where border_station_id is not null"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('SUBCOMMITTEE','VIEW_BASIC','COUNTRY',1)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('SUBCOMMITTEE','EDIT_BASIC','COUNTRY',2)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('SUBCOMMITTEE','ADD','COUNTRY',3)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('SUBCOMMITTEE','VIEW_CONTRACT','COUNTRY',4)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('SUBCOMMITTEE','EDIT_CONTRACT','COUNTRY',5)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('SUBCOMMITTEE','DELETE','COUNTRY',6)"),
        migrations.RunSQL("update static_border_stations_committeemember "\
                          "set country_id = (select operating_country_id from dataentry_borderstation db where db.id = border_station_id) "\
                          "where border_station_id is not null"),
    ]
