# Generated by Django 4.2.10 on 2024-03-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_border_stations', '0007_auto_20240125_1952'),
    ]

    operations = [
       migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','EXPORT','COUNTRY',9)"),
    ]
