# Generated by Django 4.2.10 on 2024-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_border_stations', '0008_auto_20240304_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='staff_photos'),
        ),
    ]
