# Generated by Django 4.2.10 on 2024-12-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('static_border_stations', '0009_staff_photo'),
    ]

    def migrate_id_expiration(apps, schema_editor):
        countries_to_migrate = ['Kenya', 'Lesotho', 'Liberia', 'Mozambique', 'Namibia', 'Rwanda', 'Sierra Leone',
                                'Zambia', 'Bangladesh']

        misc_type_class = apps.get_model(app_label='static_border_stations', model_name='StaffMiscellaneousTypes')
        id_expiration_type = misc_type_class()
        id_expiration_type.name = 'ID Card Expiration'
        id_expiration_type.type = 'date'
        id_expiration_type.save()

        country_model = apps.get_model(app_label='dataentry', model_name='Country')
        countries = country_model.objects.filter(name__in=countries_to_migrate)
        for country in countries:
            id_expiration_type.countries.add(country)

        misc_entry_class = apps.get_model(app_label='static_border_stations', model_name='StaffMiscellaneous')
        staff_model = apps.get_model(app_label='static_border_stations', model_name='Staff')
        staff_list = staff_model.objects.filter(country__in=countries)
        for staff in staff_list:
            if staff.id_card_expiration is None:
                value = ''
            else:
                value = staff.id_card_expiration
            misc_entry = misc_entry_class()
            misc_entry.staff = staff
            misc_entry.type = id_expiration_type
            misc_entry.value = value
            misc_entry.save()

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=127, null=True),
        ),

        migrations.RunPython(migrate_id_expiration),
    ]
