# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interceptee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('photo', models.ImageField(default=b'', upload_to=b'interceptee_photos', blank=True)),
                ('kind', models.CharField(max_length=4, choices=[(b'v', b'Victim'), (b't', b'Trafficker')])),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=4, choices=[(b'f', b'F'), (b'm', b'M')])),
                ('age', models.PositiveIntegerField(null=True, blank=True)),
                ('district', models.CharField(max_length=255, blank=True)),
                ('vdc', models.CharField(max_length=255, verbose_name=b'VDC', blank=True)),
                ('phone_contact', models.CharField(max_length=255, blank=True)),
                ('relation_to', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='InterceptionRecord',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date_form_received', models.DateTimeField()),
                ('irf_number', models.CharField(max_length=20, verbose_name=b'IRF #:')),
                ('date_time_of_interception', models.DateTimeField(verbose_name=b'Date/Time:')),
                ('date_time_entered_into_system', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('number_of_victims', models.PositiveIntegerField(null=True, verbose_name=b'# of victims:', blank=True)),
                ('number_of_traffickers', models.PositiveIntegerField(null=True, verbose_name=b'# of traffickers', blank=True)),
                ('location', models.CharField(max_length=255, verbose_name=b'Location:')),
                ('staff_name', models.CharField(max_length=255, verbose_name=b'Staff Name:')),
                ('who_in_group_alone', models.BooleanField(default=False, verbose_name=b'Alone')),
                ('who_in_group_husbandwife', models.BooleanField(default=False, verbose_name=b'Husband / Wife')),
                ('who_in_group_relative', models.BooleanField(default=False, verbose_name=b'Own brother, sister / relative')),
                ('drugged_or_drowsy', models.BooleanField(default=False, verbose_name=b'Girl appears drugged or drowsy')),
                ('meeting_someone_across_border', models.BooleanField(default=False, verbose_name=b'Is meeting a someone just across border')),
                ('seen_in_last_month_in_nepal', models.BooleanField(default=False, verbose_name=b"Meeting someone she's seen in Nepal in the last month")),
                ('traveling_with_someone_not_with_her', models.BooleanField(default=False, verbose_name=b'Was travelling with someone not with her')),
                ('wife_under_18', models.BooleanField(default=False, verbose_name=b'Wife is under 18')),
                ('married_in_past_2_weeks', models.BooleanField(default=False, verbose_name=b'Married in the past 2 weeks')),
                ('married_in_past_2_8_weeks', models.BooleanField(default=False, verbose_name=b'Married within the past 2-8 weeks')),
                ('less_than_2_weeks_before_eloping', models.BooleanField(default=False, verbose_name=b'Less than 2 weeks before eloping')),
                ('between_2_12_weeks_before_eloping', models.BooleanField(default=False, verbose_name=b'2-12 weeks before eloping')),
                ('caste_not_same_as_relative', models.BooleanField(default=False, verbose_name=b'Caste not the same as alleged relative')),
                ('caught_in_lie', models.BooleanField(default=False, verbose_name=b'Caught in a lie or contradiction')),
                ('other_red_flag', models.BooleanField(default=False, verbose_name=b'Other Red Flag')),
                ('other_red_flag_value', models.CharField(max_length=255, blank=True)),
                ('where_going_job', models.BooleanField(default=False, verbose_name=b'Job')),
                ('where_going_visit', models.BooleanField(default=False, verbose_name=b'Visit / Family / Returning Home')),
                ('where_going_shopping', models.BooleanField(default=False, verbose_name=b'Shopping')),
                ('where_going_study', models.BooleanField(default=False, verbose_name=b'Study')),
                ('where_going_treatment', models.BooleanField(default=False, verbose_name=b'Treatment')),
                ('doesnt_know_going_to_india', models.BooleanField(default=False, verbose_name=b"Doesn't know she's going to India")),
                ('running_away_over_18', models.BooleanField(default=False, verbose_name=b'Running away from home (18 years or older)')),
                ('running_away_under_18', models.BooleanField(default=False, verbose_name=b'Running away from home (under 18 years old)')),
                ('going_to_gulf_for_work', models.BooleanField(default=False, verbose_name=b'Going to Gulf for work through India')),
                ('no_address_in_india', models.BooleanField(default=False, verbose_name=b'No address in India')),
                ('no_company_phone', models.BooleanField(default=False, verbose_name=b'No company phone number')),
                ('no_appointment_letter', models.BooleanField(default=False, verbose_name=b'No Appointment Letter')),
                ('valid_gulf_country_visa', models.BooleanField(default=False, verbose_name=b'Has a valid gulf country visa in passport')),
                ('passport_with_broker', models.BooleanField(default=False, verbose_name=b'Passport is with a broker')),
                ('job_too_good_to_be_true', models.BooleanField(default=False, verbose_name=b'Job is too good to be true')),
                ('not_real_job', models.BooleanField(default=False, verbose_name=b'Not a real job')),
                ('couldnt_confirm_job', models.BooleanField(default=False, verbose_name=b'Could not confirm job')),
                ('no_bags_long_trip', models.BooleanField(default=False, verbose_name=b'No bags though claim to be going for a long time')),
                ('shopping_overnight_stuff_in_bags', models.BooleanField(default=False, verbose_name=b'Shopping - Stuff for overnight stay in bags')),
                ('no_enrollment_docs', models.BooleanField(default=False, verbose_name=b'No documentation of enrollment')),
                ('doesnt_know_school_name', models.BooleanField(default=False, verbose_name=b"Does not Know School's Name and location")),
                ('no_school_phone', models.BooleanField(default=False, verbose_name=b'No phone number for School')),
                ('not_enrolled_in_school', models.BooleanField(default=False, verbose_name=b'Not enrolled in school')),
                ('reluctant_treatment_info', models.BooleanField(default=False, verbose_name=b'Reluctant to give info about treatment')),
                ('no_medical_documents', models.BooleanField(default=False, verbose_name=b'Does not have medical documents')),
                ('fake_medical_documents', models.BooleanField(default=False, verbose_name=b'Fake Medical documents')),
                ('no_medical_appointment', models.BooleanField(default=False, verbose_name=b'No medical appointment')),
                ('doesnt_know_villiage_details', models.BooleanField(default=False, verbose_name=b"Doesn't know details about village")),
                ('reluctant_villiage_info', models.BooleanField(default=False, verbose_name=b'Reluctant to give info about village')),
                ('reluctant_family_info', models.BooleanField(default=False, verbose_name=b'Reluctant to give family info')),
                ('refuses_family_info', models.BooleanField(default=False, verbose_name=b'Will not give family info')),
                ('under_18_cant_contact_family', models.BooleanField(default=False, verbose_name=b'No family contact established')),
                ('under_18_family_doesnt_know', models.BooleanField(default=False, verbose_name=b"Family doesn't know she is going to India")),
                ('under_18_family_unwilling', models.BooleanField(default=False, verbose_name=b'Family unwilling to let her go')),
                ('over_18_family_doesnt_know', models.BooleanField(default=False, verbose_name=b'Family members do not know she is going to India')),
                ('over_18_family_unwilling', models.BooleanField(default=False, verbose_name=b'Family members unwilling to let her go')),
                ('talked_to_family_member_brother', models.BooleanField(default=False, verbose_name=b'Own brother')),
                ('talked_to_family_member_sister', models.BooleanField(default=False, verbose_name=b'Own sister')),
                ('talked_to_family_member_father', models.BooleanField(default=False, verbose_name=b'Own father')),
                ('talked_to_family_member_mother', models.BooleanField(default=False, verbose_name=b'Own mother')),
                ('talked_to_family_member_grandparent', models.BooleanField(default=False, verbose_name=b'Own grandparent')),
                ('talked_to_family_member_aunt_uncle', models.BooleanField(default=False, verbose_name=b'Own aunt / uncle')),
                ('talked_to_family_member_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('talked_to_family_member_other_value', models.CharField(max_length=255, blank=True)),
                ('reported_total_red_flags', models.IntegerField(null=True, verbose_name=b'Reported Total Red Flag Points:', blank=True)),
                ('contact_noticed', models.BooleanField(default=False, verbose_name=b'Contact')),
                ('which_contact_hotel_owner', models.BooleanField(default=False, verbose_name=b'Hotel owner')),
                ('which_contact_rickshaw_driver', models.BooleanField(default=False, verbose_name=b'Rickshaw driver')),
                ('which_contact_taxi_driver', models.BooleanField(default=False, verbose_name=b'Taxi driver')),
                ('which_contact_bus_driver', models.BooleanField(default=False, verbose_name=b'Bus driver')),
                ('which_contact_church_member', models.BooleanField(default=False, verbose_name=b'Church member')),
                ('which_contact_other_ngo', models.BooleanField(default=False, verbose_name=b'Other NGO')),
                ('which_contact_police', models.BooleanField(default=False, verbose_name=b'Police')),
                ('which_contact_subcommittee_member', models.BooleanField(default=False, verbose_name=b'Subcommittee member')),
                ('which_contact_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('which_contact_other_value', models.CharField(max_length=255, blank=True)),
                ('contact_paid', models.NullBooleanField()),
                ('contact_paid_how_much', models.CharField(max_length=255, verbose_name=b'How much?', blank=True)),
                ('staff_noticed', models.BooleanField(default=False, verbose_name=b'Staff')),
                ('staff_who_noticed', models.CharField(max_length=255, verbose_name=b'Staff who noticed:', blank=True)),
                ('noticed_hesitant', models.BooleanField(default=False, verbose_name=b'Hesitant')),
                ('noticed_nervous_or_afraid', models.BooleanField(default=False, verbose_name=b'Nervous or afraid')),
                ('noticed_hurrying', models.BooleanField(default=False, verbose_name=b'Hurrying')),
                ('noticed_drugged_or_drowsy', models.BooleanField(default=False, verbose_name=b'Drugged or drowsy')),
                ('noticed_new_clothes', models.BooleanField(default=False, verbose_name=b'New clothes')),
                ('noticed_dirty_clothes', models.BooleanField(default=False, verbose_name=b'Dirty clothes')),
                ('noticed_carrying_full_bags', models.BooleanField(default=False, verbose_name=b'Carrying Full bags')),
                ('noticed_village_dress', models.BooleanField(default=False, verbose_name=b'Village Dress')),
                ('noticed_indian_looking', models.BooleanField(default=False, verbose_name=b'Indian looking')),
                ('noticed_typical_village_look', models.BooleanField(default=False, verbose_name=b'Typical village look')),
                ('noticed_looked_like_agent', models.BooleanField(default=False, verbose_name=b'Looked like agent')),
                ('noticed_caste_difference', models.BooleanField(default=False, verbose_name=b'Caste difference')),
                ('noticed_young_looking', models.BooleanField(default=False, verbose_name=b'Young looking')),
                ('noticed_waiting_sitting', models.BooleanField(default=False, verbose_name=b'Waiting / sitting')),
                ('noticed_walking_to_border', models.BooleanField(default=False, verbose_name=b'Walking to border')),
                ('noticed_roaming_around', models.BooleanField(default=False, verbose_name=b'Roaming around')),
                ('noticed_exiting_vehicle', models.BooleanField(default=False, verbose_name=b'Exiting vehicle')),
                ('noticed_heading_to_vehicle', models.BooleanField(default=False, verbose_name=b'Heading to vehicle')),
                ('noticed_in_a_vehicle', models.BooleanField(default=False, verbose_name=b'In a vehicle')),
                ('noticed_in_a_rickshaw', models.BooleanField(default=False, verbose_name=b'In a rickshaw')),
                ('noticed_in_a_cart', models.BooleanField(default=False, verbose_name=b'In a cart')),
                ('noticed_carrying_a_baby', models.BooleanField(default=False, verbose_name=b'Carrying a baby')),
                ('noticed_on_the_phone', models.BooleanField(default=False, verbose_name=b'On the phone')),
                ('noticed_other_sign', models.BooleanField(default=False, verbose_name=b'Other sign:')),
                ('noticed_other_sign_value', models.CharField(max_length=255, blank=True)),
                ('call_subcommittee_chair', models.BooleanField(default=False, verbose_name=b'Call Subcommittee Chair')),
                ('call_thn_to_cross_check', models.BooleanField(default=False, verbose_name=b'Call THN to cross-check the names (6223856)')),
                ('name_came_up_before', models.NullBooleanField()),
                ('name_came_up_before_value', models.PositiveIntegerField(null=True, verbose_name=b'If yes, write the # from the table above:', blank=True)),
                ('scan_and_submit_same_day', models.BooleanField(default=False, verbose_name=b'Scan and submit to THN the same day')),
                ('interception_type_gulf_countries', models.BooleanField(default=False, verbose_name=b'Gulf Countries')),
                ('interception_type_india_trafficking', models.BooleanField(default=False, verbose_name=b'India Trafficking')),
                ('interception_type_unsafe_migration', models.BooleanField(default=False, verbose_name=b'Unsafe Migration')),
                ('interception_type_circus', models.BooleanField(default=False, verbose_name=b'Circus')),
                ('interception_type_runaway', models.BooleanField(default=False, verbose_name=b'Runaway')),
                ('trafficker_taken_into_custody', models.CharField(max_length=20, null=True, blank=True)),
                ('how_sure_was_trafficking', models.IntegerField(verbose_name=b'How sure are you that it was trafficking case?', choices=[(1, b'1 - Not at all sure'), (2, b'2 - Unsure but suspects it'), (3, b'3 - Somewhat sure'), (4, b'4 - Very sure'), (5, b'5 - Absolutely sure')])),
                ('has_signature', models.BooleanField(verbose_name=b'Scanned form has signature?')),
                ('scanned_form', models.FileField(default=b'', upload_to=b'scanned_irf_forms', verbose_name=b'Attach scanned copy of form (pdf or image)', blank=True)),
                ('form_entered_by', models.ForeignKey(related_name=b'irfs_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time_last_updated'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VictimInterview',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('vif_number', models.CharField(max_length=20, verbose_name=b'VIF #')),
                ('date', models.DateField(verbose_name=b'Date')),
                ('date_time_entered_into_system', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('number_of_victims', models.PositiveIntegerField(null=True, verbose_name=b'# of victims', blank=True)),
                ('number_of_traffickers', models.PositiveIntegerField(null=True, verbose_name=b'# of traffickers', blank=True)),
                ('location', models.CharField(max_length=255, blank=True)),
                ('interviewer', models.CharField(max_length=255)),
                ('statement_read_before_beginning', models.BooleanField(default=False, verbose_name=b'Check the box if form is signed')),
                ('permission_to_use_photograph', models.BooleanField(default=False, verbose_name=b'Check the box if form is signed')),
                ('victim_name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('victim_gender', models.CharField(max_length=12, verbose_name=b'Gender', choices=[(b'male', b'Male'), (b'female', b'Female')])),
                ('victim_address_district', models.CharField(max_length=255, verbose_name=b'District', blank=True)),
                ('victim_address_vdc', models.CharField(max_length=255, verbose_name=b'VDC', blank=True)),
                ('victim_address_ward', models.CharField(max_length=255, verbose_name=b'Ward #', blank=True)),
                ('victim_phone', models.CharField(max_length=255, verbose_name=b'Phone #', blank=True)),
                ('victim_age', models.CharField(max_length=255, verbose_name=b'Age', blank=True)),
                ('victim_height', models.PositiveIntegerField(null=True, verbose_name=b'Height(ft)', blank=True)),
                ('victim_weight', models.PositiveIntegerField(null=True, verbose_name=b'Weight(kg)', blank=True)),
                ('victim_caste_magar', models.BooleanField(default=False, verbose_name=b'Magar')),
                ('victim_caste_jaisi', models.BooleanField(default=False, verbose_name=b'Jaisi')),
                ('victim_caste_thakuri', models.BooleanField(default=False, verbose_name=b'Thakuri')),
                ('victim_caste_brahmin', models.BooleanField(default=False, verbose_name=b'Brahmin')),
                ('victim_caste_chhetri', models.BooleanField(default=False, verbose_name=b'Chhetri')),
                ('victim_caste_newar', models.BooleanField(default=False, verbose_name=b'Newar')),
                ('victim_caste_tamang', models.BooleanField(default=False, verbose_name=b'Tamang')),
                ('victim_caste_mongolian', models.BooleanField(default=False, verbose_name=b'Mongolian')),
                ('victim_caste_muslim', models.BooleanField(default=False, verbose_name=b'Muslim')),
                ('victim_caste_madeshi_terai', models.BooleanField(default=False, verbose_name=b'Madeshi / Terai Ethnic Group')),
                ('victim_caste_dalit', models.BooleanField(default=False, verbose_name=b'Dalit / under-priviledged')),
                ('victim_caste_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('victim_caste_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_occupation_unemployed', models.BooleanField(default=False, verbose_name=b'Unemployed')),
                ('victim_occupation_farmer', models.BooleanField(default=False, verbose_name=b'Farmer')),
                ('victim_occupation_wage_laborer', models.BooleanField(default=False, verbose_name=b'Wage-laborer')),
                ('victim_occupation_business_owner', models.BooleanField(default=False, verbose_name=b'Business Owner')),
                ('victim_occupation_migrant_worker', models.BooleanField(default=False, verbose_name=b'Migrant Worker')),
                ('victim_occupation_tailoring', models.BooleanField(default=False, verbose_name=b'Tailoring')),
                ('victim_occupation_housewife', models.BooleanField(default=False, verbose_name=b'Housewife')),
                ('victim_occupation_animal_husbandry', models.BooleanField(default=False, verbose_name=b'Animal Husbandry')),
                ('victim_occupation_domestic_work', models.BooleanField(default=False, verbose_name=b'Domestic Work')),
                ('victim_occupation_shopkeeper', models.BooleanField(default=False, verbose_name=b'Shopkeeper')),
                ('victim_occupation_hotel', models.BooleanField(default=False, verbose_name=b'Hotel')),
                ('victim_occupation_factory', models.BooleanField(default=False, verbose_name=b'Factory')),
                ('victim_occupation_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('victim_occupation_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_marital_status_single', models.BooleanField(default=False, verbose_name=b'Single')),
                ('victim_marital_status_married', models.BooleanField(default=False, verbose_name=b'Married')),
                ('victim_marital_status_widow', models.BooleanField(default=False, verbose_name=b'Widow')),
                ('victim_marital_status_divorced', models.BooleanField(default=False, verbose_name=b'Divorced')),
                ('victim_marital_status_husband_has_other_wives', models.BooleanField(default=False, verbose_name=b'Husband has other wives')),
                ('victim_marital_status_abandoned_by_husband', models.BooleanField(default=False, verbose_name=b'Abandoned by husband')),
                ('victim_lives_with_own_parents', models.BooleanField(default=False, verbose_name=b'Own Parent(s)')),
                ('victim_lives_with_husband', models.BooleanField(default=False, verbose_name=b'Husband')),
                ('victim_lives_with_husbands_family', models.BooleanField(default=False, verbose_name=b"Husband's family")),
                ('victim_lives_with_friends', models.BooleanField(default=False, verbose_name=b'Friends')),
                ('victim_lives_with_alone', models.BooleanField(default=False, verbose_name=b'Alone')),
                ('victim_lives_with_other_relative', models.BooleanField(default=False, verbose_name=b'Other Relative')),
                ('victim_lives_with_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('victim_lives_with_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_num_in_family', models.IntegerField(null=True, verbose_name=b'How many people are in your (own) family?', blank=True)),
                ('victim_primary_guardian_own_parents', models.BooleanField(default=False, verbose_name=b'Own Parent(s)')),
                ('victim_primary_guardian_husband', models.BooleanField(default=False, verbose_name=b'Husband')),
                ('victim_primary_guardian_other_relative', models.BooleanField(default=False, verbose_name=b'Other Relative')),
                ('victim_primary_guardian_non_relative', models.BooleanField(default=False, verbose_name=b'Non-relative')),
                ('victim_primary_guardian_no_one', models.BooleanField(default=False, verbose_name=b'No one (I have no guardian)')),
                ('victim_guardian_address_district', models.CharField(max_length=255, verbose_name=b'District', blank=True)),
                ('victim_guardian_address_vdc', models.CharField(max_length=255, verbose_name=b'VDC', blank=True)),
                ('victim_guardian_address_ward', models.CharField(max_length=255, verbose_name=b'Ward #', blank=True)),
                ('victim_guardian_phone', models.CharField(max_length=255, verbose_name=b'Phone #', blank=True)),
                ('victim_parents_marital_status_single', models.BooleanField(default=False, verbose_name=b'Single')),
                ('victim_parents_marital_status_married', models.BooleanField(default=False, verbose_name=b'Married')),
                ('victim_parents_marital_status_widow', models.BooleanField(default=False, verbose_name=b'Widow')),
                ('victim_parents_marital_status_father_has_other_wives', models.BooleanField(default=False, verbose_name=b'My father has other wives')),
                ('victim_parents_marital_separated', models.BooleanField(default=False, verbose_name=b'Separated (Legally married)')),
                ('victim_parents_marital_divorced', models.BooleanField(default=False, verbose_name=b'Divorced')),
                ('victim_education_level_none', models.BooleanField(default=False, verbose_name=b'None')),
                ('victim_education_level_informal', models.BooleanField(default=False, verbose_name=b'Only informal (adult)')),
                ('victim_education_level_primary', models.BooleanField(default=False, verbose_name=b'Primary only')),
                ('victim_education_level_grade_4_8', models.BooleanField(default=False, verbose_name=b'Grade 4-8')),
                ('victim_education_level_grade_9_10', models.BooleanField(default=False, verbose_name=b'Grade 9-10')),
                ('victim_education_level_slc', models.BooleanField(default=False, verbose_name=b'SLC')),
                ('victim_education_level_11_12', models.BooleanField(default=False, verbose_name=b'11-12')),
                ('victim_education_level_bachelors', models.BooleanField(default=False, verbose_name=b'Bachelors')),
                ('victim_education_level_masters', models.BooleanField(default=False, verbose_name=b'Masters')),
                ('victim_is_literate', models.NullBooleanField(verbose_name=b'Is the victim literate?')),
                ('migration_plans_education', models.BooleanField(default=False, verbose_name=b'Education')),
                ('migration_plans_travel_tour', models.BooleanField(default=False, verbose_name=b'Travel / Tour')),
                ('migration_plans_shopping', models.BooleanField(default=False, verbose_name=b'Shopping')),
                ('migration_plans_eloping', models.BooleanField(default=False, verbose_name=b'Eloping')),
                ('migration_plans_arranged_marriage', models.BooleanField(default=False, verbose_name=b'Arranged Marriage')),
                ('migration_plans_meet_own_family', models.BooleanField(default=False, verbose_name=b'Meet your own family')),
                ('migration_plans_visit_brokers_home', models.BooleanField(default=False, verbose_name=b"Visit broker's home")),
                ('migration_plans_medical_treatment', models.BooleanField(default=False, verbose_name=b'Medical treatment')),
                ('migration_plans_job_broker_didnt_say', models.BooleanField(default=False, verbose_name=b'Job - Broker did not say what job')),
                ('migration_plans_job_baby_care', models.BooleanField(default=False, verbose_name=b'Job - Baby Care')),
                ('migration_plans_job_factory', models.BooleanField(default=False, verbose_name=b'Job - Factory')),
                ('migration_plans_job_hotel', models.BooleanField(default=False, verbose_name=b'Job - Hotel')),
                ('migration_plans_job_shop', models.BooleanField(default=False, verbose_name=b'Job - Shop')),
                ('migration_plans_job_laborer', models.BooleanField(default=False, verbose_name=b'Job - Laborer')),
                ('migration_plans_job_brothel', models.BooleanField(default=False, verbose_name=b'Job - Brothel')),
                ('migration_plans_job_household', models.BooleanField(default=False, verbose_name=b'Job - Household')),
                ('migration_plans_job_other', models.BooleanField(default=False, verbose_name=b'Job - Other')),
                ('migration_plans_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('migration_plans_job_other_value', models.CharField(max_length=255, blank=True)),
                ('migration_plans_other_value', models.CharField(max_length=255, blank=True)),
                ('primary_motivation_support_myself', models.BooleanField(default=False, verbose_name=b'Support myself')),
                ('primary_motivation_support_family', models.BooleanField(default=False, verbose_name=b'Support family')),
                ('primary_motivation_personal_debt', models.BooleanField(default=False, verbose_name=b'Personal Debt')),
                ('primary_motivation_family_debt', models.BooleanField(default=False, verbose_name=b'Family Debt')),
                ('primary_motivation_love_marriage', models.BooleanField(default=False, verbose_name=b'Love / Marriage')),
                ('primary_motivation_bad_home_marriage', models.BooleanField(default=False, verbose_name=b'Bad home / marriage')),
                ('primary_motivation_get_education', models.BooleanField(default=False, verbose_name=b'Get an education')),
                ('primary_motivation_tour_travel', models.BooleanField(default=False, verbose_name=b'Tour / Travel')),
                ('primary_motivation_didnt_know', models.BooleanField(default=False, verbose_name=b"Didn't know I was going abroad")),
                ('primary_motivation_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('primary_motivation_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_where_going_region_india', models.NullBooleanField(verbose_name=b'India')),
                ('victim_where_going_region_gulf', models.NullBooleanField(verbose_name=b'Gulf / Other')),
                ('victim_where_going_india_delhi', models.NullBooleanField(verbose_name=b'Delhi')),
                ('victim_where_going_india_mumbai', models.NullBooleanField(verbose_name=b'Mumbai')),
                ('victim_where_going_india_surat', models.NullBooleanField(verbose_name=b'Surat')),
                ('victim_where_going_india_rajastan', models.NullBooleanField(verbose_name=b'Rajastan')),
                ('victim_where_going_india_kolkata', models.NullBooleanField(verbose_name=b'Kolkata')),
                ('victim_where_going_india_pune', models.NullBooleanField(verbose_name=b'Pune')),
                ('victim_where_going_india_jaipur', models.NullBooleanField(verbose_name=b'Jaipur')),
                ('victim_where_going_india_bihar', models.NullBooleanField(verbose_name=b'Bihar')),
                ('victim_where_going_india_didnt_know', models.NullBooleanField(verbose_name=b'Did Not Know')),
                ('victim_where_going_india_other', models.NullBooleanField(verbose_name=b'Other')),
                ('victim_where_going_india_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_where_going_gulf_lebanon', models.NullBooleanField(verbose_name=b'Lebanon')),
                ('victim_where_going_gulf_dubai', models.NullBooleanField(verbose_name=b'Dubai')),
                ('victim_where_going_gulf_malaysia', models.NullBooleanField(verbose_name=b'Malaysia')),
                ('victim_where_going_gulf_oman', models.NullBooleanField(verbose_name=b'Oman')),
                ('victim_where_going_gulf_saudi_arabia', models.NullBooleanField(verbose_name=b'Saudi Arabia')),
                ('victim_where_going_gulf_kuwait', models.NullBooleanField(verbose_name=b'Kuwait')),
                ('victim_where_going_gulf_qatar', models.NullBooleanField(verbose_name=b'Qatar')),
                ('victim_where_going_gulf_didnt_know', models.NullBooleanField(verbose_name=b'Did Not Know')),
                ('victim_where_going_gulf_other', models.NullBooleanField(verbose_name=b'Other')),
                ('victim_where_going_gulf_other_value', models.CharField(max_length=255, blank=True)),
                ('manpower_involved', models.NullBooleanField(verbose_name=b'Was a manpower involved?')),
                ('victim_recruited_in_village', models.BooleanField(verbose_name=b'Did someone recruit you in your village and persuade you to abroad?')),
                ('brokers_relation_to_victim_own_dad', models.BooleanField(default=False, verbose_name=b'Own dad')),
                ('brokers_relation_to_victim_own_mom', models.BooleanField(default=False, verbose_name=b'Own mom')),
                ('brokers_relation_to_victim_own_uncle', models.BooleanField(default=False, verbose_name=b'Own uncle')),
                ('brokers_relation_to_victim_own_aunt', models.BooleanField(default=False, verbose_name=b'Own aunt')),
                ('brokers_relation_to_victim_own_bro', models.BooleanField(default=False, verbose_name=b'Own bro')),
                ('brokers_relation_to_victim_own_sister', models.BooleanField(default=False, verbose_name=b'Own sister')),
                ('brokers_relation_to_victim_own_other_relative', models.BooleanField(default=False, verbose_name=b'Other relative')),
                ('brokers_relation_to_victim_friend', models.BooleanField(default=False, verbose_name=b'Friend')),
                ('brokers_relation_to_victim_agent', models.BooleanField(default=False, verbose_name=b'Agent')),
                ('brokers_relation_to_victim_husband', models.BooleanField(default=False, verbose_name=b'Husband')),
                ('brokers_relation_to_victim_boyfriend', models.BooleanField(default=False, verbose_name=b'Boyfriend')),
                ('brokers_relation_to_victim_neighbor', models.BooleanField(default=False, verbose_name=b'Neighbor')),
                ('brokers_relation_to_victim_recently_met', models.BooleanField(default=False, verbose_name=b'Recently met')),
                ('brokers_relation_to_victim_contractor', models.BooleanField(default=False, verbose_name=b'Contractor')),
                ('brokers_relation_to_victim_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('brokers_relation_to_victim_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_married_to_broker_years', models.PositiveIntegerField(null=True, verbose_name=b'Years', blank=True)),
                ('victim_married_to_broker_months', models.PositiveIntegerField(null=True, verbose_name=b'Months', blank=True)),
                ('victim_how_met_broker_from_community', models.BooleanField(default=False, verbose_name=b'Broker is from my community')),
                ('victim_how_met_broker_at_work', models.BooleanField(default=False, verbose_name=b'At work')),
                ('victim_how_met_broker_at_school', models.BooleanField(default=False, verbose_name=b'At school')),
                ('victim_how_met_broker_job_advertisement', models.BooleanField(default=False, verbose_name=b'Job advertisement')),
                ('victim_how_met_broker_he_approached_me', models.BooleanField(default=False, verbose_name=b'He approached me')),
                ('victim_how_met_broker_through_friends', models.BooleanField(default=False, verbose_name=b'Through friends')),
                ('victim_how_met_broker_through_family', models.BooleanField(default=False, verbose_name=b'Through family')),
                ('victim_how_met_broker_at_wedding', models.BooleanField(default=False, verbose_name=b'At Wedding')),
                ('victim_how_met_broker_in_a_vehicle', models.BooleanField(default=False, verbose_name=b'In a Vehicle')),
                ('victim_how_met_broker_in_a_hospital', models.BooleanField(default=False, verbose_name=b'In a Hospital')),
                ('victim_how_met_broker_went_myself', models.BooleanField(default=False, verbose_name=b'Went to him myself')),
                ('victim_how_met_broker_called_my_mobile', models.BooleanField(default=False, verbose_name=b'Called my mobile')),
                ('victim_how_met_broker_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('victim_how_met_broker_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_how_met_broker_mobile_explanation', models.TextField(blank=True)),
                ('victim_how_long_known_broker_years', models.PositiveIntegerField(null=True, verbose_name=b'Years', blank=True)),
                ('victim_how_long_known_broker_months', models.PositiveIntegerField(null=True, verbose_name=b'Months', blank=True)),
                ('victim_how_expense_was_paid_paid_myself', models.BooleanField(default=False, verbose_name=b'I paid the expenses myself')),
                ('victim_how_expense_was_paid_broker_paid_all', models.BooleanField(default=False, verbose_name=b'The broker paid all the expenses')),
                ('victim_how_expense_was_paid_gave_money_to_broker', models.BooleanField(default=False, verbose_name=b'I gave a sum of money to the broker')),
                ('victim_how_expense_was_paid_broker_gave_loan', models.BooleanField(default=False, verbose_name=b'The broker paid the expenses and I have to pay him back')),
                ('victim_how_expense_was_paid_amount', models.DecimalField(null=True, verbose_name=b'Amount', max_digits=10, decimal_places=2, blank=True)),
                ('broker_works_in_job_location_no', models.BooleanField(default=False, verbose_name=b'No')),
                ('broker_works_in_job_location_yes', models.BooleanField(default=False, verbose_name=b'Yes')),
                ('broker_works_in_job_location_dont_know', models.BooleanField(default=False, verbose_name=b"Don't Know")),
                ('amount_victim_would_earn', models.DecimalField(null=True, verbose_name=b'Amount', max_digits=10, decimal_places=2, blank=True)),
                ('number_broker_made_similar_promises_to', models.PositiveIntegerField(null=True, blank=True)),
                ('victim_first_time_crossing_border', models.NullBooleanField()),
                ('victim_primary_means_of_travel_tourist_bus', models.BooleanField(default=False, verbose_name=b'Tourist Bus')),
                ('victim_primary_means_of_travel_motorbike', models.BooleanField(default=False, verbose_name=b'Motorbike')),
                ('victim_primary_means_of_travel_private_car', models.BooleanField(default=False, verbose_name=b'Private Car')),
                ('victim_primary_means_of_travel_local_bus', models.BooleanField(default=False, verbose_name=b'Local Bus')),
                ('victim_primary_means_of_travel_microbus', models.BooleanField(default=False, verbose_name=b'Microbus')),
                ('victim_primary_means_of_travel_plane', models.BooleanField(default=False, verbose_name=b'Plane')),
                ('victim_primary_means_of_travel_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('victim_primary_means_of_travel_other_value', models.CharField(max_length=255, blank=True)),
                ('victim_stayed_somewhere_between', models.BooleanField()),
                ('victim_how_long_stayed_between_days', models.PositiveIntegerField(null=True, verbose_name=b'Days', blank=True)),
                ('victim_how_long_stayed_between_start_date', models.DateField(null=True, verbose_name=b'Start Date', blank=True)),
                ('victim_was_hidden', models.NullBooleanField()),
                ('victim_was_hidden_explanation', models.TextField(blank=True)),
                ('victim_was_free_to_go_out', models.NullBooleanField()),
                ('victim_was_free_to_go_out_explanation', models.TextField(blank=True)),
                ('how_many_others_in_situation', models.PositiveIntegerField(null=True, blank=True)),
                ('others_in_situation_age_of_youngest', models.PositiveIntegerField(null=True, blank=True)),
                ('passport_made_no_passport_made', models.BooleanField(default=False, verbose_name=b'No passport made')),
                ('passport_made_real_passport_made', models.BooleanField(default=False, verbose_name=b'Real passport made')),
                ('passport_made_passport_included_false_name', models.BooleanField(default=False, verbose_name=b'Passport included a false name')),
                ('passport_made_passport_included_other_false_info', models.BooleanField(default=False, verbose_name=b'Passport included other false info')),
                ('passport_made_passport_was_fake', models.BooleanField(default=False, verbose_name=b'Passport was fake')),
                ('victim_passport_with_broker', models.NullBooleanField()),
                ('abuse_happened_sexual_harassment', models.BooleanField(default=False, verbose_name=b'Sexual Harassment')),
                ('abuse_happened_sexual_abuse', models.BooleanField(default=False, verbose_name=b'Sexual Abuse')),
                ('abuse_happened_physical_abuse', models.BooleanField(default=False, verbose_name=b'Physical Abuse')),
                ('abuse_happened_threats', models.BooleanField(default=False, verbose_name=b'Threats')),
                ('abuse_happened_denied_proper_food', models.BooleanField(default=False, verbose_name=b'Denied Proper Food')),
                ('abuse_happened_forced_to_take_drugs', models.BooleanField(default=False, verbose_name=b'Forced to take Drugs')),
                ('abuse_happened_by_whom', models.TextField(verbose_name=b'By whom?', blank=True)),
                ('abuse_happened_explanation', models.TextField(verbose_name=b'Explain', blank=True)),
                ('victim_traveled_with_broker_companion_yes', models.BooleanField(default=False, verbose_name=b'Yes')),
                ('victim_traveled_with_broker_companion_no', models.BooleanField(default=False, verbose_name=b'No')),
                ('victim_traveled_with_broker_companion_broker_took_me_to_border', models.BooleanField(default=False, verbose_name=b'Broker took me to border')),
                ('companion_with_when_intercepted', models.NullBooleanField()),
                ('planning_to_meet_companion_later', models.NullBooleanField()),
                ('money_changed_hands_broker_companion_no', models.BooleanField(default=False, verbose_name=b'No')),
                ('money_changed_hands_broker_companion_dont_know', models.BooleanField(default=False, verbose_name=b"Don't know")),
                ('money_changed_hands_broker_companion_broker_gave_money', models.BooleanField(default=False, verbose_name=b'Broker gave money to the companion')),
                ('money_changed_hands_broker_companion_companion_gave_money', models.BooleanField(default=False, verbose_name=b'Companion gave money to the broker')),
                ('meeting_at_border_yes', models.BooleanField(default=False, verbose_name=b'Yes')),
                ('meeting_at_border_no', models.BooleanField(default=False, verbose_name=b'No')),
                ('meeting_at_border_meeting_broker', models.BooleanField(default=False, verbose_name=b'Meeting Broker')),
                ('meeting_at_border_meeting_companion', models.BooleanField(default=False, verbose_name=b'Meeting Companion')),
                ('victim_knew_details_about_destination', models.BooleanField()),
                ('other_involved_person_in_india', models.NullBooleanField()),
                ('other_involved_husband_trafficker', models.NullBooleanField()),
                ('other_involved_someone_met_along_the_way', models.NullBooleanField()),
                ('other_involved_someone_involved_in_trafficking', models.NullBooleanField()),
                ('other_involved_place_involved_in_trafficking', models.NullBooleanField()),
                ('victim_has_worked_in_sex_industry', models.NullBooleanField()),
                ('victim_place_worked_involved_sending_girls_overseas', models.NullBooleanField()),
                ('awareness_before_interception_had_heard_not_how_bad', models.BooleanField(default=False, verbose_name=b'Had heard, but never knew how bad it was until I was intercepted by TH')),
                ('awareness_before_interception_knew_how_bad_not_happening_to_her', models.BooleanField(default=False, verbose_name=b"Knew how bad it was, but didn't think that was happening to her")),
                ('awareness_before_interception_never_heard', models.BooleanField(default=False, verbose_name=b'Had never heard about it')),
                ('attitude_towards_tiny_hands_thankful', models.BooleanField(default=False, verbose_name=b'Yes, thankful to TH for saving her')),
                ('attitude_towards_tiny_hands_blames', models.BooleanField(default=False, verbose_name=b'No, blames Tiny Hands for stopping her')),
                ('attitude_towards_tiny_hands_doesnt_know', models.BooleanField(default=False, verbose_name=b"Doesn't Know")),
                ('victim_heard_gospel_no', models.BooleanField(default=False, verbose_name=b'No, I have never heard')),
                ('victim_heard_gospel_heard_name_only', models.BooleanField(default=False, verbose_name=b'Has heard the name only')),
                ('victim_heard_gospel_heard_but_never_believed', models.BooleanField(default=False, verbose_name=b'Had heard the gospel but never believed')),
                ('victim_heard_gospel_already_believer', models.BooleanField(default=False, verbose_name=b'Was already a believer')),
                ('victim_beliefs_now_doesnt_believe', models.BooleanField(default=False, verbose_name=b"Doesn't believe in Jesus")),
                ('victim_beliefs_now_believes_no_church', models.BooleanField(default=False, verbose_name=b"Believes in Jesus, but doesn't plan to go to church")),
                ('victim_beliefs_now_believes_and_church', models.BooleanField(default=False, verbose_name=b'Believes in Jesus and plans to go to church')),
                ('tiny_hands_rating_border_staff', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Border Staff polite and respectful', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('tiny_hands_rating_shelter_staff', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Shelter Staff polite and respectful', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('tiny_hands_rating_trafficking_awareness', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Trafficking Awareness', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('tiny_hands_rating_shelter_accommodations', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Shelter Accommodations', choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('how_can_we_serve_you_better', models.TextField(blank=True)),
                ('guardian_knew_was_travelling_to_india', models.NullBooleanField()),
                ('family_pressured_victim', models.NullBooleanField()),
                ('family_will_try_sending_again', models.NullBooleanField()),
                ('victim_feels_safe_at_home', models.NullBooleanField()),
                ('victim_wants_to_go_home', models.NullBooleanField()),
                ('victim_home_had_sexual_abuse_never', models.BooleanField(default=False, verbose_name=b'Never')),
                ('victim_home_had_sexual_abuse_rarely', models.BooleanField(default=False, verbose_name=b'Rarely / Minor')),
                ('victim_home_had_sexual_abuse_frequently', models.BooleanField(default=False, verbose_name=b'Frequent / Severe')),
                ('victim_home_had_physical_abuse_never', models.BooleanField(default=False, verbose_name=b'Never')),
                ('victim_home_had_physical_abuse_rarely', models.BooleanField(default=False, verbose_name=b'Rarely / Minor')),
                ('victim_home_had_physical_abuse_frequently', models.BooleanField(default=False, verbose_name=b'Frequent / Severe')),
                ('victim_home_had_emotional_abuse_never', models.BooleanField(default=False, verbose_name=b'Never')),
                ('victim_home_had_emotional_abuse_rarely', models.BooleanField(default=False, verbose_name=b'Rarely / Minor')),
                ('victim_home_had_emotional_abuse_frequently', models.BooleanField(default=False, verbose_name=b'Frequent / Severe')),
                ('victim_guardian_drinks_alcohol_never', models.BooleanField(default=False, verbose_name=b'Never')),
                ('victim_guardian_drinks_alcohol_occasionally', models.BooleanField(default=False, verbose_name=b'Occasionally')),
                ('victim_guardian_drinks_alcohol_all_the_time', models.BooleanField(default=False, verbose_name=b'All the time')),
                ('victim_guardian_uses_drugs_never', models.BooleanField(default=False, verbose_name=b'Never')),
                ('victim_guardian_uses_drugs_occasionally', models.BooleanField(default=False, verbose_name=b'Occasionally')),
                ('victim_guardian_uses_drugs_all_the_time', models.BooleanField(default=False, verbose_name=b'All the time')),
                ('victim_family_economic_situation_no_basic_needs', models.BooleanField(default=False, verbose_name=b'Unable to meet basic needs')),
                ('victim_family_economic_situation_difficult_basic_needs', models.BooleanField(default=False, verbose_name=b'Able to meet only basic needs, but it is very difficult')),
                ('victim_family_economic_situation_comfortable_basic_needs', models.BooleanField(default=False, verbose_name=b'Comfortably meet basic needs, and can afford to buy some non-essential goods/services')),
                ('victim_family_economic_situation_wealthy', models.BooleanField(default=False, verbose_name=b'Wealthy')),
                ('victim_had_suicidal_thoughts', models.NullBooleanField()),
                ('reported_total_situational_alarms', models.PositiveIntegerField(null=True, blank=True)),
                ('legal_action_against_traffickers_no', models.BooleanField(default=False, verbose_name=b'No')),
                ('legal_action_against_traffickers_fir_filed', models.BooleanField(default=False, verbose_name=b'FIR filed against')),
                ('legal_action_against_traffickers_dofe_complaint', models.BooleanField(default=False, verbose_name=b'DoFE complaint against')),
                ('legal_action_fir_against_value', models.CharField(max_length=255, blank=True)),
                ('legal_action_dofe_against_value', models.CharField(max_length=255, blank=True)),
                ('reason_no_legal_no_trafficking_suspected', models.BooleanField(default=False, verbose_name=b'No trafficking suspected')),
                ('reason_no_legal_police_not_enough_info', models.BooleanField(default=False, verbose_name=b'Police say not enough information')),
                ('reason_no_legal_trafficker_is_own_people', models.BooleanField(default=False, verbose_name=b"Trafficker is victim's own people")),
                ('reason_no_legal_she_was_going_herself', models.BooleanField(default=False, verbose_name=b'She was going herself')),
                ('reason_no_legal_trafficker_ran_away', models.BooleanField(default=False, verbose_name=b'Trafficker ran away')),
                ('reason_no_legal_victim_afraid_of_reputation', models.BooleanField(default=False, verbose_name=b'Victim afraid of reputation')),
                ('reason_no_legal_victim_afraid_for_safety', models.BooleanField(default=False, verbose_name=b'Victim afraid for her safety')),
                ('reason_no_legal_family_afraid_of_reputation', models.BooleanField(default=False, verbose_name=b'Family afraid of reputation')),
                ('reason_no_legal_family_afraid_for_safety', models.BooleanField(default=False, verbose_name=b'Family afraid for her safety')),
                ('reason_no_legal_police_bribed', models.BooleanField(default=False, verbose_name=b'Police bribed by trafficker')),
                ('reason_no_legal_victim_family_bribed', models.BooleanField(default=False, verbose_name=b'Victim / family bribed by trafficker')),
                ('reason_no_legal_interference_by_powerful_people', models.BooleanField(default=False, verbose_name=b'Interference by powerful people')),
                ('reason_no_legal_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('reason_no_legal_interference_value', models.CharField(max_length=255, blank=True)),
                ('reason_no_legal_other_value', models.CharField(max_length=255, blank=True)),
                ('interviewer_recommendation_send_home', models.BooleanField(default=False, verbose_name=b'Plan to send the girl home to stay with her guardians')),
                ('interviewer_recommendation_send_to_other_relatives', models.BooleanField(default=False, verbose_name=b'Plan to send the girl to stay with other relatives')),
                ('interviewer_recommendation_find_other_place', models.BooleanField(default=False, verbose_name=b'Tiny Hands needs to help her find another place to go')),
                ('other_people_and_places_involved', models.NullBooleanField()),
                ('has_signature', models.BooleanField(verbose_name=b'Scanned form has signature')),
                ('case_notes', models.TextField(verbose_name=b'Case Notes', blank=True)),
                ('scanned_form', models.FileField(default=b'', upload_to=b'scanned_vif_forms', verbose_name=b'Attach scanned copy of form (pdf or image)', blank=True)),
            ],
            options={
                'ordering': ['-date_time_last_updated'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VictimInterviewLocationBox',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('which_place_india_meetpoint', models.BooleanField(default=False, verbose_name=b'India Meet Point')),
                ('which_place_manpower', models.BooleanField(default=False, verbose_name=b'Manpower')),
                ('which_place_transit_hideout', models.BooleanField(default=False, verbose_name=b'Transit Hideout')),
                ('which_place_destination', models.BooleanField(default=False, verbose_name=b'Destination')),
                ('which_place_passport', models.BooleanField(default=False, verbose_name=b'Passport')),
                ('which_place_nepal_meet_point', models.BooleanField(default=False, verbose_name=b'Nepal Meet Point')),
                ('which_place_known_location', models.BooleanField(default=False, verbose_name=b'Known Location')),
                ('which_place_sex_industry', models.BooleanField(default=False, verbose_name=b'Sex Industry')),
                ('what_kind_place_persons_house', models.BooleanField(default=False, verbose_name=b"Person's House")),
                ('what_kind_place_bus_station', models.BooleanField(default=False, verbose_name=b'Bus station')),
                ('what_kind_place_train_station', models.BooleanField(default=False, verbose_name=b'Train station')),
                ('what_kind_place_shop', models.BooleanField(default=False, verbose_name=b'Shop')),
                ('what_kind_place_factory', models.BooleanField(default=False, verbose_name=b'Factory')),
                ('what_kind_place_brothel', models.BooleanField(default=False, verbose_name=b'Brothel')),
                ('what_kind_place_hotel', models.BooleanField(default=False, verbose_name=b'Hotel')),
                ('vdc', models.CharField(max_length=255, verbose_name=b'VDC', blank=True)),
                ('district', models.CharField(max_length=255, blank=True)),
                ('signboard', models.CharField(max_length=255, blank=True)),
                ('location_in_town', models.CharField(max_length=255, blank=True)),
                ('phone', models.CharField(max_length=255, verbose_name=b'Phone #', blank=True)),
                ('color', models.CharField(max_length=255, blank=True)),
                ('number_of_levels', models.CharField(max_length=255, verbose_name=b'# of Levels', blank=True)),
                ('compound_wall', models.CharField(max_length=255, blank=True)),
                ('gate_color', models.CharField(max_length=255, blank=True)),
                ('roof_type', models.CharField(max_length=255, blank=True)),
                ('roof_color', models.CharField(max_length=255, blank=True)),
                ('person_in_charge', models.CharField(max_length=255, blank=True)),
                ('nearby_landmarks', models.CharField(max_length=255, blank=True)),
                ('nearby_signboards', models.CharField(max_length=255, blank=True)),
                ('other', models.CharField(max_length=255, blank=True)),
                ('interviewer_believes_trafficked_many_girls', models.BooleanField(default=False, verbose_name=b'Interviewer believes this location is definitely used to traffic many victims')),
                ('interviewer_believes_trafficked_some_girls', models.BooleanField(default=False, verbose_name=b'Interviewer believes this location has been used repeatedly to traffic some victims')),
                ('interviewer_believes_suspect_used_for_trafficking', models.BooleanField(default=False, verbose_name=b'Interviewer suspects this location has been used for trafficking')),
                ('interviewer_believes_not_used_for_trafficking', models.BooleanField(default=False, verbose_name=b'Interviewer does not believe this location is used for trafficking')),
                ('victim_believes_trafficked_many_girls', models.BooleanField(default=False, verbose_name=b'Victim believes this location is definitely used to traffic many victims')),
                ('victim_believes_trafficked_some_girls', models.BooleanField(default=False, verbose_name=b'Victim believes this location has been used repeatedly to traffic some victims')),
                ('victim_believes_suspect_used_for_trafficking', models.BooleanField(default=False, verbose_name=b'Victim suspects this location has been used for trafficking')),
                ('victim_believes_not_used_for_trafficking', models.BooleanField(default=False, verbose_name=b'Victim does not believe this location is used for trafficking')),
                ('associated_with_person', models.NullBooleanField()),
                ('associated_with_person_value', models.IntegerField(null=True, blank=True)),
                ('victim_interview', models.ForeignKey(related_name=b'location_boxes', to='dataentry.VictimInterview')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VictimInterviewPersonBox',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('who_is_this_relationship_boss_of', models.BooleanField(default=False, verbose_name=b'Boss of...')),
                ('who_is_this_relationship_coworker_of', models.BooleanField(default=False, verbose_name=b'Co-worker of...')),
                ('who_is_this_relationship_own_relative_of', models.BooleanField(default=False, verbose_name=b'Own relative of...')),
                ('who_is_this_role_broker', models.BooleanField(default=False, verbose_name=b'Broker')),
                ('who_is_this_role_companion', models.BooleanField(default=False, verbose_name=b'Companion')),
                ('who_is_this_role_india_trafficker', models.BooleanField(default=False, verbose_name=b'India Trafficker')),
                ('who_is_this_role_contact_of_husband', models.BooleanField(default=False, verbose_name=b'Contact of Husband')),
                ('who_is_this_role_known_trafficker', models.BooleanField(default=False, verbose_name=b'Known Trafficker')),
                ('who_is_this_role_manpower', models.BooleanField(default=False, verbose_name=b'Manpower')),
                ('who_is_this_role_passport', models.BooleanField(default=False, verbose_name=b'Passport')),
                ('who_is_this_role_sex_industry', models.BooleanField(default=False, verbose_name=b'Sex Industry')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name', blank=True)),
                ('gender', models.CharField(blank=True, max_length=12, verbose_name=b'Gender', choices=[(b'male', b'Male'), (b'female', b'Female')])),
                ('address_district', models.CharField(max_length=255, verbose_name=b'District', blank=True)),
                ('address_vdc', models.CharField(max_length=255, verbose_name=b'VDC', blank=True)),
                ('address_ward', models.CharField(max_length=255, verbose_name=b'Ward #', blank=True)),
                ('phone', models.CharField(max_length=255, verbose_name=b'Phone #', blank=True)),
                ('age', models.PositiveIntegerField(null=True, verbose_name=b'Age', blank=True)),
                ('height', models.PositiveIntegerField(null=True, verbose_name=b'Height(ft)', blank=True)),
                ('weight', models.PositiveIntegerField(null=True, verbose_name=b'Weight(kg)', blank=True)),
                ('physical_description_kirat', models.BooleanField(default=False, verbose_name=b'Kirat')),
                ('physical_description_sherpa', models.BooleanField(default=False, verbose_name=b'Sherpa')),
                ('physical_description_madeshi', models.BooleanField(default=False, verbose_name=b'Madeshi')),
                ('physical_description_pahadi', models.BooleanField(default=False, verbose_name=b'Pahadi')),
                ('physical_description_newari', models.BooleanField(default=False, verbose_name=b'Newari')),
                ('appearance_other', models.CharField(max_length=255, blank=True)),
                ('occupation_none', models.BooleanField(default=False, verbose_name=b'None')),
                ('occupation_agent', models.BooleanField(default=False, verbose_name=b'Agent (taking girls to India)')),
                ('occupation_business_owner', models.BooleanField(default=False, verbose_name=b'Business owner')),
                ('occupation_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('occupation_wage_labor', models.BooleanField(default=False, verbose_name=b'Wage labor')),
                ('occupation_job_in_india', models.BooleanField(default=False, verbose_name=b'Job in India')),
                ('occupation_job_in_gulf', models.BooleanField(default=False, verbose_name=b'Job in Gulf')),
                ('occupation_farmer', models.BooleanField(default=False, verbose_name=b'Farmer')),
                ('occupation_teacher', models.BooleanField(default=False, verbose_name=b'Teacher')),
                ('occupation_police', models.BooleanField(default=False, verbose_name=b'Police')),
                ('occupation_army', models.BooleanField(default=False, verbose_name=b'Army')),
                ('occupation_guard', models.BooleanField(default=False, verbose_name=b'Guard')),
                ('occupation_cook', models.BooleanField(default=False, verbose_name=b'Cook')),
                ('occupation_driver', models.BooleanField(default=False, verbose_name=b'Driver')),
                ('occupation_other_value', models.CharField(max_length=255, blank=True)),
                ('political_party_congress', models.BooleanField(default=False, verbose_name=b'Congress')),
                ('political_party_maoist', models.BooleanField(default=False, verbose_name=b'Maoist')),
                ('political_party_umn', models.BooleanField(default=False, verbose_name=b'UMN')),
                ('political_party_forum', models.BooleanField(default=False, verbose_name=b'Forum')),
                ('political_party_tarai_madesh', models.BooleanField(default=False, verbose_name=b'Tarai Madesh')),
                ('political_party_shadbawona', models.BooleanField(default=False, verbose_name=b'Shadbawona')),
                ('political_party_rnt', models.BooleanField(default=False, verbose_name=b'Raprapha Nepal Thruhat')),
                ('political_party_njf', models.BooleanField(default=False, verbose_name=b'Nepal Janadikarik Forum')),
                ('political_party_loktantrak', models.BooleanField(default=False, verbose_name=b'Loktantrak Party')),
                ('political_party_dont_know', models.BooleanField(default=False, verbose_name=b"Don't Know")),
                ('political_party_other', models.BooleanField(default=False, verbose_name=b'Other')),
                ('political_party_other_value', models.CharField(max_length=255, blank=True)),
                ('where_spends_time', models.TextField(verbose_name=b'Where does he spend most of his time? How can we get ahlod of or find him?', blank=True)),
                ('interviewer_believes_definitely_trafficked', models.BooleanField(default=False, verbose_name=b'Interviewer believes they have definitely trafficked many girls')),
                ('interviewer_believes_have_trafficked', models.BooleanField(default=False, verbose_name=b'Interviewer believes they have trafficked some girls')),
                ('interviewer_believes_suspects_trafficked', models.BooleanField(default=False, verbose_name=b'Interviewer suspects they are a trafficker')),
                ('interviewer_believes_not_trafficker', models.BooleanField(default=False, verbose_name=b"Interviewer doesn't believe they are a trafficker")),
                ('victim_believes_definitely_trafficked', models.BooleanField(default=False, verbose_name=b'Victim believes they have definitely trafficked many girls')),
                ('victim_believes_have_trafficked', models.BooleanField(default=False, verbose_name=b'Victim believes they have trafficked some girls')),
                ('victim_believes_suspects_trafficked', models.BooleanField(default=False, verbose_name=b'Victim suspects they are a trafficker')),
                ('victim_believes_not_trafficker', models.BooleanField(default=False, verbose_name=b"Victim doesn't believe they are a trafficker")),
                ('associated_with_place', models.NullBooleanField()),
                ('associated_with_place_value', models.IntegerField(null=True, blank=True)),
                ('victim_interview', models.ForeignKey(related_name=b'person_boxes', to='dataentry.VictimInterview')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='interceptee',
            name='interception_record',
            field=models.ForeignKey(related_name=b'interceptees', to='dataentry.InterceptionRecord'),
            preserve_default=True,
        ),
    ]
