# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'InterceptionRecord'
        db.create_table(u'dataentry_interceptionrecord', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('form_entered_by', self.gf('django.db.models.fields.related.ForeignKey')(related_name='irfs_entered', to=orm['accounts.Account'])),
            ('date_form_received', self.gf('django.db.models.fields.DateTimeField')()),
            ('irf_number', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('date_time_of_interception', self.gf('django.db.models.fields.DateTimeField')()),
            ('date_time_entered_into_system', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('date_time_last_updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('number_of_victims', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('number_of_traffickers', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('location', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('staff_name', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('who_in_group_alone', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('who_in_group_husbandwife', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('who_in_group_relative', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('drugged_or_drowsy', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('meeting_someone_across_border', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('seen_in_last_month_in_nepal', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('traveling_with_someone_not_with_her', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('wife_under_18', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('married_in_past_2_weeks', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('married_in_past_2_8_weeks', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('less_than_2_weeks_before_eloping', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('between_2_12_weeks_before_eloping', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('caste_not_same_as_relative', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('caught_in_lie', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('other_red_flag', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('other_red_flag_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('where_going_job', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('where_going_visit', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('where_going_shopping', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('where_going_study', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('where_going_treatment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('doesnt_know_going_to_india', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('running_away_over_18', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('running_away_under_18', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('going_to_gulf_for_work', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_address_in_india', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_company_phone', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_appointment_letter', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('valid_gulf_country_visa', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('passport_with_broker', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('job_too_good_to_be_true', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('not_real_job', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('couldnt_confirm_job', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_bags_long_trip', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('shopping_overnight_stuff_in_bags', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_enrollment_docs', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('doesnt_know_school_name', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_school_phone', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('not_enrolled_in_school', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('reluctant_treatment_info', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_medical_documents', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('fake_medical_documents', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_medical_appointment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('doesnt_know_villiage_details', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('reluctant_villiage_info', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('reluctant_family_info', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('refuses_family_info', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('under_18_cant_contact_family', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('under_18_family_doesnt_know', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('under_18_family_unwilling', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('over_18_family_doesnt_know', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('over_18_family_unwilling', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_brother', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_sister', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_father', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_mother', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_grandparent', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_aunt_uncle', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('talked_to_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('reported_total_red_flags', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('contact_noticed', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_hotel_owner', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_rickshaw_driver', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_taxi_driver', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_bus_driver', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_church_member', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_other_ngo', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_police', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_subcommittee_member', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('contact_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('contact_paid', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('contact_paid_how_much', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('staff_noticed', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('staff_who_noticed', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('noticed_hesitant', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_nervous_or_afraid', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_hurrying', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_drugged_or_drowsy', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_new_clothes', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_dirty_clothes', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_carrying_full_bags', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_village_dress', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_indian_looking', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_typical_village_look', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_looked_like_agent', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_caste_difference', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_young_looking', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_waiting_sitting', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_walking_to_border', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_roaming_around', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_exiting_vehicle', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_heading_to_vehicle', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_in_a_vehicle', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_in_a_rickshaw', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_in_a_cart', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_carrying_a_baby', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_on_the_phone', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_other_sign', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('noticed_other_sign_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('call_subcommittee_chair', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('call_thn_to_cross_check', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('name_come_up_before', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('name_come_up_before_yes_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('scan_and_submit_same_day', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('interception_type', self.gf('django.db.models.fields.CharField')(max_length=30, blank=True)),
            ('trafficker_taken_into_custody', self.gf('django.db.models.fields.CharField')(default='', max_length=255, blank=True)),
            ('how_sure_was_trafficking', self.gf('django.db.models.fields.IntegerField')()),
            ('has_signature', self.gf('django.db.models.fields.BooleanField')()),
            ('scanned_form', self.gf('django.db.models.fields.files.FileField')(default='', max_length=100, blank=True)),
        ))
        db.send_create_signal(u'dataentry', ['InterceptionRecord'])

        # Adding model 'Interceptee'
        db.create_table(u'dataentry_interceptee', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('photo', self.gf('django.db.models.fields.files.ImageField')(default='', max_length=100, blank=True)),
            ('interception_record', self.gf('django.db.models.fields.related.ForeignKey')(related_name='interceptees', to=orm['dataentry.InterceptionRecord'])),
            ('kind', self.gf('django.db.models.fields.CharField')(max_length=4)),
            ('full_name', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=4, blank=True)),
            ('age', self.gf('django.db.models.fields.PositiveIntegerField')(null=True, blank=True)),
            ('district', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('vdc', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('phone_contact', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('relation_to', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
        ))
        db.send_create_signal(u'dataentry', ['Interceptee'])

        # Adding model 'VictimInterview'
        db.create_table(u'dataentry_victiminterview', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('vif_number', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('date_time', self.gf('django.db.models.fields.DateTimeField')()),
            ('date_time_entered_into_system', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('date_time_last_updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('number_of_victims', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('number_of_traffickers', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('location', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('interviewer', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('statement_read_before_beginning', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('permission_to_use_photograph', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_name', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('victim_gender', self.gf('django.db.models.fields.CharField')(max_length=12)),
            ('victim_address_district', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_address_vdc', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_address_ward', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_phone', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_age', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_height', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_weight', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_caste_magar', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_jaisi', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_thakuri', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_brahmin', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_chhetri', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_newar', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_tamang', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_mongolian', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_muslim', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_madeshi_terai', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_dalit', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_caste_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_occupation_unemployed', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_farmer', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_wage_laborer', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_business_owner', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_migrant_worker', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_tailoring', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_housewife', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_animal_husbandry', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_domestic_work', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_shopkeeper', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_hotel', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_factory', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_occupation_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_marital_status_single', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_marital_status_married', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_marital_status_widow', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_marital_status_divorced', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_marital_status_husband_has_other_wives', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_marital_status_abandoned_by_husband', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_own_parents', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_husband', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_husbands_family', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_friends', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_alone', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_other_relative', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_lives_with_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_num_in_family', self.gf('django.db.models.fields.IntegerField')(default=False, blank=True)),
            ('victim_primary_guardian_own_parents', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_primary_guardian_husband', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_primary_guardian_other_relative', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_primary_guardian_non_relative', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_primary_guardian_no_one', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_guardian_address_district', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_guardian_address_vdc', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_guardian_address_ward', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_guardian_phone', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_parents_marital_status_single', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_parents_marital_status_married', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_parents_marital_status_widow', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_parents_marital_status_father_has_other_wives', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_parents_marital_separated', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_parents_marital_divorced', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_none', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_informal', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_primary', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_grade_4_8', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_grade_9_10', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_slc', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_11_12', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_bachelors', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_education_level_masters', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_is_literate', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_education', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_travel_tour', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_shopping', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_eloping', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_arranged_marriage', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_meet_own_family', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_visit_brokers_home', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_medical_treatment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_broker_didnt_say', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_baby_care', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_factory', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_hotel', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_shop', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_laborer', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_brothel', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_household', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('migration_plans_job_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('migration_plans_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('primary_motivation_support_myself', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_support_family', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_personal_debt', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_family_debt', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_love_marriage', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_bad_home_marriage', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_get_education', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_tour_travel', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_didnt_know', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('primary_motivation_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_where_going_india', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_delhi', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_mumbai', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_surat', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_rajastan', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_kolkata', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_pune', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_jaipur', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_bihar', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_india_didnt_know', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_india_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_lebanon', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_dubai', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_malaysia', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_oman', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_saudi_arabia', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_kuwait', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_qatar', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_gulf_didnt_know', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_where_going_gulf_other', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal(u'dataentry', ['VictimInterview'])

        # Adding model 'VictimInterviewPersonBox'
        db.create_table(u'dataentry_victiminterviewpersonbox', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('victim_interview', self.gf('django.db.models.fields.related.ForeignKey')(related_name='person_boxes', to=orm['dataentry.VictimInterview'])),
            ('who_is_this_relationship', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('who_is_this_role', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('gender', self.gf('django.db.models.fields.CharField')(max_length=12, blank=True)),
            ('address_district', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('address_vdc', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('address_ward', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('phone', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('age', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('height', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('weight', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('physical_description', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('appearance_other', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('occupation', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('occupation_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('political_party', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('political_party_other_value', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('where_spends_time', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('interviewer_believes', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('victim_believes', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('associated_with_place', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('associated_with_place_value', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal(u'dataentry', ['VictimInterviewPersonBox'])

        # Adding model 'VictimInterviewLocationBox'
        db.create_table(u'dataentry_victiminterviewlocationbox', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('victim_interview', self.gf('django.db.models.fields.related.ForeignKey')(related_name='location_boxes', to=orm['dataentry.VictimInterview'])),
            ('which_place_india_meetpoint', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('which_place_manpower', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('which_place_transit_hideout', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('which_place_destination', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('which_place_passport', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('which_place_nepal_meet_point', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('which_place_known_location', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('which_place_sex_industry', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('what_kind_place_persons_house', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('what_kind_place_bus_station', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('what_kind_place_train_station', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('what_kind_place_shop', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('what_kind_place_factory', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('what_kind_place_brothel', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('what_kind_place_hotel', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('vdc', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('district', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('signboard', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('location_in_town', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('phone', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('color', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('number_of_levels', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('compound_wall', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('gate_color', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('roof_type', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('roof_color', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('person_in_charge', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('nearby_landmarks', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('nearby_signboards', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('other', self.gf('django.db.models.fields.CharField')(max_length=255, blank=True)),
            ('interviewer_believes_trafficked_many_girls', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('interviewer_believes_trafficked_some_girls', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('interviewer_believes_suspect_used_for_trafficking', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('interviewer_believes_not_used_for_trafficking', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_believes_trafficked_many_girls', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_believes_trafficked_some_girls', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_believes_suspect_used_for_trafficking', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('victim_believes_not_used_for_trafficking', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('associated_with_person', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('associated_with_person_value', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal(u'dataentry', ['VictimInterviewLocationBox'])


    def backwards(self, orm):
        # Deleting model 'InterceptionRecord'
        db.delete_table(u'dataentry_interceptionrecord')

        # Deleting model 'Interceptee'
        db.delete_table(u'dataentry_interceptee')

        # Deleting model 'VictimInterview'
        db.delete_table(u'dataentry_victiminterview')

        # Deleting model 'VictimInterviewPersonBox'
        db.delete_table(u'dataentry_victiminterviewpersonbox')

        # Deleting model 'VictimInterviewLocationBox'
        db.delete_table(u'dataentry_victiminterviewlocationbox')


    models = {
        u'accounts.account': {
            'Meta': {'object_name': 'Account'},
            'activation_key': ('django.db.models.fields.CharField', [], {'default': "'a9CS8O66aFrYbqn3Rl65H2NSzY3zwykXk1fezncG'", 'max_length': '40'}),
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'unique': 'True', 'max_length': '255'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Group']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'permission_accounts_manage': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_irf_add': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_irf_edit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_irf_view': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_vif_add': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_vif_edit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_vif_view': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user_designation': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'accounts'", 'to': u"orm['accounts.DefaultPermissionsSet']"}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Permission']"})
        },
        u'accounts.defaultpermissionsset': {
            'Meta': {'object_name': 'DefaultPermissionsSet'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'permission_accounts_manage': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_irf_add': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_irf_edit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_irf_view': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_vif_add': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_vif_edit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'permission_vif_view': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'dataentry.interceptee': {
            'Meta': {'ordering': "['id']", 'object_name': 'Interceptee'},
            'age': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'district': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'full_name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '4', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'interception_record': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'interceptees'", 'to': u"orm['dataentry.InterceptionRecord']"}),
            'kind': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'phone_contact': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'photo': ('django.db.models.fields.files.ImageField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'relation_to': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'vdc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'})
        },
        u'dataentry.interceptionrecord': {
            'Meta': {'object_name': 'InterceptionRecord'},
            'between_2_12_weeks_before_eloping': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'call_subcommittee_chair': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'call_thn_to_cross_check': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'caste_not_same_as_relative': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'caught_in_lie': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_bus_driver': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_church_member': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_hotel_owner': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_noticed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_other_ngo': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'contact_paid': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'contact_paid_how_much': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'contact_police': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_rickshaw_driver': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_subcommittee_member': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'contact_taxi_driver': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'couldnt_confirm_job': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'date_form_received': ('django.db.models.fields.DateTimeField', [], {}),
            'date_time_entered_into_system': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_time_last_updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'date_time_of_interception': ('django.db.models.fields.DateTimeField', [], {}),
            'doesnt_know_going_to_india': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'doesnt_know_school_name': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'doesnt_know_villiage_details': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'drugged_or_drowsy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'fake_medical_documents': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'form_entered_by': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'irfs_entered'", 'to': u"orm['accounts.Account']"}),
            'going_to_gulf_for_work': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'has_signature': ('django.db.models.fields.BooleanField', [], {}),
            'how_sure_was_trafficking': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'interception_type': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'irf_number': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'job_too_good_to_be_true': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'less_than_2_weeks_before_eloping': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'married_in_past_2_8_weeks': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'married_in_past_2_weeks': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'meeting_someone_across_border': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'name_come_up_before': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'name_come_up_before_yes_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'no_address_in_india': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_appointment_letter': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_bags_long_trip': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_company_phone': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_enrollment_docs': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_medical_appointment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_medical_documents': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_school_phone': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'not_enrolled_in_school': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'not_real_job': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_carrying_a_baby': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_carrying_full_bags': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_caste_difference': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_dirty_clothes': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_drugged_or_drowsy': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_exiting_vehicle': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_heading_to_vehicle': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_hesitant': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_hurrying': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_in_a_cart': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_in_a_rickshaw': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_in_a_vehicle': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_indian_looking': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_looked_like_agent': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_nervous_or_afraid': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_new_clothes': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_on_the_phone': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_other_sign': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_other_sign_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'noticed_roaming_around': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_typical_village_look': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_village_dress': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_waiting_sitting': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_walking_to_border': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'noticed_young_looking': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'number_of_traffickers': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'number_of_victims': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'other_red_flag': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'other_red_flag_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'over_18_family_doesnt_know': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'over_18_family_unwilling': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'passport_with_broker': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'refuses_family_info': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reluctant_family_info': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reluctant_treatment_info': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reluctant_villiage_info': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'reported_total_red_flags': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'running_away_over_18': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'running_away_under_18': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'scan_and_submit_same_day': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'scanned_form': ('django.db.models.fields.files.FileField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'seen_in_last_month_in_nepal': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'shopping_overnight_stuff_in_bags': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'staff_name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'staff_noticed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'staff_who_noticed': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'talked_to_aunt_uncle': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'talked_to_brother': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'talked_to_father': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'talked_to_grandparent': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'talked_to_mother': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'talked_to_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'talked_to_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'talked_to_sister': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'trafficker_taken_into_custody': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255', 'blank': 'True'}),
            'traveling_with_someone_not_with_her': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'under_18_cant_contact_family': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'under_18_family_doesnt_know': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'under_18_family_unwilling': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'valid_gulf_country_visa': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'where_going_job': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'where_going_shopping': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'where_going_study': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'where_going_treatment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'where_going_visit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'who_in_group_alone': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'who_in_group_husbandwife': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'who_in_group_relative': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'wife_under_18': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'dataentry.victiminterview': {
            'Meta': {'object_name': 'VictimInterview'},
            'date_time': ('django.db.models.fields.DateTimeField', [], {}),
            'date_time_entered_into_system': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'date_time_last_updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'interviewer': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'migration_plans_arranged_marriage': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_education': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_eloping': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_baby_care': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_broker_didnt_say': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_brothel': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_factory': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_hotel': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_household': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_laborer': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_job_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'migration_plans_job_shop': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_medical_treatment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_meet_own_family': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'migration_plans_shopping': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_travel_tour': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'migration_plans_visit_brokers_home': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'number_of_traffickers': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'number_of_victims': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'permission_to_use_photograph': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_bad_home_marriage': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_didnt_know': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_family_debt': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_get_education': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_love_marriage': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'primary_motivation_personal_debt': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_support_family': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_support_myself': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'primary_motivation_tour_travel': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'statement_read_before_beginning': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_address_district': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_address_vdc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_address_ward': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_age': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_caste_brahmin': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_chhetri': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_dalit': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_jaisi': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_madeshi_terai': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_magar': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_mongolian': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_muslim': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_newar': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_caste_tamang': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_caste_thakuri': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_11_12': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_bachelors': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_grade_4_8': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_grade_9_10': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_informal': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_masters': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_none': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_primary': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_education_level_slc': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_gender': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'victim_guardian_address_district': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_guardian_address_vdc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_guardian_address_ward': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_guardian_phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_height': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_is_literate': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_lives_with_alone': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_lives_with_friends': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_lives_with_husband': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_lives_with_husbands_family': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_lives_with_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_lives_with_other_relative': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_lives_with_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_lives_with_own_parents': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_marital_status_abandoned_by_husband': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_marital_status_divorced': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_marital_status_husband_has_other_wives': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_marital_status_married': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_marital_status_single': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_marital_status_widow': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'victim_num_in_family': ('django.db.models.fields.IntegerField', [], {'default': 'False', 'blank': 'True'}),
            'victim_occupation_animal_husbandry': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_business_owner': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_domestic_work': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_factory': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_farmer': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_hotel': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_housewife': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_migrant_worker': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_occupation_shopkeeper': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_tailoring': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_unemployed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_occupation_wage_laborer': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_parents_marital_divorced': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_parents_marital_separated': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_parents_marital_status_father_has_other_wives': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_parents_marital_status_married': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_parents_marital_status_single': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_parents_marital_status_widow': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_primary_guardian_husband': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_primary_guardian_no_one': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_primary_guardian_non_relative': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_primary_guardian_other_relative': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_primary_guardian_own_parents': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_weight': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_where_going_bihar': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_delhi': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_dubai': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_gulf_didnt_know': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_gulf_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_india': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_india_didnt_know': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_india_other': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_jaipur': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_kolkata': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_kuwait': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_lebanon': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_malaysia': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_mumbai': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_oman': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_pune': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_qatar': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_rajastan': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_saudi_arabia': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_where_going_surat': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'vif_number': ('django.db.models.fields.CharField', [], {'max_length': '20'})
        },
        u'dataentry.victiminterviewlocationbox': {
            'Meta': {'object_name': 'VictimInterviewLocationBox'},
            'associated_with_person': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'associated_with_person_value': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'color': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'compound_wall': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'district': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'gate_color': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'interviewer_believes_not_used_for_trafficking': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'interviewer_believes_suspect_used_for_trafficking': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'interviewer_believes_trafficked_many_girls': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'interviewer_believes_trafficked_some_girls': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'location_in_town': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'nearby_landmarks': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'nearby_signboards': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'number_of_levels': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'other': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'person_in_charge': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'roof_color': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'roof_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'signboard': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'vdc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_believes_not_used_for_trafficking': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_believes_suspect_used_for_trafficking': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_believes_trafficked_many_girls': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_believes_trafficked_some_girls': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'victim_interview': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'location_boxes'", 'to': u"orm['dataentry.VictimInterview']"}),
            'what_kind_place_brothel': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'what_kind_place_bus_station': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'what_kind_place_factory': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'what_kind_place_hotel': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'what_kind_place_persons_house': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'what_kind_place_shop': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'what_kind_place_train_station': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_destination': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_india_meetpoint': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_known_location': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_manpower': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_nepal_meet_point': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_passport': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_sex_industry': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'which_place_transit_hideout': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        u'dataentry.victiminterviewpersonbox': {
            'Meta': {'object_name': 'VictimInterviewPersonBox'},
            'address_district': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'address_vdc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'address_ward': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'age': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'appearance_other': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'associated_with_place': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'associated_with_place_value': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'max_length': '12', 'blank': 'True'}),
            'height': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'interviewer_believes': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'occupation': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'occupation_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'physical_description': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'political_party': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'political_party_other_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_believes': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'victim_interview': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'person_boxes'", 'to': u"orm['dataentry.VictimInterview']"}),
            'weight': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'where_spends_time': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'who_is_this_relationship': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'who_is_this_role': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'})
        }
    }

    complete_apps = ['dataentry']