# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160310_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='permission_receive_email',
        ),
        migrations.RemoveField(
            model_name='defaultpermissionsset',
            name='permission_receive_email',
        ),
        migrations.AddField(
            model_name='account',
            name='permission_receive_investigation_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='permission_receive_legal_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_receive_investigation_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_receive_legal_alert',
            field=models.BooleanField(default=False),
        ),
    ]
