# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20161107_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='permission_budget_manage',
        ),
        migrations.RemoveField(
            model_name='defaultpermissionsset',
            name='permission_budget_manage',
        ),
        migrations.AddField(
            model_name='account',
            name='permission_budget_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='permission_budget_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='permission_budget_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='permission_budget_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_budget_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_budget_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_budget_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_budget_view',
            field=models.BooleanField(default=False),
        ),
    ]
