# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-08 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170107_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permission_can_receive_mdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_can_receive_mdf',
            field=models.BooleanField(default=False),
        ),
    ]
