# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170608_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permission_person_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultpermissionsset',
            name='permission_person_match',
            field=models.BooleanField(default=False),
        ),
    ]
