# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_expiringtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country_name',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
