from dataentry.specification.form_spec import FormSpec, FormsOfTypeSpec, CategorySpec, BaseQuestionSpec, StorageSpec

irf_common_storage: StorageSpec = {
    'tag': 'IrfCommon',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IrfCommon',
    'parent_storage': None,
    'parent_field': None
}
interceptee_storage: StorageSpec = {
    'tag': 'IntercepteeCommon',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IntercepteeCommon',
    'parent_storage': irf_common_storage,
    'parent_field': 'interception_record'
}
attachment_storage: StorageSpec = {
    'tag': 'IrfAttachmentCommon',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IrfAttachmentCommon',
    'parent_storage': irf_common_storage,
    'parent_field': 'interception_record'
}
verification_storage: StorageSpec = {
    'tag': 'IrfVerification',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IrfVerification',
    'parent_storage': irf_common_storage,
    'parent_field': 'interception_record'
}

base_question: dict[str, BaseQuestionSpec] = {
    'irfNumber': {
        'tag': 'irfNumber',
        'answer_type': 'String',
        'field_name': 'irf_number',
        'export_name': 'IRF #',
        'params': None,
        'export_params': None,
    },
    'irfNumberOfPvs': {
        'tag': 'irfNumberOfPvs',
        'answer_type': 'Integer',
        'field_name': 'number_of_victims',
        'export_name': '# of PVs',
        'params': None,
        'export_params': None,
    },
    'irfLocation': {
        'tag': 'irfLocation',
        'answer_type': 'String',
        'field_name': 'location',
        'export_name': 'Location',
        'params': None,
        'export_params': None,
    },
    'irfDateOfIntercept': {
        'tag': 'irfDateOfIntercept',
        'answer_type': 'Date',
        'field_name': 'date_of_interception',
        'export_name': 'Date of Interception',
        'params': None,
        'export_params': None,
    },
    'irfTimeOfIntercept': {
        'tag': 'irfTimeOfIntercept',
        'answer_type': 'String',
        'field_name': 'time_of_interception',
        'export_name': 'Time of Interception',
        'params': None,
        'export_params': None,
    },
    'irfNumberOfSuspects': {
        'tag': 'irfNumberOfSuspects',
        'answer_type': 'Integer',
        'field_name': 'number_of_traffickers',
        'export_name': '# of Suspects',
        'params': None,
        'export_params': None,
    },
    'irfStaffName': {
        'tag': 'irfStaffName',
        'answer_type': 'String',
        'field_name': 'staff_name',
        'export_name': 'Staff Name',
        'params': None,
        'export_params': None,
    },

    'irfAge0to5': {
        'tag': 'irfAge0to5',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_age_0_5',
        'export_name': 'Age 0-5',
        'params': None,
        'export_params': None,
    },
    'irfAge6to9': {
        'tag': 'irfAge6to9',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_age_6_9',
        'export_name': 'Age 6-9',
        'params': None,
        'export_params': None,
    },
    'irfAge10to14': {
        'tag': 'irfAge10to14',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_age_10_14',
        'export_name': 'Age 10-14',
        'params': None,
        'export_params': None,
    },
    'irfAge15to17': {
        'tag': 'irfAge15to17',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_age_15_17',
        'export_name': 'Age 15-17',
        'params': None,
        'export_params': None,
    },
    'irfAge18to22': {
        'tag': 'irfAge18to22',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_age_18_22',
        'export_name': 'Age 18-22',
        'params': None,
        'export_params': None,
    },
    'irfAge23to29': {
        'tag': 'irfAge23to29',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_age_23_29',
        'export_name': 'Age 23-29',
        'params': None,
        'export_params': None,
    },
    'irfAge30to35': {
        'tag': 'irfAge30to35',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_age_30_35',
        'export_name': 'Age 30-35',
        'params': None,
        'export_params': None,
    },
    'irfFemale': {
        'tag': 'irfFemale',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_female',
        'export_name': 'Female',
        'params': None,
        'export_params': None,
    },
    'irfMinorNoGuardian': {
        'tag': 'irfMinorNoGuardian',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_minor_no_guardian',
        'export_name': 'Minor without guardian',
        'params': None,
        'export_params': None,
    },
    'irfSeductive': {
        'tag': 'irfSeductive',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_seductive',
        'export_name': 'Seductive appearance',
        'params': None,
        'export_params': None,
    },

    'irfUnemployed': {
        'tag': 'irfUnemployed',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_unemployed',
        'export_name': 'Unemployed adult',
        'params': None,
        'export_params': None,
    },
    'irfInsufficientResources': {
        'tag': 'irfInsufficientResources',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_insufficient_resources',
        'export_name': 'Insufficient resources to get home',
        'params': None,
        'export_params': None,
    },
    'irfPoorArea': {
        'tag': 'irfPoorArea',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_poor_area',
        'export_name': 'Moving from poor country or area',
        'params': None,
        'export_params': None,
    },
    'irfNoPhone': {
        'tag': 'irfNoPhone',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerable_no_phone',
        'export_name': 'No phone',
        'params': None,
        'export_params': None,
    },

    'irfVulnerableTotal': {
        'tag': 'irfVulnerableTotal',
        'answer_type': 'Integer',
        'field_name': 'vulnerable_total',
        'export_name': 'No phone',
        'params': None,
        'Vulnerability total points': None,
    },
}

category: dict[str, CategorySpec] = {
    'irfTopCategory': {
        'tag': 'irfTopBox',
        'category_type': 'grid',
        'description': 'IRF Top Box',
        'storage': None,
    },
    'irfVulnerableCategory': {
        'tag': 'irfVulnerableCategory',
        'category_type': 'grid',
        'description': 'IRF Vulnerable Tab',
        'storage': None,
    },
    'irfSituationCategory': {
        'tag': 'irfSituationCategory',
        'category_type': 'grid',
        'description': 'IRF Situation Tab',
        'storage': None,
    },
    'irfControlCategory': {
        'tag': 'irfControlCategory',
        'category_type': 'grid',
        'description': 'IRF Control Tab',
        'storage': None,
    },
    'irfPeopleCategory': {
        'tag': 'irfPeopleCategory',
        'category_type': 'card',
        'description': 'IRF People Tab',
        'storage': interceptee_storage,
    },
    'irfProcedureCategory': {
        'tag': 'irfProcedureCategory',
        'category_type': 'grid',
        'description': 'IRF Staff Procedure Tab',
        'storage': None,
    },
    'irfAttachmentCategory': {
        'tag': 'irfAttachmentCategory',
        'category_type': 'card',
        'description': 'IRF Attachments Tab',
        'storage': attachment_storage,
    },
    'irfVerificationCategory': {
        'tag': 'irfVerificationCategory',
        'category_type': 'card',
        'description': 'IRF Verification Tab',
        'storage': verification_storage,
    },
}

irf_core: FormSpec = {
    'name': 'irfCore2024_08',
    'storage': irf_common_storage,
    'sections': [
        {
            'name': 'Top',
            'category': category['irfTopCategory'],
            'subsections': [
                {
                    'title': 'Top',
                    'key': 'top',
                    'side': 'full',
                    'questions': [
                        {
                            'base_question': base_question['irfNumber'],
                            'label': 'IRF #',
                            'entry_type': 'text',
                            'span': 6,
                            'total': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNumberOfPvs'],
                            'label': '# of PVs',
                            'entry_type': 'text',
                            'span': 6,
                            'total': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfLocation'],
                            'label': 'Location',
                            'entry_type': 'text',
                            'span': 6,
                            'total': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfDateOfIntercept'],
                            'label': 'Date',
                            'entry_type': 'text',
                            'span': 6,
                            'total': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfTimeOfIntercept'],
                            'label': 'Time',
                            'entry_type': 'text',
                            'span': 6,
                            'total': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNumberOfSuspects'],
                            'label': '# of Suspects',
                            'entry_type': 'text',
                            'span': 6,
                            'total': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfStaffName'],
                            'label': 'Staff Name',
                            'entry_type': 'text',
                            'span': 6,
                            'total': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                    ],
                },
            ]
        },
        {
            'name': 'Vulnerability',
            'category': category['irfVulnerableCategory'],
            'subsections': [
                {
                    'title': 'Demographics & Appearance',
                    'key': 'demo',
                    'side': 'left',
                    'questions': [
                        {
                            'base_question': base_question['irfAge0to5'],
                            'label': 'Age 0-5',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 7,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge6to9'],
                            'label': 'Age 6-9',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 6,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge10to14'],
                            'label': 'Age 10-14',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 5,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge15to17'],
                            'label': 'Age 15-17',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 4,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge18to22'],
                            'label': 'Age 18-22',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 5,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge23to29'],
                            'label': 'Age 23-29',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge30to35'],
                            'label': 'Age 30-35',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 1,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFemale'],
                            'label': 'Female',
                            'entry_type': 'checkbox',
                            'span': 6,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfMinorNoGuardian'],
                            'label': 'Minor without guardian',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 5,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfSeductive'],
                            'label': 'Seductive appearance',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 4,
                            'options': None,
                            'other_option': None,
                        },
                    ]
                },
                {
                    'title': 'Poverty',
                    'key': 'poverty',
                    'side': 'center',
                    'questions': [
                        {
                            'base_question': base_question['irfUnemployed'],
                            'label': 'Unemployed adult',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfInsufficientResources'],
                            'label': 'Insufficient resources to get home',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfPoorArea'],
                            'label': 'Moving from poor country or area',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNoPhone'],
                            'label': 'No Phone',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total': base_question['irfVulnerableTotal'],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                    ]
                }
            ]
        }
    ],
    'validations': [],
    'export': None
}

irf_202408: FormsOfTypeSpec = {
    'form_type': 'IRF',
    'version': '2024.8',
    'form_specs': [irf_core],
}
