from dataentry.specification.form_spec import FormSpec, FormsOfTypeSpec, CategorySpec, BaseQuestionSpec, StorageSpec

irf_common_storage: StorageSpec = {
    'tag': 'IrfCommon',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IrfCommon',
    'parent_storage': None,
    'parent_field': None
}
interceptee_storage: StorageSpec = {
    'tag': 'IntercepteeCommon',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IntercepteeCommon',
    'parent_storage': irf_common_storage,
    'parent_field': 'interception_record'
}
attachment_storage: StorageSpec = {
    'tag': 'IrfAttachmentCommon',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IrfAttachmentCommon',
    'parent_storage': irf_common_storage,
    'parent_field': 'interception_record'
}
verification_storage: StorageSpec = {
    'tag': 'IrfVerification',
    'module_name': 'dataentry.models.irf_common',
    'model_name': 'IrfVerification',
    'parent_storage': irf_common_storage,
    'parent_field': 'interception_record'
}

base_question: dict[str, BaseQuestionSpec] = {
    'irfNumber': {
        'tag': 'irfNumber',
        'answer_type': 'String',
        'field_name': 'irf_number',
        'export_name': 'IRF #',
        'params': None,
        'export_params': None,
    },
    'irfNumberOfPvs': {
        'tag': 'irfNumberOfPvs',
        'answer_type': 'Integer',
        'field_name': 'number_of_victims',
        'export_name': '# of PVs',
        'params': None,
        'export_params': None,
    },
    'irfLocation': {
        'tag': 'irfLocation',
        'answer_type': 'String',
        'field_name': 'location',
        'export_name': 'Location',
        'params': None,
        'export_params': None,
    },
    'irfDateOfIntercept': {
        'tag': 'irfDateOfIntercept',
        'answer_type': 'Date',
        'field_name': 'date_of_interception',
        'export_name': 'Date of Interception',
        'params': None,
        'export_params': None,
    },
    'irfTimeOfIntercept': {
        'tag': 'irfTimeOfIntercept',
        'answer_type': 'String',
        'field_name': 'time_of_interception',
        'export_name': 'Time of Interception',
        'params': None,
        'export_params': None,
    },
    'irfNumberOfSuspects': {
        'tag': 'irfNumberOfSuspects',
        'answer_type': 'Integer',
        'field_name': 'number_of_traffickers',
        'export_name': '# of Suspects',
        'params': None,
        'export_params': None,
    },
    'irfStaffName': {
        'tag': 'irfStaffName',
        'answer_type': 'String',
        'field_name': 'staff_name',
        'export_name': 'Staff Name',
        'params': None,
        'export_params': None,
    },

    'irfAge0to5': {
        'tag': 'irfAge0to5',
        'answer_type': 'Checkbox',
        'field_name': 'age_0_5',
        'export_name': 'Age 0-5',
        'params': None,
        'export_params': None,
    },
    'irfAge6to9': {
        'tag': 'irfAge6to9',
        'answer_type': 'Checkbox',
        'field_name': 'age_6_9',
        'export_name': 'Age 6-9',
        'params': None,
        'export_params': None,
    },
    'irfAge10to14': {
        'tag': 'irfAge10to14',
        'answer_type': 'Checkbox',
        'field_name': 'age_10_14',
        'export_name': 'Age 10-14',
        'params': None,
        'export_params': None,
    },
    'irfAge15to17': {
        'tag': 'irfAge15to17',
        'answer_type': 'Checkbox',
        'field_name': 'age_15_17',
        'export_name': 'Age 15-17',
        'params': None,
        'export_params': None,
    },
    'irfAge18to22': {
        'tag': 'irfAge18to22',
        'answer_type': 'Checkbox',
        'field_name': 'age_18_22',
        'export_name': 'Age 18-22',
        'params': None,
        'export_params': None,
    },
    'irfAge23to29': {
        'tag': 'irfAge23to29',
        'answer_type': 'Checkbox',
        'field_name': 'age_23_29',
        'export_name': 'Age 23-29',
        'params': None,
        'export_params': None,
    },
    'irfAge30to35': {
        'tag': 'irfAge30to35',
        'answer_type': 'Checkbox',
        'field_name': 'age_30_35',
        'export_name': 'Age 30-35',
        'params': None,
        'export_params': None,
    },
    'irfFemale': {
        'tag': 'irfFemale',
        'answer_type': 'Checkbox',
        'field_name': 'female',
        'export_name': 'Female',
        'params': None,
        'export_params': None,
    },
    'irfMinorNoGuardian': {
        'tag': 'irfMinorNoGuardian',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerability_minor_without_guardian',
        'export_name': 'Minor without guardian',
        'params': None,
        'export_params': None,
    },
    'irfSeductive': {
        'tag': 'irfSeductive',
        'answer_type': 'Checkbox',
        'field_name': 'seductive_appearance',
        'export_name': 'Seductive appearance',
        'params': None,
        'export_params': None,
    },

    'irfUnemployed': {
        'tag': 'irfUnemployed',
        'answer_type': 'Checkbox',
        'field_name': 'adult_unemployed',
        'export_name': 'Unemployed adult',
        'params': None,
        'export_params': None,
    },
    'irfInsufficientResources': {
        'tag': 'irfInsufficientResources',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerability_insufficient_resource',
        'export_name': 'Insufficient resources to get home',
        'params': None,
        'export_params': None,
    },
    'irfPoorArea': {
        'tag': 'irfPoorArea',
        'answer_type': 'Checkbox',
        'field_name': 'moving_from_poor_area',
        'export_name': 'Moving from poor country or area',
        'params': None,
        'export_params': None,
    },
    'irfNoPhone': {
        'tag': 'irfNoPhone',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerability_no_mobile_phone',
        'export_name': 'No phone',
        'params': None,
        'export_params': None,
    },
    'irfRecentlyEnslaved': {
        'tag': 'irfRecentlyEnslaved',
        'answer_type': 'Checkbox',
        'field_name': 'recently_enslaved',
        'export_name': 'Returning from being enslaved',
        'params': None,
        'export_params': None,
    },
    'irfFirstTimeTravelingAbroad': {
        'tag': 'irfReturningFromBeingEnslaved',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerability_first_time_traveling_abroad',
        'export_name': 'First time traveling abroad',
        'params': None,
        'export_params': None,
    },
    'irfRunaway': {
        'tag': 'irfRunaway',
        'answer_type': 'Checkbox',
        'field_name': 'runaway',
        'export_name': 'Runaway',
        'params': None,
        'export_params': None,
    },
    'irfFirstTimeTravelingToCity': {
        'tag': 'irfFirstTimeTravelingToCity',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerability_first_time_traveling_to_city',
        'export_name': 'First time traveling to city from rural area',
        'params': None,
        'export_params': None,
    },
    'irfTravelingWithSomeoneRecentlyMet': {
        'tag': 'irfTravelingWithSomeoneRecentlyMet',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerability_travel_met_recently',
        'export_name': 'Is or was traveling with someone recently met',
        'params': None,
        'export_params': None,
    },
    'irfStrandedAbandoned': {
        'tag': 'irfStrandedAbandoned',
        'answer_type': 'Checkbox',
        'field_name': 'vulnerability_stranded_or_abandoned',
        'export_name': 'Lured somewhere and now stranded / abandoned',
        'params': None,
        'export_params': None,
    },
    'irfNotInSchool': {
        'tag': 'irfNotInSchool',
        'answer_type': 'Checkbox',
        'field_name': 'not_in_school',
        'export_name': 'School-age minor not enrolled in school',
        'params': None,
        'export_params': None,
    },

    'irfMonitorVulnerableTotal': {
        'tag': 'irfMonitorVulnerableTotal',
        'answer_type': 'Integer',
        'field_name': 'vulnerable_monitor_total',
        'export_name': 'Vulnerable Monitor Total',
        'params': None,
        'export_params': None,
    },

    'irfComputedVulnerableTotal': {
        'tag': 'irfComputedVulnerableTotal',
        'answer_type': 'Integer',
        'field_name': 'vulnerable_computed_total',
        'export_name': 'Vulnerable Computed Total',
        'params': None,
        'export_params': None,
    },
    'irfMonitorTotal': {
        'tag': 'irfMonitorTotal',
        'answer_type': 'Integer',
        'field_name': 'overall_monitor_total',
        'export_name': 'Overall Monitor Total',
        'params': None,
        'export_params': None,
    },
    'irfComputedTotal': {
        'tag': 'irfComputedTotal',
        'answer_type': 'Integer',
        'field_name': 'overall_computed_total',
        'export_name': 'Overall Computed Total',
        'params': None,
        'export_params': None,
    },

    # Interceptee Card
    'irfInterceptPerson': {
        'tag': 'irfInterceptPerson',
        'answer_type': 'Person',
        'field_name': 'person',
        'export_name': '',
        'params': '{"name": "private", "phone": "private", "address2": "private", "birthdate": "private", "identifiers": "private", "nationality": "private", "subdirectory": "interceptee_photos/"}',
        'export_params': None,
    },
    'irfNotPresent': {
        'tag': 'irfNotPresent',
        'answer_type': 'String',
        'field_name': 'not_physically_present',
        'export_name': 'Not Physically Present',
        'params': None,
        'export_params': None,
    },
    'irfFamilyContacted': {
        'tag': 'irfFamilyContacted',
        'answer_type': 'String',
        'field_name': 'family_contacted',
        'export_name': 'Family Contacted',
        'params': None,
        'export_params': None,
    },
    'irfFamilyContactedDetail': {
        'tag': 'irfFamilyContactedDetail',
        'answer_type': 'String',
        'field_name': 'family_contacted_detail',
        'export_name': 'Family Contacted Detail',
        'params': None,
        'export_params': None,
    },

    # Attachment Card
    'irfAttachmentNumber': {
        'tag': 'irfAttachmentNumber',
        'answer_type': 'Integer',
        'field_name': 'attachment_number',
        'export_name': 'Attachment Number',
        'params': None,
        'export_params': None,
    },
    'irfAttachmentDescription': {
        'tag': 'irfAttachmentDescription',
        'answer_type': 'String',
        'field_name': 'description',
        'export_name': 'Attachment Description',
        'params': None,
        'export_params': None,
    },
    'irfAttachmentFile': {
        'tag': 'irfAttachmentFile',
        'answer_type': 'Image',
        'field_name': 'attachment',
        'export_name': 'Attachment File',
        'params': None,
        'export_params': None,
    },
    'irfAttachmentPrivate': {
        'tag': 'irfAttachmentPrivate',
        'answer_type': 'Checkbox',
        'field_name': 'private_card',
        'export_name': 'Attachment Private',
        'params': None,
        'export_params': None,
    },
    'irfAttachmentOption': {
        'tag': 'irfAttachmentOption',
        'answer_type': 'String',
        'field_name': 'option',
        'export_name': 'Attachment Option',
        'params': None,
        'export_params': None,
    },

    # Verification Card
    'irfVerificationType': {
        'tag': 'irfVerificationType',
        'answer_type': 'Integer',
        'field_name': 'verification_type',
        'export_name': 'Verification Type',
        'params': None,
        'export_params': None,
    },
    'irfFollowUpCall': {
        'tag': 'irfFollowUpCall',
        'answer_type': 'String',
        'field_name': 'followup_call',
        'export_name': 'Followup Call',
        'params': None,
        'export_params': None,
    },
    'irfFollowUpDetails': {
        'tag': 'irfFollowUpDetails',
        'answer_type': 'String',
        'field_name': 'followup_details',
        'export_name': 'Followup Details',
        'params': None,
        'export_params': None,
    },
    'irfVerificationEvidenceCategorization': {
        'tag': 'irfVerificationEvidenceCategorization',
        'answer_type': 'String',
        'field_name': 'evidence_categorization',
        'export_name': 'Evidence Categorization',
        'params': None,
        'export_params': None,
    },
    'irfVerificationReason': {
        'tag': 'irfVerificationReason',
        'answer_type': 'String',
        'field_name': 'reason',
        'export_name': 'Verification Reason',
        'params': None,
        'export_params': None,
    },
    'irfVerificationDate': {
        'tag': 'irfVerificationDate',
        'answer_type': 'Date',
        'field_name': 'verified_date',
        'export_name': 'Verification Date',
        'params': None,
        'export_params': None,
    },
    'irfVerifier': {
        'tag': 'irfVerifier',
        'answer_type': 'Integer',
        'field_name': 'verifier_id',
        'export_name': 'Verifier',
        'params': None,
        'export_params': None,
    },
}

category: dict[str, CategorySpec] = {
    'irfTopCategory': {
        'tag': 'irfTopBox',
        'category_type': 'grid',
        'description': 'IRF Top Box',
        'storage': None,
    },
    'irfVulnerableCategory': {
        'tag': 'irfVulnerableCategory',
        'category_type': 'grid',
        'description': 'IRF Vulnerable Tab',
        'storage': None,
    },
    'irfSituationCategory': {
        'tag': 'irfSituationCategory',
        'category_type': 'grid',
        'description': 'IRF Situation Tab',
        'storage': None,
    },
    'irfControlCategory': {
        'tag': 'irfControlCategory',
        'category_type': 'grid',
        'description': 'IRF Control Tab',
        'storage': None,
    },
    'irfPeopleCategory': {
        'tag': 'irfPeopleCategory',
        'category_type': 'card',
        'description': 'IRF People Tab',
        'storage': interceptee_storage,
    },
    'irfProcedureCategory': {
        'tag': 'irfProcedureCategory',
        'category_type': 'grid',
        'description': 'IRF Staff Procedure Tab',
        'storage': None,
    },
    'irfAttachmentCategory': {
        'tag': 'irfAttachmentCategory',
        'category_type': 'card',
        'description': 'IRF Attachments Tab',
        'storage': attachment_storage,
    },
    'irfVerificationCategory': {
        'tag': 'irfVerificationCategory',
        'category_type': 'card',
        'description': 'IRF Verification Tab',
        'storage': verification_storage,
    },
}

irf_core: FormSpec = {
    'name': 'irfCore2024_08',
    'storage': irf_common_storage,
    'sections': [
        {
            'name': 'Top',
            'category': category['irfTopCategory'],
            'subsections': [
                {
                    'title': 'Top',
                    'key': 'top',
                    'side': 'full',
                    'questions': [
                        {
                            'base_question': base_question['irfNumber'],
                            'label': 'IRF #',
                            'entry_type': 'text',
                            'span': 6,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNumberOfPvs'],
                            'label': '# of PVs',
                            'entry_type': 'number',
                            'span': 6,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfLocation'],
                            'label': 'Location',
                            'entry_type': 'text',
                            'span': 6,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfDateOfIntercept'],
                            'label': 'Date',
                            'entry_type': 'text',
                            'span': 6,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfTimeOfIntercept'],
                            'label': 'Time',
                            'entry_type': 'text',
                            'span': 6,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNumberOfSuspects'],
                            'label': '# of Suspects',
                            'entry_type': 'number',
                            'span': 6,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfStaffName'],
                            'label': 'Staff Name',
                            'entry_type': 'text',
                            'span': 6,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                    ],
                },
            ]
        },
        {
            'name': 'Vulnerability',
            'category': category['irfVulnerableCategory'],
            'subsections': [
                {
                    'title': 'Demographics & Appearance',
                    'key': 'demo',
                    'side': 'left',
                    'questions': [
                        {
                            'base_question': base_question['irfAge0to5'],
                            'label': 'Age 0-5',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 7,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge6to9'],
                            'label': 'Age 6-9',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 6,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge10to14'],
                            'label': 'Age 10-14',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 5,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge15to17'],
                            'label': 'Age 15-17',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 4,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge18to22'],
                            'label': 'Age 18-22',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 5,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge23to29'],
                            'label': 'Age 23-29',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAge30to35'],
                            'label': 'Age 30-35',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 1,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFemale'],
                            'label': 'Female',
                            'entry_type': 'checkbox',
                            'span': 12,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfMinorNoGuardian'],
                            'label': 'Minor without guardian',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 5,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfSeductive'],
                            'label': 'Seductive appearance',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 4,
                            'options': None,
                            'other_option': None,
                        },
                    ]
                },
                {
                    'title': 'Poverty',
                    'key': 'poverty',
                    'side': 'center',
                    'questions': [
                        {
                            'base_question': base_question['irfUnemployed'],
                            'label': 'Unemployed adult',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfInsufficientResources'],
                            'label': 'Insufficient resources to get home',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfPoorArea'],
                            'label': 'Moving from poor country or area',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNoPhone'],
                            'label': 'No Phone',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                    ]
                },
                {
                    'title': 'Situation',
                    'key': 'situation',
                    'side': 'right',
                    'questions': [
                        {
                            'base_question': base_question['irfRecentlyEnslaved'],
                            'label': 'Returning from being enslaved',
                            'entry_type': 'checkbox',
                            'span': 16,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 2,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfRunaway'],
                            'label': 'Runaway',
                            'entry_type': 'checkbox',
                            'span': 8,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 2,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFirstTimeTravelingAbroad'],
                            'label': 'First time traveling abroad',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 2,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFirstTimeTravelingToCity'],
                            'label': 'First time traveling to city from rural area',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 2,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfTravelingWithSomeoneRecentlyMet'],
                            'label': 'Is or was traveling with someone recently met',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfStrandedAbandoned'],
                            'label': 'Lured somewhere and now stranded / abandoned',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNotInSchool'],
                            'label': 'School-age minor not enrolled in school',
                            'entry_type': 'checkbox',
                            'span': 24,
                            'total_question': [base_question['irfComputedVulnerableTotal'],
                                               base_question['irfComputedTotal']],
                            'points': 3,
                            'options': None,
                            'other_option': None,
                        },
                    ]
                },
                {
                    'title': '',
                    'key': 'total',
                    'side': 'center',
                    'questions': [
                        {
                            'base_question': base_question['irfMonitorVulnerableTotal'],
                            'label': 'TOTAL VULNERABILITY POINTS',
                            'entry_type': 'number',
                            'span': 24,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfComputedVulnerableTotal'],
                            'label': 'COMPUTED TOTAL VULNERABILITY POINTS',
                            'entry_type': 'sum',
                            'span': 24,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                    ]
                }
            ]
        },

        {
            'name': 'People',
            'category': category['irfPeopleCategory'],
            'subsections': [
                {
                    'title': '',
                    'key': 'people',
                    'side': 'full',
                    'questions': [
                        {
                            'base_question': base_question['irfInterceptPerson'],
                            'label': '',
                            'entry_type': 'person',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfNotPresent'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFamilyContacted'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFamilyContactedDetail'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                    ],
                },
            ]
        },

        {
            'name': 'Attachments',
            'category': category['irfAttachmentCategory'],
            'subsections': [
                {
                    'title': '',
                    'key': 'attachment',
                    'side': 'full',
                    'questions': [
                        {
                            'base_question': base_question['irfAttachmentNumber'],
                            'label': '',
                            'entry_type': 'number',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAttachmentDescription'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAttachmentFile'],
                            'label': '',
                            'entry_type': 'file',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAttachmentPrivate'],
                            'label': '',
                            'entry_type': 'checkbox',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfAttachmentOption'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                    ],
                },
            ]
        },

        {
            'name': 'Verification',
            'category': category['irfVerificationCategory'],
            'subsections': [
                {
                    'title': '',
                    'key': 'verification',
                    'side': 'full',
                    'questions': [
                        {
                            'base_question': base_question['irfVerificationType'],
                            'label': '',
                            'entry_type': 'number',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFollowUpCall'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfFollowUpDetails'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfVerificationEvidenceCategorization'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfVerificationReason'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfVerificationDate'],
                            'label': '',
                            'entry_type': 'text',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                        {
                            'base_question': base_question['irfVerifier'],
                            'label': '',
                            'entry_type': 'number',
                            'span': None,
                            'total_question': None,
                            'points': None,
                            'options': None,
                            'other_option': None,
                        },
                    ],
                },
            ]
        },
    ],
    'validations': [
        {
            'tag': 'irfLocationEntered',
            'level': 'warning',
            'validation_type': 'not_blank_or_null',
            'message': 'Location should be entered',
            'questions': [base_question['irfLocation']],
            'trigger': None,
            'trigger_value': None,
            'params': None,
            'on_retrieve': False,
            'on_update': True
        }
    ],
    'export': {
        'tag': 'irfCore',
        'module_name': 'export_import.irf_google_sheet',
        'class_name': 'IrfGoogleSheet',
        'spreadsheet_name': 'irfCore202408',
        'sheet_name': 'irf',
        'key_field_name': 'IRF Number',
        'cards': [
            {
                'category': category['irfPeopleCategory'],
                'prefix': 'Victim',
                'max_instances': 1,
                'index_field_name': None
            },
            {
                'category': category['irfPeopleCategory'],
                'prefix': 'Trafficker %d',
                'max_instances': 5,
                'index_field_name': None
            }
        ],
        'fields': [
            {
                'field_name': 'station',
                'answer_type': 'String',
                'export_name': 'Station',
                'card': None,
                'argument_json': '{"part": "station_name"}'
            },
            {
                'field_name': 'date_time_entered_into_system',
                'answer_type': 'DateTime',
                'export_name': 'Date/Time Entered into System',
                'card': None,
                'argument_json': None
            },
            {
                'field_name': 'status',
                'answer_type': 'String',
                'export_name': 'Status',
                'card': None,
                'argument_json': None
            },
        ],
        'suppress_warnings': True,
    }
}

irf_202408: FormsOfTypeSpec = {
    'form_type': 'IRF',
    'version': '2024.8',
    'form_specs': [irf_core],
}
