# Use a more specific base image
FROM python:3.9-slim-buster

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Clone the repo
RUN git clone https://github.com/ChristoGH/facematcher_deploy.git .

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Create a new group and user
RUN groupadd -r myappgroup && useradd -r -g myappgroup myappuser

# Switch to the new user
USER myappuser

# Expose the required port
EXPOSE 8501

# Set the health check
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1

# Set the entrypoint
ENTRYPOINT ["streamlit", "run", "facematcher_deploy.py", "--server.port=8501", "--server.address=0.0.0.0"]
