# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderstationbudgetcalculation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
