# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-20 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_borderstationbudgetcalculation_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borderstationbudgetcalculation',
            old_name='shelter_electricity',
            new_name='shelter_electricity_amount',
        ),
        migrations.RenameField(
            model_name='borderstationbudgetcalculation',
            old_name='shelter_rent',
            new_name='shelter_rent_amount',
        ),
        migrations.RenameField(
            model_name='borderstationbudgetcalculation',
            old_name='shelter_water',
            new_name='shelter_water_amount',
        ),
        
        # Create other items entries for bikes for staff
        migrations.RunSQL("insert into budget_otherbudgetitemcost (name, cost, form_section, budget_item_parent_id) "\
            "select 'Staff bikes', travel_number_of_staff_using_bikes * travel_number_of_staff_using_bikes_multiplier, 1, id "\
            "from budget_borderstationbudgetcalculation "\
            "where travel_number_of_staff_using_bikes > 0 and travel_number_of_staff_using_bikes_multiplier > 0"),
        migrations.RunSQL("insert into budget_otherbudgetitemcost (name, cost, form_section, budget_item_parent_id) "\
            "select 'Shelter startup', shelter_shelter_startup_amount, 5, id "\
            "from budget_borderstationbudgetcalculation "\
            "where shelter_shelter_startup = true"),
        migrations.RunSQL("insert into budget_otherbudgetitemcost (name, cost, form_section, budget_item_parent_id) "\
            "select 'Last month''s medical expense', medical_last_months_expense, 8, id "\
            "from budget_borderstationbudgetcalculation "\
            "where medical_last_months_expense != 0"),
        
        migrations.RunSQL("update budget_otherbudgetitemcost set form_section=5 where form_section=6"),
        migrations.RunSQL("update budget_otherbudgetitemcost set form_section=2 where form_section=4"),
        migrations.RunSQL("update budget_otherbudgetitemcost set form_section=8 where form_section=9"),
    ]
