# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20151020_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherbudgetitemcost',
            name='form_section',
            field=models.IntegerField(blank=True, null=True, verbose_name=[(1, b'Travel'), (2, b'Miscellaneous'), (3, b'Awareness'), (4, b'Supplies'), (5, b'Shelter'), (6, b'FoodGas'), (7, b'Communication'), (8, b'Staff'), (9, b'Medical'), (10, b'Administration')]),
        ),
    ]
