# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-01-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20210120_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borderstationbudgetcalculation',
            old_name='administration_registration_amount',
            new_name='administration_office_amount',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='administration_registration',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='communication_number_of_staff_with_walkie_talkies',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='communication_number_of_staff_with_walkie_talkies_multiplier',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='shelter_shelter_startup',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='shelter_shelter_startup_amount',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='shelter_shelter_two',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='shelter_shelter_two_amount',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_binoculars_amount',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_binoculars_boolean',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_flashlights_amount',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_flashlights_boolean',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_recorders_amount',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_recorders_boolean',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_walkie_talkies_amount',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='supplies_walkie_talkies_boolean',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='travel_last_months_expense_for_sending_girls_home',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='travel_number_of_staff_using_bikes',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='travel_number_of_staff_using_bikes_multiplier',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='travel_motorbike',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='travel_motorbike_amount',
        ),
         migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='medical_last_months_expense',
        ),
        migrations.AddField(
            model_name='borderstationbudgetcalculation',
            name='administration_office',
            field=models.BooleanField(default=False, verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='borderstationbudgetcalculation',
            name='shelter_electricity',
            field=models.BooleanField(default=False, verbose_name='Electricity'),
        ),
        migrations.AddField(
            model_name='borderstationbudgetcalculation',
            name='shelter_rent',
            field=models.BooleanField(default=False, verbose_name='Rent'),
        ),
        migrations.AddField(
            model_name='borderstationbudgetcalculation',
            name='shelter_water',
            field=models.BooleanField(default=False, verbose_name='Water'),
        ),
        migrations.AlterField(
            model_name='otherbudgetitemcost',
            name='form_section',
            field=models.IntegerField(blank=True, null=True, verbose_name=[(1, 'Travel'), (2, 'Miscellaneous'), (3, 'Awareness'), (5, 'Potential Victim Care'), (7, 'Communication'), (8, 'Staff & Benefits'), (10, 'Administration')]),
        ),
        migrations.RunSQL("update budget_borderstationbudgetcalculation set shelter_electricity=true"),
        migrations.RunSQL("update budget_borderstationbudgetcalculation set shelter_rent=true"),
        migrations.RunSQL("update budget_borderstationbudgetcalculation set shelter_water=true"),
    ]
