# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-20 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20170106_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='miscellaneous_number_of_intercepts_last_month',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='miscellaneous_number_of_intercepts_last_month_multiplier',
        ),
    ]
