# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0006_auto_20170606_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderstationbudgetcalculation',
            name='mdf_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),

    ]
