# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-17 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20210615_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='awareness_sign_boards',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='awareness_sign_boards_boolean',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='food_and_gas_number_of_days',
        ),
        migrations.RemoveField(
            model_name='borderstationbudgetcalculation',
            name='food_and_gas_number_of_limbo_girls',
        ),
    ]
