# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    Budgets = apps.get_model('budget', 'BorderStationBudgetCalculation')
    for row in Budgets.objects.all():
        row.mdf_uuid = uuid.uuid4()
        row.save(update_fields=['mdf_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_borderstationbudgetcalculation_mdf_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='mdf_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        )
    ]
