# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-07-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20210617_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='administration_booth_amount',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='administration_number_of_intercepts_last_month_adder',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='administration_number_of_intercepts_last_month_multiplier',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='administration_number_of_meetings_per_month_multiplier',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='administration_office_amount',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='awareness_awareness_party',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='awareness_contact_cards_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='awareness_contact_cards_boolean_amount',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='communication_chair_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=17, verbose_name='for chair'),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='food_and_gas_limbo_girls_multiplier',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='food_and_gas_number_of_intercepted_girls_multiplier_before',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='shelter_electricity_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='shelter_rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='shelter_water_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='travel_chair_with_bike_amount',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=17, verbose_name='for chair (if has bike)'),
        ),
        migrations.AlterField(
            model_name='borderstationbudgetcalculation',
            name='travel_plus_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='otherbudgetitemcost',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='staffbudgetitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, null=True),
        ),
    ]
