# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-06 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20220324_1941'),
    ]

    operations = [
        migrations.RunSQL("update budget_otherbudgetitemcost "\
                          "set work_project_id = ("\
                          "select  border_station_id "\
                          "from budget_borderstationbudgetcalculation "\
                          "where id = budget_otherbudgetitemcost.budget_item_parent_id)"),
        migrations.RunSQL("update budget_staffbudgetitem "\
                          "set work_project_id = ("\
                          "select  border_station_id "\
                          "from budget_borderstationbudgetcalculation "\
                          "where id = budget_staffbudgetitem.budget_calc_sheet_id)"),
        migrations.RunSQL("update budget_otherbudgetitemcost "\
                          "set form_section = 10 " \
                          "where form_section = 2"),
    ]
