# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20220406_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderstationbudgetcalculation',
            name='date_finalized',
            field=models.DateField(null=True),
        ),
    ]
