# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-28 14:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataentry', '0254_auto_20230509_1844'),
        ('static_border_stations', '0006_auto_20230509_1733'),
        ('budget', '0013_borderstationbudgetcalculation_past_sent_approved'),
    ]
    
    budget_type = '0'
    try:
        budget_type = str(ContentType.objects.get(app_label='budget', model='borderstationbudgetcalculation').id)
    except:
        # In test environment, ContentType does not work correctly, but in test there is no data to migrate
        pass

    operations = [
        migrations.CreateModel(
            name='MdfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(verbose_name=[(11, 'Past Month Sent Money'), (12, 'Limbo Potential Victims'), (13, 'Money Not Spent')])),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('associated_section', models.IntegerField(blank=True, null=True, verbose_name=[(1, 'Staff Travel'), (3, 'Awareness'), (5, 'Potential Victim Care'), (7, 'Communication'), (8, 'Salaries & Benefits'), (10, 'Administration'), (11, 'Past Month Sent Money'), (12, 'Limbo Potential Victims'), (13, 'Money Not Spent'), (14, 'Operational Expenses'), (15, 'Rent & Utilities')])),
                ('deduct', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyDistributionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_entered', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Submitted', max_length=127)),
                ('month_year', models.DateTimeField(default=datetime.datetime.now)),
                ('last_month_number_of_intercepted_pvs', models.PositiveIntegerField(default=0, verbose_name='# last month PVs')),
                ('number_of_pv_days', models.PositiveIntegerField(default=0)),
                ('past_sent_approved', models.CharField(blank=True, max_length=127)),
                ('border_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyDistributionMultipliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('category', models.IntegerField(verbose_name=[(1, 'Staff Travel'), (3, 'Awareness'), (5, 'Potential Victim Care'), (7, 'Communication'), (8, 'Salaries & Benefits'), (10, 'Administration'), (11, 'Past Month Sent Money'), (12, 'Limbo Potential Victims'), (13, 'Money Not Spent'), (14, 'Operational Expenses'), (15, 'Rent & Utilities')])),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_entered', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Submitted', max_length=127)),
                ('category', models.IntegerField(verbose_name=[(8, 'Salaries & Benefits'), (15, 'Rent & Utilities'), (10, 'Administration'), (3, 'Supplies & Awareness'), (1, 'Staff Travel'), (5, 'Potential Victim Care'), (14, 'Operational Expenses'), (16, 'Multipliers')])),
                ('original_cost', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('monthly', models.BooleanField(default=False, verbose_name='Monthly')),
                ('benefit_type_name', models.CharField(blank=True, max_length=127)),
                ('discussion_status', models.CharField(default='None', max_length=127)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('override_mdf_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='override_mdf', to='dataentry.BorderStation')),
                ('prior_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.ProjectRequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='static_border_stations.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequestAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='project_request_attachments')),
                ('option', models.CharField(max_length=127, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.ProjectRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=127)),
                ('comment', models.TextField(blank=True, verbose_name='Description')),
                ('mdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.MonthlyDistributionForm')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.ProjectRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequestDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_entered', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, verbose_name='Discussion text')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('notify', models.ManyToManyField(related_name='discussion_notify', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.ProjectRequest')),
                ('response', models.ManyToManyField(related_name='discussion_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='monthlydistributionform',
            name='requests',
            field=models.ManyToManyField(to='budget.ProjectRequest'),
        ),
        migrations.AddField(
            model_name='mdfitem',
            name='mdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.MonthlyDistributionForm'),
        ),
        migrations.AddField(
            model_name='mdfitem',
            name='work_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation'),
        ),
        migrations.CreateModel(
            name='MdfCombined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('month_year', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='Submitted', max_length=127)),
                ('date_time_entered', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('border_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        
        migrations.RunSQL("insert into budget_monthlydistributionmultipliers (name, category)  values ('PV Food & Snacks per Day',5)"),
        migrations.RunSQL("insert into budget_monthlydistributionmultipliers (name, category)  values ('Stationary',3)"),
        migrations.RunSQL("insert into budget_monthlydistributionmultipliers (name, category)  values ('Limbo PV cost per Day',12)"),
        
        migrations.RunSQL("insert into budget_mdfcombined (object_id, content_type_id, border_station_id, month_year, date_time_entered, date_time_last_updated, status) "\
                          "select id," + budget_type + ",border_station_id, month_year, date_time_entered, date_time_last_updated, "\
                                "case when date_finalized is null then 'Submitted' else 'Final' end as status "\
                          "from budget_borderstationbudgetcalculation"),
    ]
