# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-01 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20230628_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='completed_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
