# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20230628_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdfitem',
            name='reason_not_deduct',
            field=models.TextField(blank=True, verbose_name='Reason to not deduct'),
        ),
    ]
