# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_mdfitem_reason_not_deduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdfitem',
            name='approved_by',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.RunSQL("update budget_mdfitem "\
                          "set approved_by = (select past_sent_approved from budget_monthlydistributionform mdf where mdf_id = mdf.id) "\
                          "where category = 11"),
    ]
