# Generated by Django 4.2.10 on 2024-10-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_stationary_to_stationery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdfitem',
            name='associated_section',
            field=models.IntegerField(blank=True, null=True, verbose_name=[(1, 'Staff Travel'), (3, 'Supplies & Awareness'), (5, 'PV Care'), (7, 'Communication'), (8, 'Salaries & Benefits'), (10, 'Administration'), (11, 'Past Month Sent Money'), (12, 'Limbo Potential Victims'), (13, 'Money Not Spent'), (14, 'Operational Expenses'), (15, 'Rent & Utilities'), (16, 'Multipliers'), (17, 'Guides')]),
        ),
        migrations.AlterField(
            model_name='monthlydistributionmultipliers',
            name='category',
            field=models.IntegerField(verbose_name=[(1, 'Staff Travel'), (3, 'Supplies & Awareness'), (5, 'PV Care'), (7, 'Communication'), (8, 'Salaries & Benefits'), (10, 'Administration'), (11, 'Past Month Sent Money'), (12, 'Limbo Potential Victims'), (13, 'Money Not Spent'), (14, 'Operational Expenses'), (15, 'Rent & Utilities'), (16, 'Multipliers'), (17, 'Guides')]),
        ),
    ]
