# Generated by Django 4.2.10 on 2024-10-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_monthlydistributionform_signed_pbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydistributionform',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
