# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalchargevictim',
            name='victim_status',
            field=models.TextField(null=True),
        ),
    ]
