# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcharge',
            name='legal_charge_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
