# Generated by Django 4.2.10 on 2024-02-29 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal', '0002_auto_20240113_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcharge',
            name='form_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
