# Generated by Django 4.2.10 on 2024-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_alter_legalcharge_form_entered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalchargesuspect',
            name='police_case_or_court_case',
        ),
        migrations.AddField(
            model_name='legalchargesuspect',
            name='how_do_you_know',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='legalchargesuspect',
            name='verified_by',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='legalchargesuspect',
            name='verified_date',
            field=models.DateField(null=True),
        ),
    ]
