# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0028_auto_20160221_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interceptionrecord',
            name='irf_number',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'IRF #:'),
        ),
        migrations.AlterField(
            model_name='victiminterview',
            name='vif_number',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'VIF #'),
        ),
    ]
