# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:06
from __future__ import unicode_literals
from itertools import chain
from django.db import models, migrations
from django.core.management import call_command
import ipdb


def migrate_foreign_keys(app_config, app_name, model_name, person_field_name, person_list):
    model = app_config.get_model(app_name, model_name)
    Person = app_config.get_model(app_name, 'Person')

    for instance in model.objects.all():

        person = Person.objects.create()

        #Looping/Getting all the attributes for the Person object
        for person_attr in person_list:
            person_attr_data = getattr(instance, person_attr)

            #Apply the correct attribute
            if "name" in person_attr:
                person.full_name = person_attr_data.strip()
            elif "age" in person_attr:
                try:
                    if type(person_attr_data) == unicode:
                        person_attr_data = int(person_attr_data)
                except:
                    person_attr_data = None
                if type(person_attr_data) == int:
                    person.age = person_attr_data
            elif "gender" in person_attr:
                if person_attr_data is not None and len(person_attr_data) > 0:
                    person.gender = person_attr_data.upper().strip()[0]
            elif "address1" in person_attr:
                person.address1 = person_attr_data
            elif "address2" in person_attr:
                person.address2 = person_attr_data
            elif "phone" in person_attr:
                person.phone_contact = person_attr_data.strip()

        setattr(instance, person_field_name, person)

        person.save()

        instance.save()

def migration_ops(model_name, person_field_name, person_list):
    return [

        # Add temporary fields to store the new foreign keys.
        migrations.AddField(model_name=model_name, name=person_field_name, field=models.ForeignKey(to='dataentry.Person', null=True, blank=True)),

        # Set values for the temporary fields.
        migrations.RunPython(lambda app, schema_editor: migrate_foreign_keys(app, 'dataentry', model_name, person_field_name, person_list)),

        #Remove the old fields that are now replaced with the Person FK
        migrations.RemoveField(model_name=model_name, name=person_list[0]),
        migrations.RemoveField(model_name=model_name, name=person_list[1]),
        migrations.RemoveField(model_name=model_name, name=person_list[2]),
        migrations.RemoveField(model_name=model_name, name=person_list[3]),
        migrations.RemoveField(model_name=model_name, name=person_list[4]),
        migrations.RemoveField(model_name=model_name, name=person_list[5]),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0029_auto_20160310_0212'),
    ]

    operations = chain(
        migration_ops('interceptee', 'person', ["full_name", "address1", "address2", "age", "gender", "phone_contact"]),
        migration_ops('victiminterview', 'victim', ["victim_name", "victim_address1", "victim_address2", "victim_age", "victim_gender", "victim_phone"]),
        migration_ops('victiminterviewpersonbox', 'person', ["name", "address1", "address2", "age", "gender", "phone"]),
    )
