# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0015_auto_20160304_0144'),
        ('dataentry', '0031_auto_20160311_0143'),
    ]

    operations = [
    ]
