# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0031_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        # migrations.AddField(
        #     model_name='interceptee',
        #     name='photo',
        #     field=models.ImageField(blank=True, default=b'', upload_to=b'interceptee_photos'),
        # ),
    ]
