# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0032_auto_20160405_0110'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='victiminterview',
        #     name='victim_address1',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterview',
        #     name='victim_address2',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterview',
        #     name='victim_age',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterview',
        #     name='victim_gender',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterview',
        #     name='victim_name',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterview',
        #     name='victim_phone',
        # ),
        # migrations.AddField(
        #     model_name='victiminterview',
        #     name='victim',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person'),
        # ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'm'), (b'F', b'f')], max_length=4),
        ),
        # migrations.AlterField(
        #     model_name='victiminterviewpersonbox',
        #     name='gender',
        #     field=models.CharField(blank=True, choices=[(b'Male', b'male'), (b'Female', b'female')], max_length=12, verbose_name=b'Gender'),
        # ),
    ]
