# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0032_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'm'), (b'F', b'f')], max_length=4),
        ),
    ]
