# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0033_auto_20160428_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address1',
            name='level',
            field=models.CharField(choices=[(b'Country', b'Country'), (b'State', b'State'), (b'District', b'District'), (b'City', b'City'), (b'VDC', b'VDC'), (b'Block', b'Block'), (b'Building', b'Building')], default=b'District', max_length=255),
        ),
        migrations.AlterField(
            model_name='address2',
            name='level',
            field=models.CharField(choices=[(b'Country', b'Country'), (b'State', b'State'), (b'District', b'District'), (b'City', b'City'), (b'VDC', b'VDC'), (b'Block', b'Block'), (b'Building', b'Building')], default=b'VDC', max_length=255),
        ),
    ]
