# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0033_auto_20160428_1941'),
        ('dataentry', '0030_auto_20160318_0013'),
    ]

    operations = [
    ]
