# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0033_auto_20160405_0639'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='victiminterviewpersonbox',
        #     name='address1',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterviewpersonbox',
        #     name='address2',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterviewpersonbox',
        #     name='age',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterviewpersonbox',
        #     name='gender',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterviewpersonbox',
        #     name='name',
        # ),
        # migrations.RemoveField(
        #     model_name='victiminterviewpersonbox',
        #     name='phone',
        # ),
        # migrations.AddField(
        #     model_name='victiminterviewpersonbox',
        #     name='person',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person'),
        # ),
    ]
