# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0034_auto_20160408_2258'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='interceptee',
        #     name='person',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person'),
        # ),
        # migrations.AlterField(
        #     model_name='victiminterview',
        #     name='victim',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person'),
        # ),
        # migrations.AlterField(
        #     model_name='victiminterviewpersonbox',
        #     name='person',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person'),
        # ),
    ]
