# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0034_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuzzymatching',
            name='phone_number_cutoff',
        ),
        migrations.RemoveField(
            model_name='fuzzymatching',
            name='phone_number_limit',
        ),
    ]
