# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0034_auto_20160511_0727'),
        ('dataentry', '0035_auto_20160511_0055'),
    ]

    operations = [
    ]
