# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0037_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='date_time_last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 24, 0, 33, 22, 426298, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
