# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0038_sitesettings_date_time_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuzzyMatching',
        ),
    ]
