# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-09 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0039_delete_fuzzymatching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zoom_level', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='interceptionrecord',
            name='border_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataentry.BorderStation'),
        ),
        migrations.AddField(
            model_name='victiminterview',
            name='border_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataentry.BorderStation'),
        ),
        migrations.AddField(
            model_name='borderstation',
            name='operating_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataentry.Country'),
        ),
    ]
