# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-10 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0040_auto_20170209_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borderstation',
            name='operating_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataentry.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='zoom_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interceptionrecord',
            name='border_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataentry.BorderStation'),
        ),
        migrations.AlterField(
            model_name='victiminterview',
            name='border_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataentry.BorderStation'),
        ),
    ]
