# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0041_auto_20170210_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='alias_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.AliasGroup'),
        ),
    ]
