# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0042_auto_20170421_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='interceptionrecord',
            name='case_notes',
            field=models.TextField(blank=True, verbose_name=b'Case Notes'),
        ),
    ]
