# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0047_permission_enable_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderstation',
            name='time_zone',
            field=models.CharField(default='Asia/Kathmandu', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='min_level',
            field=models.CharField(default='STATION', max_length=100),
        ),
    ]
