# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 19:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0047_permission_enable_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100000, null=True)),
                ('code', models.CharField(max_length=125, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='CardStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('column_layout', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Export_Import_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('field_type', models.CharField(max_length=126)),
                ('export_name', models.CharField(max_length=126)),
                ('arguments_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExportImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=126, null=True)),
                ('implement_class_name', models.CharField(max_length=126, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportImportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=126)),
                ('max_instances', models.PositiveIntegerField()),
                ('card_export_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_import_card', to='dataentry.ExportImport')),
                ('export_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_import_base', to='dataentry.ExportImport')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Country')),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_or_import', models.CharField(max_length=10)),
                ('spreadsheet_name', models.CharField(max_length=126)),
                ('sheet_name', models.CharField(max_length=126)),
                ('key_column', models.CharField(max_length=126)),
                ('import_status_column', models.CharField(max_length=126, null=True)),
                ('import_issue_column', models.CharField(max_length=126, null=True)),
                ('export_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.ExportImport')),
            ],
        ),
        migrations.CreateModel(
            name='Irf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irf_number', models.CharField(max_length=20, unique=True, verbose_name='IRF #:')),
                ('number_of_victims', models.PositiveIntegerField(blank=True, null=True, verbose_name='# of victims:')),
                ('location', models.CharField(max_length=255, verbose_name='Location:')),
                ('date_time_of_interception', models.DateTimeField(verbose_name='Date/Time:')),
                ('number_of_traffickers', models.PositiveIntegerField(blank=True, null=True, verbose_name='# of traffickers')),
                ('staff_name', models.CharField(max_length=255, verbose_name='Staff Name:')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Form')),
            ],
        ),
        migrations.CreateModel(
            name='IrfResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100000, null=True)),
                ('irf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Irf')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_part', models.CharField(max_length=126, null=True)),
                ('layout', models.CharField(max_length=126)),
                ('span', models.PositiveIntegerField(null=True)),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.AnswerType')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=126)),
                ('description', models.CharField(max_length=126)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.AnswerType')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=126)),
                ('span', models.PositiveIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Category')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=126)),
                ('foreign_key_field_parent', models.CharField(max_length=126, null=True)),
                ('foreign_key_field_child', models.CharField(max_length=126, null=True)),
                ('parent_storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Storage')),
            ],
        ),
        migrations.AlterField(
            model_name='permission',
            name='min_level',
            field=models.CharField(default='STATION', max_length=100),
        ),
        migrations.AddField(
            model_name='questionstorage',
            name='foreign_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Storage'),
        ),
        migrations.AddField(
            model_name='questionstorage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question'),
        ),
        migrations.AddField(
            model_name='previewlayout',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question'),
        ),
        migrations.AddField(
            model_name='irfresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.FormType'),
        ),
        migrations.AddField(
            model_name='form',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Storage'),
        ),
        migrations.AddField(
            model_name='export_import_question',
            name='export_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.ExportImport'),
        ),
        migrations.AddField(
            model_name='export_import_question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.CategoryType'),
        ),
        migrations.AddField(
            model_name='category',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Form'),
        ),
        migrations.AddField(
            model_name='cardstorage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Category'),
        ),
        migrations.AddField(
            model_name='cardstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Storage'),
        ),
        migrations.AddField(
            model_name='answerlayout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Category'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question'),
        ),
    ]
