# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0048_auto_20180427_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irfindia',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.RunSQL("UPDATE dataentry_permission SET min_level = 'STATION' where permission_group = 'IRF';"),
        migrations.RunSQL("INSERT INTO dataentry_permission (permission_group, action, min_level, account_permission_name) values ('FORMS', 'CLASSIC','GLOBAL', null);"),
    ]
