# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0048_auto_20180307_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_warning_message', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='FormValidationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question')),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.FormValidation')),
            ],
        ),
        migrations.CreateModel(
            name='FormValidationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
            ],
        ),
        migrations.RenameField(
            model_name='irfresponse',
            old_name='irf',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='model_name',
            new_name='form_model_name',
        ),
        migrations.AddField(
            model_name='storage',
            name='module_name',
            field=models.CharField(default='UNSET', max_length=126),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='response_model_name',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Form'),
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Question'),
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='validation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.FormValidationType'),
        ),
    ]
