# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0049_auto_20180516_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irfindia',
            name='trafficker_taken_into_custody',
        ),
        migrations.RemoveField(
            model_name='irfnepal',
            name='trafficker_taken_into_custody',
        ),
        migrations.AddField(
            model_name='intercepteeindia',
            name='trafficker_taken_into_custody',
            field=models.BooleanField(default=False, verbose_name='taken_into_custody'),
        ),
        migrations.AddField(
            model_name='intercepteenepal',
            name='trafficker_taken_into_custody',
            field=models.BooleanField(default=False, verbose_name='taken_into_custody'),
        ),
    ]
