# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0050_auto_20180522_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalidation',
            name='trigger_value',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
