# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0052_auto_20180529_1710'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO dataentry_permission (permission_group, action, min_level, account_permission_name) values ('IRF', 'VIEW PI','STATION',null);"),
    ]
