# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0048_auto_20180717_2333'),
        ('dataentry', '0054_auto_20180613_1744'),
    ]

    operations = [
    ]
