# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 12:37
from __future__ import unicode_literals
import os

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.core.management import call_command
from django.core.management.color import no_style
from django.db import connection

from dataentry.models import Country

app_name = 'dataentry'

country_names = [
    'Nepal',
    'South Africa',
    'Thailand',
    'India'
    ]

form_model_names = [
    'FormType',
    'Storage',
    "Form",
    'CategoryType',
    'Category',
    'CardStorage',
    'AnswerType',
    'Question',
    'QuestionLayout',
    'QuestionStorage',
    'Answer',
    'FormValidationLevel',
    'FormValidationType',
    'FormValidation',
    'FormValidationQuestion',
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0054_auto_20180613_1744'),
    ]
    
    def ensure_countries(apps, schema_editor):
        id = 1
        for country_name in country_names:
            country = Country()
            country.id = id
            country.name = country_name
            country.latitude = 0
            country.longitude = 0
            try:
                country.save()
            except:
                pass
            
            id = id + 1
            
        sequence_sql = connection.ops.sequence_reset_sql(no_style(), [Country,])
        with connection.cursor() as cursor:
            for sql in sequence_sql:
                cursor.execute(sql)

    def load_fixture(apps, schema_editor):
        fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../fixtures'))
        fixture_filename = 'form_data_20180713.json'
        fixture_file = os.path.join(fixture_dir, fixture_filename)
        call_command('loaddata', fixture_file) 
    
    def unload_prior(apps, schema_editor):
        for model_name in reversed(form_model_names):
            my_model = apps.get_model(app_name, model_name)
            rc = my_model.objects.all().delete()

    operations = [
        migrations.AlterField(
            model_name='irfindia',
            name='how_sure_was_trafficking',
            field=models.IntegerField(choices=[(1, '1 - Not at all sure'), (2, '2 - Unsure but suspects it'), (3, '3 - Somewhat sure'), (4, '4 - Very sure'), (5, '5 - Absolutely sure')], null=True, verbose_name='How sure are you that it was trafficking case?'),
        ),
        migrations.AlterField(
            model_name='irfindia',
            name='type_of_intercept',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='irfindia',
            name='who_noticed',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='how_sure_was_trafficking',
            field=models.IntegerField(choices=[(1, '1 - Not at all sure'), (2, '2 - Unsure but suspects it'), (3, '3 - Somewhat sure'), (4, '4 - Very sure'), (5, '5 - Absolutely sure')], null=True, verbose_name='How sure are you that it was trafficking case?'),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='type_of_intercept',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='who_noticed',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='how_sure_was_trafficking',
            field=models.IntegerField(choices=[(1, '1 - Not at all sure'), (2, '2 - Unsure but suspects it'), (3, '3 - Somewhat sure'), (4, '4 - Very sure'), (5, '5 - Absolutely sure')], null=True, verbose_name='How sure are you that it was trafficking case?'),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='type_of_intercept',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='who_noticed',
            field=models.CharField(max_length=127, null=True),
        ),
                  
        migrations.RunPython(ensure_countries),
        migrations.RunPython(unload_prior),
        migrations.RunPython(load_fixture),
    ]
