# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0055_auto_20180713_1237'),
        ('dataentry', '0048_auto_20180717_2333'),
    ]

    operations = [
         migrations.RunSQL("insert into dataentry_userlocationpermission (account_id, country_id, permission_id, station_id) select id, null, 25, null from accounts_account;"),
    ]
