# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0060_form_migration_fix'),
        ('dataentry', '0058_edit_delete_permission'),
    ]

    operations = [
    ]
