# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0062_auto_20180824_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irfindia',
            name='case_notes',
        ),
        migrations.RemoveField(
            model_name='irfmalawi',
            name='case_notes',
        ),
        migrations.RemoveField(
            model_name='irfnepal',
            name='case_notes',
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='reason_for_intercept',
            field=models.TextField(blank=True, verbose_name='Reason For Intercept'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='reason_for_intercept',
            field=models.TextField(blank=True, verbose_name='Reason For Intercept'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='reason_for_intercept',
            field=models.TextField(blank=True, verbose_name='Reason For Intercept'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='reason_for_intercept',
            field=models.TextField(blank=True, verbose_name='Reason For Intercept'),
        ),
    ]
