# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 23:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from dataentry.models.form_migration import FormMigration

def migrate_forms(apps, schema_editor):
    # Invoke form migration with specific file containing lastest form data
    FormMigration.migrate(apps, schema_editor, 'form_data_20180903.json')


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0063_auto_20180830_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportImportField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=126)),
                ('export_name', models.CharField(max_length=126)),
                ('arguments_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_answer_type', to='dataentry.AnswerType')),
            ],
        ),
        migrations.RemoveField(
            model_name='export_import_question',
            name='export_import',
        ),
        migrations.RemoveField(
            model_name='export_import_question',
            name='question',
        ),
        migrations.RenameField(
            model_name='googlesheet',
            old_name='key_column',
            new_name='key_field_name',
        ),
        migrations.AddField(
            model_name='googlesheet',
            name='suppress_column_warnings',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='exportimportcard',
            name='card_export_import',
        ),
        migrations.RemoveField(
            model_name='exportimportcard',
            name='start_position',
        ),
        migrations.AddField(
            model_name='exportimport',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportimport',
            name='implement_module',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='exportimportcard',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='export_import_card', to='dataentry.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='export_name',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='export_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='exportimportcard',
            name='export_import',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='export_import_base', to='dataentry.ExportImport'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Export_Import_Question',
        ),
        migrations.AddField(
            model_name='exportimportfield',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.ExportImportCard'),
        ),
        migrations.AddField(
            model_name='exportimportfield',
            name='export_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.ExportImport'),
        ),
        migrations.RenameModel(
            old_name='GoogleSheet',
            new_name='GoogleSheetConfig',
        ),
        migrations.RunPython(migrate_forms),
    ]
