# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0064_auto_20180902_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irfbangladesh',
            name='convinced_by_family',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfbangladesh',
            name='convinced_by_police',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfbangladesh',
            name='convinced_by_staff',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfbangladesh',
            name='purpose_for_going_other',
            field=models.CharField(blank=True, max_length=127, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='irfbangladesh',
            name='where_going_other',
            field=models.CharField(blank=True, max_length=127, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='irfindia',
            name='convinced_by_family',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfindia',
            name='convinced_by_police',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfindia',
            name='convinced_by_staff',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfindia',
            name='noticed_other_sign',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfmalawi',
            name='convinced_by_family',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfmalawi',
            name='convinced_by_police',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfmalawi',
            name='convinced_by_staff',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='convinced_by_family',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='convinced_by_police',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='convinced_by_staff',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfnepal',
            name='noticed_other_sign',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='convinced_by_family',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='convinced_by_police',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='convinced_by_staff',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
