# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0064_auto_20180902_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irfindia',
            name='reason_for_intercept',
        ),
        migrations.RemoveField(
            model_name='irfmalawi',
            name='reason_for_intercept',
        ),
        migrations.RemoveField(
            model_name='irfnepal',
            name='reason_for_intercept',
        ),
        migrations.AddField(
            model_name='irfindia',
            name='case_notes',
            field=models.TextField(blank=True, verbose_name='Case Notes'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='case_notes',
            field=models.TextField(blank=True, verbose_name='Case Notes'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='case_notes',
            field=models.TextField(blank=True, verbose_name='Case Notes'),
        ),
        migrations.AlterField(
            model_name='irfbangladesh',
            name='known_place_bangladesh',
            field=models.CharField(default='False', max_length=127),
        ),
    ]
