# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0068_auto_20181015_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address1',
            name='level',
            field=models.CharField(choices=[('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('City', 'City'), ('VDC', 'VDC'), ('Block', 'Block'), ('Building', 'Building'), ('Village', 'Village'), ('Post Office', 'Post Office'), ('Upozilla', 'Upozilla')], default='District', max_length=255),
        ),
        migrations.AlterField(
            model_name='address2',
            name='level',
            field=models.CharField(choices=[('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('City', 'City'), ('VDC', 'VDC'), ('Block', 'Block'), ('Building', 'Building'), ('Village', 'Village'), ('Post Office', 'Post Office'), ('Upozilla', 'Upozilla')], default='VDC', max_length=255),
        ),
    ]
