# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0068_cifnepal_locationboxnepal_personboxnepal_potentialvictimnepal_transporationnepal_vehicleboxnepal'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationboxnepal',
            name='flag_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personboxnepal',
            name='flag_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialvictimnepal',
            name='flag_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporationnepal',
            name='flag_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleboxnepal',
            name='flag_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
