# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0069_auto_20181019_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cifnepal',
            old_name='border_cross_bus',
            new_name='border_cross_vehicle',
        ),
        migrations.RemoveField(
            model_name='cifnepal',
            name='border_cross_rickshaw',
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='suspected_trafficker_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='travel_expenses_paid_by_broker_pb',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='travel_expenses_paid_by_broker_repaid_pb',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='travel_expenses_paid_to_broker_pb',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='address1',
            name='level',
            field=models.CharField(choices=[('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('City', 'City'), ('VDC', 'VDC'), ('Block', 'Block'), ('Building', 'Building'), ('Village', 'Village'), ('Post Office', 'Post Office'), ('Upozilla', 'Upozilla')], default='District', max_length=255),
        ),
        migrations.AlterField(
            model_name='address2',
            name='level',
            field=models.CharField(choices=[('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('City', 'City'), ('VDC', 'VDC'), ('Block', 'Block'), ('Building', 'Building'), ('Village', 'Village'), ('Post Office', 'Post Office'), ('Upozilla', 'Upozilla')], default='VDC', max_length=255),
        ),
    ]
