# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-01 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0070_auto_20181025_1732'),
        ('dataentry', '0069_auto_20181030_0604'),
    ]

    operations = [
    ]
