# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-06 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0068_auto_20181024_1729'),
        ('dataentry', '0071_merge_20181101_1434'),
    ]

    operations = [
    ]
