# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-20 15:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0074_auto_20181203_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlayout',
            name='form_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
