# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-03 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0073_exportimportcard_index_field_name'),
    ]

    operations = [
        migrations.RunSQL("UPDATE dataentry_permission SET min_level='STATION' where permission_group='BUDGETS';"),
    ]
