# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0076_auto_20190114_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irfnepal',
            name='noticed_walking_to_border',
        ),
        migrations.RemoveField(
            model_name='irfnepal',
            name='over_18_family_doesnt_know',
        ),
        migrations.RemoveField(
            model_name='irfnepal',
            name='over_18_family_unwilling',
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='contradiction_between_stories',
            field=models.BooleanField(default=False, verbose_name='Contradiction between stories'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='evidence_categorization',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='family_doesnt_know_where_going_18_23',
            field=models.BooleanField(default=False, verbose_name='18-23 Family doesnt know where they are going'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='family_unwilling_to_let_go_18_23',
            field=models.BooleanField(default=False, verbose_name='18-23 Family unwilling to let them go'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='group_facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='group_missed_call',
            field=models.BooleanField(default=False, verbose_name='Missed Call'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='group_other_website',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='noticed_on_train',
            field=models.BooleanField(default=False, verbose_name='On a train'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='over_23_family_unwilling_to_let_go',
            field=models.BooleanField(default=False, verbose_name='Over 23 Family unwilling to let them go'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='reason_for_intercept',
            field=models.TextField(blank=True, verbose_name='Primary reason for intercept'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='relationship_to_get_married',
            field=models.BooleanField(default=False, verbose_name='Coming to get married'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='where_going_someone_paid_expenses',
            field=models.BooleanField(default=False, verbose_name='Non relatives paid for their travel'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='who_in_group_dating',
            field=models.BooleanField(default=False, verbose_name='Boyfriend / Girlfriend'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='who_in_group_engaged',
            field=models.BooleanField(default=False, verbose_name='Fiancée'),
        ),
    ]
