# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0077_auto_20190122_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irfbangladesh',
            old_name='walking_to_border',
            new_name='noticed_walking_to_border',
        ),
        migrations.RemoveField(
            model_name='irfnepal',
            name='noticed_on_train',
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='noticed_walking_to_border',
            field=models.BooleanField(default=False, verbose_name='Walking to border'),
        ),
        migrations.RunSQL("UPDATE dataentry_irfnepal SET noticed_walking_to_border = (select noticed_walking_to_border from dataentry_interceptionrecord where dataentry_interceptionrecord.id = dataentry_irfnepal.id)  where dataentry_interceptionrecord.id = dataentry_irfnepal.id) where id in (select id from dataentry_interceptionrecord);"),
        
    ]
