# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0078_auto_20190214_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CifAttachmentNepal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='cif_attachments', verbose_name='Attach scanned copy of form (pdf or image)')),
                ('cif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.CifNepal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
