# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0079_cifattachmentnepal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrfAttachmentSouthAfrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='scanned_irf_forms', verbose_name='Attach scanned copy of form (pdf or image)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='irfattachmentsouthafrica',
            name='interception_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.IrfSouthAfrica'),
        ),
        migrations.RenameField(
            model_name='irfsouthafrica',
            old_name='passport_fake',
            new_name='passport_fraudulent',
        ),
        migrations.RenameField(
            model_name='irfsouthafrica',
            old_name='supporting_documents_fake',
            new_name='supporting_documents_fraudulent',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='appearance_lady_boy',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='destination_ireland',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='destination_manchester',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='destination_swaziland',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_african_child',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_african_female',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_asian_female',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_bangladeshi_male',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_east_europe_female',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_ethiopian_female',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_malawian_female',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_nepali_male',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_other',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='nationality_gender_pakistani_male',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='scanned_form',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='where_going_relationship',
        ),
        migrations.RemoveField(
            model_name='irfsouthafrica',
            name='where_going_visit',
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='believe_they_are_pvot',
            field=models.NullBooleanField(verbose_name='Do they believe they are PVOT?'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='case_report',
            field=models.BooleanField(default=False, verbose_name='Case report'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='cif',
            field=models.BooleanField(default=False, verbose_name='CIF'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='contradiction_in_story',
            field=models.BooleanField(default=False, verbose_name='contradicction in story'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='destination_lesotho',
            field=models.BooleanField(default=False, verbose_name='Lesotho'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='details_validated_and_correted',
            field=models.BooleanField(default=False, verbose_name='Details were validated and corrected'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='documentation_in_order',
            field=models.BooleanField(default=False, verbose_name='Documentation in order'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='entry_allowed',
            field=models.BooleanField(default=False, verbose_name='Entry allowed'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='entry_refused',
            field=models.BooleanField(default=False, verbose_name='Entry refused'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='host_non_relative_paid',
            field=models.BooleanField(default=False, verbose_name='Host/Recruiter is non-relative and paid for travel expenses'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='ims_case_number',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='interview_findings',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='no_red_flags',
            field=models.BooleanField(default=False, verbose_name='No red flags'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='no_return_ticket',
            field=models.BooleanField(default=False, verbose_name='No return ticket'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='paid_for_accomodations',
            field=models.BooleanField(default=False, verbose_name='Paid for accomodations'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='reason_believe_trafficked',
            field=models.TextField(blank=True, default='', verbose_name='What is the primary reason you believe this person is being trafficked or is at high risk of being trafficked'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='relationship_suspect_forced_marriage',
            field=models.BooleanField(default=False, verbose_name='Suspect forced marriage'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='require_assistance',
            field=models.NullBooleanField(verbose_name='Do they require assistance?'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='status_misuse_of_permit',
            field=models.BooleanField(default=False, verbose_name='Misuse of permit'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='story_caught_in_lie',
            field=models.BooleanField(default=False, verbose_name='Caught in lie'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='story_consistent',
            field=models.BooleanField(default=False, verbose_name='Story consistent'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='story_contradicts_pvot',
            field=models.BooleanField(default=False, verbose_name="Contradicts PVOT's story"),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='story_will_not_provide_permit',
            field=models.BooleanField(default=False, verbose_name='Hangs up when asked for permit/ID'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='transit_allowed',
            field=models.BooleanField(default=False, verbose_name='Transit allowed'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='transit_refused',
            field=models.BooleanField(default=False, verbose_name='Transit refused'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='visit_no_connection_to_host',
            field=models.BooleanField(default=False, verbose_name='No clear connection to host'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='visit_unaware_who_fetch',
            field=models.BooleanField(default=False, verbose_name='Unaware of who is fetching them from airport'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='visit_unaware_who_fetching_them',
            field=models.BooleanField(default=False, verbose_name='Unaware of who is fetching them from airport'),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='paid_no_payback_terms',
            field=models.BooleanField(default=False, verbose_name='Not determined payback terms'),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='paid_offer_expenses',
            field=models.BooleanField(default=False, verbose_name='Offering to pay without expectations/explanation'),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='story_claims_not_know',
            field=models.BooleanField(default=False, verbose_name='Claims not to know PVOT'),
        ),
        migrations.AlterField(
            model_name='irfsouthafrica',
            name='visit_doesnt_know_host',
            field=models.BooleanField(default=False, verbose_name='Does not know host well'),
        ),
        
    ]
