# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0079_cifattachmentnepal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporationnepal',
            name='transportation_crossing',
        ),
        migrations.AddField(
            model_name='transporationnepal',
            name='transportation_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
