# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-20 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0080_auto_20190314_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrfAttachmentIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='scanned_irf_forms', verbose_name='Attach scanned copy of form (pdf or image)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='irfattachmentindia',
            name='interception_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.IrfIndia'),
        ),
        migrations.RunSQL("insert into dataentry_irfattachmentindia (attachment_number, description, attachment, interception_record_id) select 1, 'scanned irf', scanned_form, id from dataentry_irfindia where scanned_form is not null and scanned_form != '';"),
        migrations.RemoveField(
            model_name='irfindia',
            name='group_wife_girl_indian',
        ),
        migrations.RemoveField(
            model_name='irfindia',
            name='group_wife_girl_nepali_bengali',
        ),
        migrations.RemoveField(
            model_name='irfindia',
            name='meeting_someone_across_border',
        ),
        migrations.RemoveField(
            model_name='irfindia',
            name='noticed_other_sign',
        ),
        migrations.RemoveField(
            model_name='irfindia',
            name='over_18_family_doesnt_know',
        ),
        migrations.RemoveField(
            model_name='irfindia',
            name='over_18_family_unwilling',
        ),
        migrations.RemoveField(
            model_name='irfindia',
            name='valid_gulf_country_visa',
        ),
        migrations.RemoveField(
            model_name='irfindia',
            name='scanned_form',
        ),
        migrations.AddField(
            model_name='irfindia',
            name='contradiction_between_stories',
            field=models.BooleanField(default=False, verbose_name='Contradiction between stories'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='who_in_group_dating',
            field=models.BooleanField(default=False, verbose_name='Dating Couple'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='who_in_group_engaged',
            field=models.BooleanField(default=False, verbose_name='Engaged'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='family_doesnt_know_where_going_18_23',
            field=models.BooleanField(default=False, verbose_name='18-23, family does not know where they are going'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='family_unwilling_to_let_go_18_23',
            field=models.BooleanField(default=False, verbose_name='18-23, family unwilling to let them go'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='girl_from_nepal_bangladesh',
            field=models.BooleanField(default=False, verbose_name='Girl is from Nepal or Bangladesh'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='interview_findings',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='on_way_to_get_married',
            field=models.BooleanField(default=False, verbose_name='On their way to get married'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='over_23_family_unwilling_to_let_go',
            field=models.BooleanField(default=False, verbose_name='Over 23, family unwilling to let them go'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='reason_believe_trafficked',
            field=models.TextField(blank=True, default='', verbose_name='What is the primary reason you believe this person is being trafficked or is at high risk of being trafficked'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='relationship_to_get_married',
            field=models.BooleanField(default=False, verbose_name='On their way to get married'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='waiting_for_someone_location',
            field=models.BooleanField(default=False, verbose_name='Waiting for someone in that location'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='wife_under_18',
            field=models.BooleanField(default=False, verbose_name='Wife/fiancee is under 18'),
        ),
        
    ]
