# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0081_auto_20190320_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifnepal',
            name='informant_number',
            field=models.CharField(blank=True, max_length=126, null=True, verbose_name='Informant #'),
        ),
    ]
