# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0080_country_currency'),
        ('dataentry', '0082_auto_20190322_0854'),
    ]

    operations = [
    ]
