# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0083_merge_20190325_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrfAttachmentBangladesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='scanned_irf_forms', verbose_name='Attach scanned copy of form (pdf or image)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='irfattachmentbangladesh',
            name='interception_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.IrfBangladesh'),
        ),
        migrations.RunSQL("insert into dataentry_irfattachmentbangladesh (attachment_number, description, attachment, interception_record_id) select 1, 'scanned irf', scanned_form, id from dataentry_irfbangladesh where scanned_form is not null and scanned_form != '';"),
        migrations.RemoveField(
            model_name='irfbangladesh',
            name='call_project_manager',
        ),
        migrations.RemoveField(
            model_name='irfbangladesh',
            name='noticed_drugged_or_drowsy',
        ),
        migrations.RemoveField(
            model_name='irfbangladesh',
            name='scan_submit_og_same_day',
        ),
        migrations.RemoveField(
            model_name='irfbangladesh',
            name='scanned_form',
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='contradiction_between_stories',
            field=models.BooleanField(default=False, verbose_name='Contradiction between stories'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='dont_know_which_city',
            field=models.BooleanField(default=False, verbose_name="Don't know which town/city"),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='dont_know_who_marry',
            field=models.BooleanField(default=False, verbose_name=" Doesn't know person they are going to marry"),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='exploitative_situation',
            field=models.BooleanField(default=False, verbose_name='Escaping an exploitative situation'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='group_facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='group_missed_call',
            field=models.BooleanField(default=False, verbose_name='Missed Call'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='group_never_met_before',
            field=models.BooleanField(default=False, verbose_name='Meeting someone for the first time'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='group_other_website',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='interview_findings',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='money_or_job_for_marriage',
            field=models.BooleanField(default=False, verbose_name='Was promised money or a job in exchange'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='purpose_for_leaving_marriage',
            field=models.BooleanField(default=False, verbose_name='Marriage'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='relationship_to_get_married',
            field=models.BooleanField(default=False, verbose_name='On their way to get married '),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='traveling_through_india',
            field=models.BooleanField(default=False, verbose_name='Traveling through India'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='unrealistic_benefit_for_marriage',
            field=models.BooleanField(default=False, verbose_name='Was promised unrealistic benefits for her family in exchange'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='where_going_to_hotel',
            field=models.BooleanField(default=False, verbose_name='To Hotel'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='who_in_group_dating',
            field=models.BooleanField(default=False, verbose_name='Dating Couple'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='who_in_group_engaged',
            field=models.BooleanField(default=False, verbose_name='Engaged'),
        ),
    ]
