# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0085_auto_20190329_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personidentification',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person'),
        ),
        migrations.RunSQL("INSERT INTO dataentry_personidentification (type, number, location, person_id) select 'Passport', passport, '', id from dataentry_person where passport is not null and passport != '';"),
        migrations.RemoveField(
            model_name='person',
            name='passport',
        ),
                migrations.RemoveField(
            model_name='cifnepal',
            name='legal_action_taken_staff_do_not_believe',
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='border_cross_air',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='known_broker_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='married_broker_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
                migrations.AddField(
            model_name='cifnepal',
            name='case_exploration_gulf_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='police_station_threats_prevented_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cifnepal',
            name='guardian_phone',
            field=models.CharField(max_length=126, null=True, verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='cifnepal',
            name='guardian_relationship',
            field=models.CharField(max_length=1024, null=True, verbose_name='Guardian Relationship'),
        ),
        migrations.AlterField(
            model_name='cifnepal',
            name='recruited_agency_pb',
            field=models.CharField(max_length=126, null=True, verbose_name='Agency PB'),
        ),
        migrations.AlterField(
            model_name='cifnepal',
            name='recruited_broker_pb',
            field=models.CharField(max_length=126, null=True, verbose_name='Broker PB'),
        ),
        migrations.AlterField(
            model_name='cifnepal',
            name='social_media',
            field=models.CharField(max_length=1024, null=True, verbose_name='Social Media'),
        ),
        migrations.AlterField(
            model_name='personboxnepal',
            name='social_media',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='potentialvictimnepal',
            name='social_media',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
