# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0091_auto_20190425_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrfAttachmentNepal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='scanned_irf_forms', verbose_name='Attach scanned copy of form (pdf or image)')),
                ('private_card', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='irfattachmentnepal',
            name='interception_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.IrfNepal'),
        ),
        migrations.RunSQL("insert into dataentry_irfattachmentnepal (attachment_number, description, attachment, interception_record_id, private_card) select 1, 'scanned irf', scanned_form, id, TRUE from dataentry_irfnepal where scanned_form is not null and scanned_form != '';"),
        migrations.RemoveField(
            model_name='irfnepal',
            name='scanned_form',
        ),
    ]
