# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-05 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0098_auto_20190604_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrfAttachmentMalawi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=126, null=True)),
                ('attachment', models.FileField(upload_to='scanned_irf_forms', verbose_name='Attach scanned copy of form (pdf or image)')),
                ('private_card', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='irfmalawi',
            name='appears_under_spell',
        ),
        migrations.RemoveField(
            model_name='irfmalawi',
            name='interception_made',
        ),
        migrations.RemoveField(
            model_name='irfmalawi',
            name='met_before_journey',
        ),
        migrations.RemoveField(
            model_name='irfmalawi',
            name='scanned_form',
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='contradiction_between_stories',
            field=models.BooleanField(default=False, verbose_name='Contradiction between stories'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='doesnt_speak_destination_language',
            field=models.BooleanField(default=False, verbose_name="Doesn't speak language of destination"),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='enrollment_confirmed',
            field=models.BooleanField(default=False, verbose_name='Enrollment confirmed'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='evidence_categorization',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='group_young_women_kids',
            field=models.BooleanField(default=False, verbose_name='Group of young women / kids'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='host_non_relative_paid',
            field=models.BooleanField(default=False, verbose_name='Non-relative(s) paid their travel expenses'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='job_confirmed',
            field=models.BooleanField(default=False, verbose_name='Job confirmed'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='mobile_phone_taken_away',
            field=models.BooleanField(default=False, verbose_name='Their mobile phone was taken away'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='purpose_for_going_other',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='reason_for_intercept',
            field=models.TextField(blank=True, verbose_name='Primary reason for intercept'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='relationship_arranged_by_other',
            field=models.BooleanField(default=False, verbose_name='Non-relative(s) organized their travel'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='valid_id_or_enrollment_documents',
            field=models.BooleanField(default=False, verbose_name='Valid ID card or enrollment documents'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='where_going_doesnt_know',
            field=models.BooleanField(default=False, verbose_name="Don't know where they are going"),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='who_in_group_dating',
            field=models.BooleanField(default=False, verbose_name='Dating couple'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='who_in_group_engaged',
            field=models.BooleanField(default=False, verbose_name='Engaged'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='who_in_group_pv_under_14',
            field=models.BooleanField(default=False, verbose_name='PV is under 14'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='wife_under_18',
            field=models.BooleanField(default=False, verbose_name='Wife/fiancee is under 18'),
        ),
        migrations.AddField(
            model_name='irfattachmentmalawi',
            name='interception_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.IrfMalawi'),
        ),
    ]
