# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0101_auto_20190610_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfafrica',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_first_reason',
            field=models.TextField(blank=True, verbose_name='First Reason'),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_first_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_first_verification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_followup_call',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_leadership_review',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_second_reason',
            field=models.TextField(blank=True, verbose_name='Second Reason'),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_second_verification',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_second_verification_date',
            field=models.DateField(null=True),
        ),
    ]
