# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-08 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0103_auto_20190701_1244'),
    ]

    operations = [
        migrations.RunSQL("UPDATE dataentry_permission SET min_level = 'COUNTRY' where permission_group = 'NOTIFICATIONS' and action='MDF';"),
    ]
