# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-01 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0102_auto_20190611_2057'),
    ]

    operations = [
         migrations.RunSQL("update dataentry_permission set min_level = 'STATION' where permission_group='ACCOUNTS';"),
    ]
