# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0110_auto_20190827_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personboxbangladesh',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxbenin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxghana',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxindia',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxkenya',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxmalawi',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxnepal',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxosi',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxsierraleone',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxsouthafrica',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxtanzania',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personboxuganda',
            name='role',
        ),
    ]
