# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0112_auto_20190828_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cifbangladesh',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifbangladesh',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifbangladesh',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifbangladesh',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifbangladesh',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifbangladesh',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifbenin',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifbenin',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifbenin',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifbenin',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifbenin',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifbenin',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifghana',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifghana',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifghana',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifghana',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifghana',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifghana',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifindia',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifindia',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifindia',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifindia',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifindia',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifindia',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifkenya',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifkenya',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifkenya',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifkenya',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifkenya',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifkenya',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifmalawi',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifmalawi',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifmalawi',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifmalawi',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifmalawi',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifmalawi',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifnepal',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifosi',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifosi',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifosi',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifosi',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifosi',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifosi',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifsierraleone',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifsierraleone',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifsierraleone',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifsierraleone',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifsierraleone',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifsierraleone',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifsouthafrica',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifsouthafrica',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifsouthafrica',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifsouthafrica',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifsouthafrica',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifsouthafrica',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ciftanzania',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='ciftanzania',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='ciftanzania',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ciftanzania',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='ciftanzania',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ciftanzania',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifuganda',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifuganda',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='cifuganda',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifuganda',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='cifuganda',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cifuganda',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbangladesh',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfbenin',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfghana',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfghana',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfghana',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfindia',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfindianetwork',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfindianetwork',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfindianetwork',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfkenya',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfmalawi',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfnepal',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfsierraleone',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfsierraleone',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfsierraleone',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfsouthafrica',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irftanzania',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irftanzania',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irftanzania',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_back_corrected',
            field=models.TextField(blank=True, verbose_name='Back Corrected'),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='irfuganda',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfbangladesh',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfbangladesh',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfbangladesh',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfbangladesh',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='vdfbangladesh',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfbangladesh',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfbenin',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfbenin',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfbenin',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfbenin',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='vdfbenin',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfbenin',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfindia',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfindia',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfindia',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfindia',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='vdfindia',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfindia',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfnepal',
            name='logbook_incomplete_questions',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfnepal',
            name='logbook_incomplete_sections',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='vdfnepal',
            name='logbook_information_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfnepal',
            name='logbook_notes',
            field=models.TextField(blank=True, verbose_name='Logbook Notes'),
        ),
        migrations.AddField(
            model_name='vdfnepal',
            name='logbook_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vdfnepal',
            name='logbook_submitted',
            field=models.DateField(null=True),
        ),
    ]
