# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0117_auto_20191024_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='aftercare_always_1_staff_in_shelter',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='aftercare_eduction_dhuwani',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='aftercare_eduction_nepalese_homes',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='aftercare_eduction_top_women_jobs',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='aftercare_only_female_staff_in_shelter',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='aftercare_victims_tested_std',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='engagement_number_of_vdfs',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_police',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_reports_cdo',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_reports_ddc',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_reports_women_children',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='paralegal_active_case_update_to_nation_office',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='paralegal_arrests_last_month',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='shelter_log_book',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
