# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0122_auto_20191112_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='cifattachmentbangladesh',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentbenin',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentghana',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentindia',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentkenya',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentmalawi',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentnepal',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentosi',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentsierraleone',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentsouthafrica',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmenttanzania',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentuganda',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='cifattachmentzimbabwe',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentbangladesh',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentbenin',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentcambodia',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentghana',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentindia',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentindianetwork',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentkenya',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentmalawi',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentnepal',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentsierraleone',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentsouthafrica',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmenttanzania',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentuganda',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='irfattachmentzimbabwe',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentbangladesh',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentbenin',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentindia',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentkenya',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentmalawi',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentnepal',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentsouthafrica',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmenttanzania',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentuganda',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfattachmentzimbabwe',
            name='option',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
