# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0124_auto_20191126_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdfbangladesh',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfbenin',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfindia',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfkenya',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfmalawi',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfnepal',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfsouthafrica',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdftanzania',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfuganda',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
        migrations.AddField(
            model_name='vdfzimbabwe',
            name='fundraising_purpose',
            field=models.CharField(max_length=126, null=True, verbose_name='how we can use your photo and the information collected during this interviewfor operational fundraising purposes.'),
        ),
    ]
