# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0125_auto_20191203_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='logistics_progress_reports_cdo',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='logistics_progress_reports_ddc',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='logistics_progress_reports_women_children',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='logistics_wdo_every_3_months',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='aftercare_eduction_touch',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='engagement_intercept_poster',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='engagement_movement_poster',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='govern_core_values',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='human_anti_corruption',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_cdo',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_municipal_rural',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_ngo',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='logistics_progress_ward',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='paralegal_gd_last_month',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='paralegal_when_to_file_case_poster',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
