# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0127_auto_20200108_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
