# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0131_auto_20200207_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalidation',
            name='form_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.FormType'),
        ),
        migrations.AlterField(
            model_name='formvalidation',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Form'),
        ),
    ]
