# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0132_auto_20200212_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercepteecommon',
            name='photo',
            field=models.ImageField(blank=True, db_index=True, default='', upload_to='interceptee_photos'),
        ),
        migrations.AddIndex(
            model_name='cifcommon',
            index=models.Index(fields=['logbook_submitted', 'station'], name='dataentry_c_logbook_845b53_idx'),
        ),
        migrations.AddIndex(
            model_name='irfcommon',
            index=models.Index(fields=['logbook_submitted', 'station'], name='dataentry_i_logbook_da5c66_idx'),
        ),
        migrations.AddIndex(
            model_name='irfcommon',
            index=models.Index(fields=['logbook_first_verification_date', 'station'], name='dataentry_i_logbook_ef594b_idx'),
        ),
        migrations.AddIndex(
            model_name='irfcommon',
            index=models.Index(fields=['logbook_second_verification_date', 'station'], name='dataentry_i_logbook_2648a4_idx'),
        ),
        migrations.AddIndex(
            model_name='vdfcommon',
            index=models.Index(fields=['logbook_submitted', 'station'], name='dataentry_v_logbook_2dcad0_idx'),
        ),
    ]
