# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-11 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0133_auto_20200219_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifcommon',
            name='form_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cifcommon_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='irfcommon',
            name='form_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irfcommon_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='form_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthlyreport_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vdfcommon',
            name='form_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vdfcommon_entered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
