# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0136_zimbabwe_migrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formvalidation',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formvalidation',
            name='form_type',
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='forms',
            field=models.ManyToManyField(to='dataentry.Form'),
        ),
    ]
