# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-16 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0137_auto_20200320_1519'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_irfcommon set noticed_young_looking=true "\
                          "where (young_woman_going_to_mining_town = true or group_young_women_kids = true) and "\
                          "station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and c.name in ('Malawi','Sierra Leone'))"),
        migrations.RunSQL("update dataentry_irfcommon set profile_children=true "\
                          "where (who_in_group_pv_under_14 = true or undocumented_children_in_group = true) and "\
                          "station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and c.name in ('Malawi','$ierra Leone'))"),
        migrations.RunSQL("update dataentry_irfcommon set vulnerability_family_unwilling=under_18_family_unwilling "\
                          "where station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and c.name in ('Malawi','$ierra Leone'))"),
        migrations.RunSQL("update dataentry_irfcommon set study_doesnt_know_school_details=true "\
                          "where (study_doesnt_know_school_details = true or no_enrollment_docs = true or doesnt_know_school_name = true or no_school_phone = true) and "\
                          "station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and c.name in ('Malawi','$ierra Leone'))"),
        migrations.RunSQL("update dataentry_irfcommon set industry=("\
                          "case when industry='' then 'Massage Parlor' else industry || ';Massage Parlor' end) "\
                          "where employment_massage_parlor = true and "\
                          "station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and c.name in ('Malawi','$ierra Leone'))"),
        migrations.RunSQL("update dataentry_irfcommon set industry=("\
                          "case when industry='' then 'Farm work' else industry || ';Farm work' end) "\
                          "where seasonal_farm_work = true and "\
                          "station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and c.name in ('Malawi'))"),
        migrations.RunSQL("update dataentry_irfcommon set industry=("\
                          "case when industry='' then 'Unregistered Mine' else industry || ';Unregistered Mine' end) "\
                          "where unregistered_mine = true and "\
                          "station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and c.name in ('Malawi'))"),
    ]
