# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-16 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0138_milawi_sierra_irf'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO dataentry_permission (permission_group, action, min_level, account_permission_name) values ('NOTIFICATIONS', 'IRF_SUBMITTED','STATION',null);"),
        migrations.RunSQL("INSERT INTO dataentry_permission (permission_group, action, min_level, account_permission_name) values ('NOTIFICATIONS', 'IRF_VERIFIED','STATION',null);"),
    ]
