# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-01 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0146_irfcommon_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(blank=True, max_length=1024)),
                ('social_media_verified', models.BooleanField(default=False, verbose_name='Social Media Verified')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='masterperson',
            name='appearance',
            field=models.TextField(blank=True, verbose_name='Appearance'),
        ),
        migrations.AddField(
            model_name='masterperson',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='masterperson',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='social_media_verified',
            field=models.BooleanField(default=False, verbose_name='Social Media Verified'),
        ),
        migrations.AlterField(
            model_name='person',
            name='master_set_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='personsocialmedia',
            name='master_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.MasterPerson'),
        ),
        migrations.AddField(
            model_name='personsocialmedia',
            name='social_media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.SocialMediaType'),
        ),
        migrations.AddField(
            model_name='person',
            name='social_media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.SocialMediaType'),
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('match_date', models.DateField(auto_now=True)),
                ('master1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master1', to='dataentry.MasterPerson')),
                ('master2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master2', to='dataentry.MasterPerson')),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.MatchType')),
            ],
        ),
        migrations.AddField(
            model_name='personmatch',
            name='matched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MatchAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.MatchAction')),
                ('master1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterHistory1', to='dataentry.MasterPerson')),
                ('master2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterHistory2', to='dataentry.MasterPerson')),
                ('match_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.MatchType')),
                ('matched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person')),
            ],
        ),
        
        migrations.RunSQL("insert into dataentry_phonetype (name) values('Own') "),
        migrations.RunSQL("insert into dataentry_phonetype (name) values('Family') "),
        migrations.RunSQL("insert into dataentry_phonetype (name) values('Friend') "),
        migrations.RunSQL("insert into dataentry_phonetype (name) values('False') "),
        
        migrations.RunSQL("insert into dataentry_addresstype (name) values('Current') "),
        migrations.RunSQL("insert into dataentry_addresstype (name) values('Last Known') "),
        migrations.RunSQL("insert into dataentry_addresstype (name) values('Family') "),
        migrations.RunSQL("insert into dataentry_addresstype (name) values('Friend') "),
        migrations.RunSQL("insert into dataentry_addresstype (name) values('False') "),
        
        migrations.RunSQL("insert into dataentry_socialmediatype (name) values('Own') "),
        migrations.RunSQL("insert into dataentry_socialmediatype (name) values('Family') "),
        migrations.RunSQL("insert into dataentry_socialmediatype (name) values('Friend') "),
        migrations.RunSQL("insert into dataentry_socialmediatype (name) values('False') "),
        
        migrations.RunSQL("insert into dataentry_documenttype (name) values('Photo') "),
        
        migrations.RunSQL("insert into dataentry_matchtype (name) values('Possible') "),
        migrations.RunSQL("insert into dataentry_matchtype (name) values('Suggested') "),
        migrations.RunSQL("insert into dataentry_matchtype (name) values('Non-match') "),
        
        migrations.RunSQL("insert into dataentry_matchaction (name) values('create master person') "),
        migrations.RunSQL("insert into dataentry_matchaction (name) values('add to master person') "),
        migrations.RunSQL("insert into dataentry_matchaction (name) values('create match') "),
        migrations.RunSQL("insert into dataentry_matchaction (name) values('update match') "),
        migrations.RunSQL("insert into dataentry_matchaction (name) values('remove from master person') "),
        migrations.RunSQL("insert into dataentry_matchaction (name) values('merge master persons') "),
        migrations.RunSQL("insert into dataentry_matchaction (name) values('deactivate master person') "),
    ]
