# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_border_stations', '0003_auto_20200721_1709'),
        ('dataentry', '0147_auto_20200702_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.PositiveIntegerField()),
                ('compliance', models.FloatField(null=True)),
                ('budget', models.PositiveIntegerField(null=True)),
                ('gospel', models.PositiveIntegerField(null=True)),
                ('empowerment', models.PositiveIntegerField(null=True)),
                ('cifs', models.PositiveIntegerField(null=True)),
                ('convictions', models.PositiveIntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataentry.BorderStation')),
            ],
        ),
        migrations.CreateModel(
            name='LocationStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.PositiveIntegerField()),
                ('intercepts', models.PositiveIntegerField(null=True)),
                ('arrests', models.PositiveIntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_border_stations.Location')),
            ],
        ),
        migrations.CreateModel(
            name='CountryExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.PositiveIntegerField()),
                ('exchange_rate', models.FloatField(default=1)),
            ],
        ),
         migrations.AddField(
            model_name='countryexchange',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Country'),
        ),
        migrations.AddField(
            model_name='borderstation',
            name='non_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='prior_arrests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='prior_convictions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='prior_intercepts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='enable_all_locations',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LocationStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.PositiveIntegerField()),
                ('work_fraction', models.FloatField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_border_stations.Location')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_border_stations.Staff')),
            ],
        ),
        
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level)  values ('STATION_STATISTICS','VIEW','COUNTRY')"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level)  values ('STATION_STATISTICS','EDIT','COUNTRY')"),
    ]
