# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0147_auto_20200702_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.PositiveIntegerField()),
                ('compliance', models.FloatField(null=True)),
                ('budget', models.PositiveIntegerField(null=True)),
                ('intercepts', models.PositiveIntegerField(null=True)),
                ('arrests', models.PositiveIntegerField(null=True)),
                ('gospel', models.PositiveIntegerField(null=True)),
                ('empowerment', models.PositiveIntegerField(null=True)),
                ('cifs', models.PositiveIntegerField(null=True)),
                ('convictions', models.PositiveIntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borderstation',
            name='non_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='prior_arrests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='prior_convictions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='prior_intercepts',
            field=models.IntegerField(default=0),
        ),
        
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level)  values ('STATION_STATISTICS','VIEW','COUNTRY')"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level)  values ('STATION_STATISTICS','EDIT','COUNTRY')"),
    ]
