# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0149_auto_20200813_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMatch',
            fields=[
                ('the_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pendingmatch',
                'managed': False,
            },
        ),
    ]
