# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0155_audit_auditsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfcommon',
            name='signs_fake_documentation',
            field=models.BooleanField(default=False, verbose_name='Fake documents'),
        ),
    ]
