# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-21 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0157_legalcase_legalcaseattachment_legalcasesuspect_legalcasevictim'),
    ]

    operations = [
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level)  values ('NOTIFICATIONS','HSA','COUNTRY')"),
    ]
