# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0161_auto_20201028_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcasesuspect',
            name='fine_currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legalcasesuspect',
            name='fine_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
