# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-03 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0163_audit_form_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='form',
        ),
    ]
