# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-12 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0164_remove_audit_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='missing_data_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalcasesuspect',
            name='named_on_charge_sheet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legalcasesuspect',
            name='named_in_verdict',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
