# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0165_auto_20201112_1939'),
    ]

    
    operations = [
        migrations.AddField(
            model_name='audit',
            name='forms_in_range',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditsample',
            name='monitor_notes',
            field=models.TextField(blank=True),
        ),
    ]
