# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-12-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dataentry', '0166_auditsample_monitor_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='personformcache',
            name='person',
        ),
        migrations.DeleteModel(
            name='PersonFormCache',
        ),
    ]
