# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-12-04 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0166_personform'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalidation',
            name='retrieve',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='update',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
