# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-12-16 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataentry', '0168_auto_20201210_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='GospelVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('date_time_entered_into_system', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('profess_to_accept_christ', models.CharField(max_length=126, null=True)),
                ('survey_complete', models.CharField(max_length=126, null=True)),
                ('searchlight_edited', models.CharField(max_length=126, null=True)),
                ('date_of_followup', models.DateField(null=True, verbose_name='Interview date')),
                ('followup_person', models.CharField(max_length=126, null=True)),
                ('form_entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gospelverification_entered_by', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
                ('vdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.VdfCommon')),
            ],
            options={
                'abstract': False,
            },
        ),
        
        migrations.RunSQL(
            "insert into dataentry_permission (permission_group, action, min_level)  values ('GOSPEL_VERIFICATION','VIEW','STATION')"
            ),
        migrations.RunSQL(
            "insert into dataentry_permission (permission_group, action, min_level)  values ('GOSPEL_VERIFICATION','EDIT','STATION')"
            ),
    ]
