# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-12-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0169_gospelverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCaseTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField()),
                ('comment', models.TextField()),
                ('added_by', models.CharField(max_length=255, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_removed', models.DateField(null=True)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.LegalCase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='comment',
        ),
    ]
