# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0171_irf_new_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='human_trafficking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='specific_code_law',
            field=models.TextField(null=True),
        ),
    ]
