# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-03-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0174_irfcommon_vulnerability_family_friend_arranged_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('diagnostic_date', models.DateField(auto_now_add=True)),
                ('location', models.TextField(blank=True)),
                ('diagnostic_data', models.TextField(blank=True)),
            ],
        ),
    ]
