# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-03-23 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0174_irfcommon_vulnerability_family_friend_arranged_travel'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_irfcommon set evidence_categorization = 'Evidence of Trafficking'"\
                          "where evidence_categorization like 'Clear%' or "\
                          "evidence_categorization like 'Some%'"),
        migrations.RunSQL("update dataentry_irfcommon set logbook_first_verification = 'Evidence of Trafficking'"\
                          "where logbook_first_verification like 'Clear%' or "\
                          "logbook_first_verification like 'Some%'"),
        migrations.RunSQL("update dataentry_irfcommon set logbook_second_verification = 'Evidence of Trafficking'"\
                          "where logbook_second_verification like 'Clear%' or "\
                          "logbook_second_verification like 'Some%'"),
    ]
