# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-04-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0179_auto_20210413_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcasesuspect',
            name='arrest_submitted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='legalcasesuspect',
            name='verdict_submitted_date',
            field=models.DateField(null=True),
        ),
        migrations.RunSQL("update dataentry_legalcasesuspect set arrest_submitted_date='2000-01-01' where arrest_date is not null"),
        migrations.RunSQL("update dataentry_legalcasesuspect set verdict_submitted_date='2000-01-01' where verdict_date is not null"),
    ]
