# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-04-27 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_border_stations', '0003_auto_20200721_1709'),
        ('dataentry', '0181_auto_20210427_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationstaff',
            unique_together=set([('year_month', 'location', 'staff')]),
        ),
        migrations.AlterUniqueTogether(
            name='locationstatistics',
            unique_together=set([('year_month', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='stationstatistics',
            unique_together=set([('year_month', 'station')]),
        ),
    ]
