# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-05-25 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0182_auto_20210427_1253'),
    ]

    operations = [
        migrations.RunSQL('DROP VIEW IF EXISTS cifcombined'),
        migrations.AlterField(
            model_name='cifcommon',
            name='other_possible_victims',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.RunSQL("update dataentry_cifcommon set other_possible_victims = 'True' where other_possible_victims ='true'"),
        migrations.RunSQL("update dataentry_cifcommon set other_possible_victims = 'False' where other_possible_victims ='false'"),
    ]
