# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0183_auto_20210525_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdfcommon',
            name='contact_national_office',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='country_pv_sent',
            field=models.CharField(max_length=126, null=True, verbose_name='What country was the PV sent back to?'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='how_pv_released',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='interaction_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hours'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='pv_spent_time_at_shelter',
            field=models.CharField(max_length=126, null=True, verbose_name='Did the PV spend time at LJ’s short-term shelter?'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='relationship_to_guardian',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='service_education_about_ht',
            field=models.BooleanField(default=False, verbose_name='Education about HT'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='service_food',
            field=models.BooleanField(default=False, verbose_name='Food'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='service_legal_support',
            field=models.BooleanField(default=False, verbose_name='Legal Support'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='service_medical_support',
            field=models.BooleanField(default=False, verbose_name='Medical Support '),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='service_safe_foreign_employment',
            field=models.BooleanField(default=False, verbose_name='Safe Foreign Employment Info'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='service_travel_support',
            field=models.BooleanField(default=False, verbose_name='Travel Support'),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='share_gospel_why_not',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='shelter_nights',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nights'),
        ),
        
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set awareness_of_exploitation_before_interception='Was aware, but did not know how bad until intercepted by LJ' "\
                          " where awareness_of_exploitation_before_interception='Had heard, but never knew how bad it was until I was intercepted by TH/LJ'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set awareness_of_exploitation_before_interception='Was aware, but didn''t think it was happening to them' "\
                          " where awareness_of_exploitation_before_interception='Knew how bad it was, but didn''t think it was happening to them'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set awareness_of_exploitation_before_interception='Was not aware' "\
                          " where awareness_of_exploitation_before_interception='Had never heard about it'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set what_victim_believes_now='Does not believe Jesus is the one true God' "\
                          " where what_victim_believes_now='Don''t believe'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set what_victim_believes_now='Already believes Jesus is the one true God' "\
                          " where what_victim_believes_now like ('Do believe%') and victim_heard_message_before = 'Yes - heard and was believer'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set what_victim_believes_now='Came to believe that Jesus is the one true God' "\
                          " where what_victim_believes_now like ('Do believe%') and victim_heard_message_before != 'Yes - heard and was believer'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set victim_heard_message_before='Yes' "\
                          " where victim_heard_message_before like 'Yes%'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set victim_heard_message_before='Yes' "\
                          " where victim_heard_message_before like 'Yes%'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set where_victim_sent=where_victim_sent_details "\
                          " where where_victim_sent_details is not null and where_victim_sent_details != ''"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set how_pv_released='Someone came to pick the PV up from the station/shelter' "\
                          " where someone_pick_up_victim = 'Yes'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Malawi','Lesotho','Mozambique','Namibia'))"),
    ]
