# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0186_auto_20210624_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gospelverification',
            name='profess_to_accept_christ',
        ),
        migrations.RemoveField(
            model_name='gospelverification',
            name='survey_complete',
        ),
        migrations.AddField(
            model_name='gospelverification',
            name='connect_with_church',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gospelverification',
            name='form_changes',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='gospelverification',
            name='how_pv_professed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gospelverification',
            name='reason_for_change',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gospelverification',
            name='shared_resources',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gospelverification',
            name='staff_who_shared',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
