# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0187_auto_20210628_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdfcommon',
            name='why_sent_home_with_with_alarms',
            field=models.TextField(null=True, verbose_name='If the potential victim has 10 or more total Home Situation Alarms and you recommend sending the potential victim home to stay with guardians, why?'),
        ),
    ]
