# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-07-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0188_auto_20210630_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationstatistics',
            name='subcommittee_members',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
