# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-07-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0191_auto_20210712_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstatistics',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
