# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-08-20 15:51
from __future__ import unicode_literals
import pytz

from django.db import migrations, models

def irf_interception_date_and_time(apps, schema_editor):
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute("SELECT id, time_zone from dataentry_borderstation")
    stations = cursor.fetchall()
    station_timezone = {}
    for station in stations:
        station_timezone[station[0]] = station[1]
    cursor.execute('SELECT id, date_time_of_interception, station_id FROM dataentry_irfcommon order by station_id')
    irfs = cursor.fetchall()
    for irf in irfs:
        date_time = irf[1]
        tz = pytz.timezone(station_timezone[irf[2]])
        date_time = date_time.astimezone(tz)
        date_time = date_time.replace(microsecond=0)
        date_time = date_time.replace(tzinfo=None)
        
        date_value = date_time.strftime("%Y=%m-%d")
        if date_time.second == 1:   # seconds set to one when no time was provided
            time_value = None
        else:
            time_value = date_time.strftime("%H:%M")
        
        print(irf[0], irf[1], station_timezone[irf[2]], date_time, date_value, time_value)
        if time_value is not None:
            cursor.execute("UPDATE dataentry_irfcommon SET date_of_interception=%s, time_of_interception=%s WHERE id=%s",[date_value, time_value, irf[0]])
        else:
            cursor.execute("UPDATE dataentry_irfcommon SET date_of_interception=%s WHERE id=%s",[date_value, irf[0]])
            print('None', irf[0])

class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0192_auto_20210722_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfcommon',
            name='date_of_interception',
            field=models.DateField(default=None, null=True, verbose_name='Interception date'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='time_of_interception',
            field=models.TimeField(null=True),
        ),
        migrations.RunPython(irf_interception_date_and_time),
        migrations.RemoveField(
            model_name='irfcommon',
            name='date_time_of_interception',
        ),
    ]
