# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-09-02 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0194_auto_20210824_1847'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set awareness_of_exploitation_before_interception='Was aware, but did not know how bad until intercepted by LJ' "\
                          " where awareness_of_exploitation_before_interception='Had heard, but never knew how bad it was until I was intercepted by TH/LJ'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set awareness_of_exploitation_before_interception='Was aware, but didn''t think it was happening to them' "\
                          " where awareness_of_exploitation_before_interception='Knew how bad it was, but didn''t think it was happening to them'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set awareness_of_exploitation_before_interception='Was not aware' "\
                          " where awareness_of_exploitation_before_interception='Had never heard about it'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set what_victim_believes_now='Does not believe Jesus is the one true God' "\
                          " where what_victim_believes_now='Don''t believe'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set what_victim_believes_now='Already believes Jesus is the one true God' "\
                          " where what_victim_believes_now like ('Do believe%') and victim_heard_message_before = 'Yes - heard and was believer'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set what_victim_believes_now='Came to believe that Jesus is the one true God' "\
                          " where what_victim_believes_now like ('Do believe%') and victim_heard_message_before != 'Yes - heard and was believer'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set victim_heard_message_before='Yes' "\
                          " where victim_heard_message_before like 'Yes%'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set victim_heard_message_before='Yes' "\
                          " where victim_heard_message_before like 'Yes%'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set where_victim_sent=where_victim_sent_details "\
                          " where where_victim_sent_details is not null and where_victim_sent_details != ''"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
        migrations.RunSQL("update dataentry_vdfcommon "\
                          "set how_pv_released='Someone came to pick the PV up from the station/shelter' "\
                          " where someone_pick_up_victim = 'Yes'"\
                          " and station_id in (select s.id from dataentry_borderstation s, dataentry_country c where s.operating_country_id = c.id and "\
                          "c.name in ('Bangladesh','Ghana','India','Uganda'))"),
    ]
