# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-29 11:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0197_auto_20210915_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='match_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_match_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.RunSQL("update dataentry_person set last_match_time='2100-02-01' where last_match_time is null"),
    ]
