# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-11 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0199_auto_20211005_1813'),
    ]

    operations = [
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STATION_STATISTICS','EDIT_ALL','GLOBAL',4)"),

    ]
