# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0201_auto_20211015_1510'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_permission set min_level='COUNTRY', account_permission_name=null where permission_group='NOTIFICATIONS' and action='LEGAL'"),
    ]
