# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-03 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0202_auto_20211018_2017'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_personidentification set type='ID#' where type='Citizenship'"),
    ]
