# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-11-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0203_auto_20211103_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfcommon',
            name='control_abducted',
            field=models.BooleanField(default=False, verbose_name='Abducted'),
        ),
    ]
