# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0204_irfcommon_control_abducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfcommon',
            name='pv_stopped_on_own',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
