# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-15 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0209_auto_20211215_2211'),
    ]

    operations = [
        migrations.RunSQL("insert into dataentry_projectcategory (name, sort_order) values ('Transit Stations',1)"),
        migrations.RunSQL("insert into dataentry_projectcategory (name, sort_order) values ('Impact Multiplying',2)"),
        migrations.RunSQL("insert into dataentry_projectcategory (name, sort_order) values ('Admin',3)"),
        
        migrations.RunSQL("update dataentry_borderstation set project_category_id=1 where non_transit=false"),
        migrations.RunSQL("update dataentry_borderstation set project_category_id=2 where non_transit=true"),
        migrations.RunSQL("update dataentry_borderstation set features='hasStaff;hasProjectStats;hasLocations;hasLocationStaffing;hasForms' where non_transit=true"),
        
        migrations.RunSQL("update dataentry_permission set min_level='PROJECT' where min_level='STATION'"),
        migrations.RunSQL("update dataentry_permission set permission_group='PROJECTS' where permission_group='STATIONS'"),
        migrations.RunSQL("update dataentry_permission set permission_group='PROJECT_STATISTICS' where permission_group='STATION_STATISTICS'"),
    ]
