# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-17 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0210_auto_20211215_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borderstation',
            name='non_transit',
        ),
    ]
