# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-03 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0211_remove_borderstation_non_transit'),
    ]

    operations = [
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('PROJECTS','SET_FEATURES','GLOBAL',7)"),
    ]
