# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-20 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0213_stationstatistics_active_shelters'),
    ]

    operations = [
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('NOTIFICATIONS','CONFIRMED_MATCH','COUNTRY',-1)"),

    ]
