# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0214_auto_20220120_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empowerment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_entered_into_system', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=4)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('pre_emp_usd', models.DecimalField(decimal_places=2, max_digits=17)),
                ('pre_emp_local', models.CharField(blank=True, max_length=255, null=True)),
                ('post_emp_usd', models.DecimalField(decimal_places=2, max_digits=17)),
                ('post_emp_local', models.CharField(blank=True, max_length=255, null=True)),
                ('lines_crossed', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation')),
            ],
        ),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('EMP','VIEW','STATION',1)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('EMP','EDIT','STATION',3)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('EMP','ADD','STATION',4)"),
    ]
