# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-01 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0215_empowerment'),
    ]

    operations = [
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('NOTIFICATIONS','SUGGESTED_MATCH','COUNTRY',-1)"),
    ]
