# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0217_gospel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gospel',
            name='profession_date',
            field=models.DateField(null=True),
        ),
    ]
