# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0218_gospel_profession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='empowerment',
            name='vdf_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
