# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-12 09:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0219_empowerment_vdf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcategory',
            name='form_category_question_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
