# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0220_formcategory_form_category_question_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfcommon',
            name='control_under_18_recruited_for_work',
            field=models.BooleanField(default=False, verbose_name='Under 18, recruited for work'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_travel_met_recently',
            field=models.BooleanField(default=False, verbose_name='Is or was traveling with someone they met recently'),
        ),
    ]
