# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0221_irfcommon_control_under_18_recruited_for_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderstation',
            name='mdf_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataentry.BorderStation'),
        ),
    ]
