# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0221_irfcommon_control_under_18_recruited_for_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfcommon',
            name='control_id_or_permit_with_broker',
            field=models.BooleanField(default=False, verbose_name='Passport is with a broker'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_stranded_or_abandoned',
            field=models.BooleanField(default=False, verbose_name='Stranded/abandoned'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_under_16_recruited_for_work',
            field=models.BooleanField(default=False, verbose_name='Under 16, recruited for work'),
        ),
    ]
