# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0224_irfverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irfcommon',
            old_name='logbook_second_verification',
            new_name='verified_evidence_categorization',
        ),
        migrations.RenameField(
            model_name='irfcommon',
            old_name='logbook_second_verification_date',
            new_name='verified_date',
        ),
        migrations.RemoveIndex(
            model_name='irfcommon',
            name='dataentry_i_logbook_2648a4_idx',
        ),
        migrations.AddIndex(
            model_name='irfcommon',
            index=models.Index(fields=['verified_date', 'station'], name='dataentry_i_verifie_666b5c_idx'),
        ),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('NOTIFICATIONS','IRF_TIE_RESOLVED','STATION',-1)"),
    ]
