# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0225_auto_20220530_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='form_tag',
            field=models.CharField(default='replaceMe', max_length=126),
        ),
        migrations.AddField(
            model_name='exportimport',
            name='form_tag',
            field=models.CharField(default='replaceMe', max_length=126),
        ),
        migrations.AddField(
            model_name='formvalidation',
            name='form_tag',
            field=models.CharField(default='replaceMe', max_length=126),
        ),
        migrations.AddField(
            model_name='question',
            name='form_tag',
            field=models.CharField(default='question', max_length=126),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_name',
            field=models.CharField(max_length=126, unique=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='form_model_name',
            field=models.CharField(max_length=126, unique=True),
        ),
        migrations.RunSQL("update dataentry_category set form_tag = form_tag || id"),
        migrations.RunSQL("update dataentry_question set form_tag = form_tag || id"),
        migrations.RunSQL("update dataentry_formvalidation set form_tag = form_tag || id"),
        migrations.RunSQL("update dataentry_exportimport set form_tag = form_tag || id"),
    ]
