# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0226_auto_20220620_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='form_tag',
            field=models.CharField(max_length=126, unique=True),
        ),
        migrations.AlterField(
            model_name='exportimport',
            name='form_tag',
            field=models.CharField(max_length=126, unique=True),
        ),
        migrations.AlterField(
            model_name='formvalidation',
            name='form_tag',
            field=models.CharField(max_length=126, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='form_tag',
            field=models.CharField(max_length=126, unique=True),
        ),
        migrations.AddField(
            model_name='formtype',
            name='tag_enalbed',
            field=models.BooleanField(default=False),
        ),
    ]
