# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-07 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0227_auto_20220620_1342'),
    ]

    operations = [
        migrations.RunSQL(
            'insert into dataentry_irfverification (interception_record_id, verification_type, followup_call, followup_details, evidence_categorization,'\
                    'reason, verified_date, verifier_id) '\
                "select irf.id, 1, irf.logbook_followup_call, '', irf.logbook_first_verification, irf.logbook_first_reason, "\
                        'irf.logbook_first_verification_date, acc.id '\
                'from dataentry_irfcommon as irf '
                    "left outer join accounts_account as acc on irf.logbook_first_verification_name = acc.first_name || ' ' || acc.last_name " \
                'where irf.logbook_first_verification_date is not null and irf.station_id in ('\
                        'select id from dataentry_borderstation '\
                        'where operating_country_id in ('\
                                'select id from dataentry_country '\
                                "where name in ('Bangladesh')))"
        ),
        migrations.RunSQL(
            'insert into dataentry_irfverification (interception_record_id, verification_type, followup_call, followup_details, evidence_categorization,'\
                    'reason, verified_date, verifier_id) '\
                "select irf.id, 2, '', '', irf.verified_evidence_categorization, irf.logbook_second_reason, "\
                        'irf.verified_date, acc.id '\
                'from dataentry_irfcommon as irf '\
                    "left outer join accounts_account as acc on irf.logbook_second_verification_name = acc.first_name || ' ' || acc.last_name " \
                'where irf.verified_date is not null and irf.station_id in ('\
                        'select id from dataentry_borderstation '\
                        'where operating_country_id in ('\
                                'select id from dataentry_country '\
                                "where name in ('Bangladesh')))"
        ),
        migrations.RunSQL(
            'update dataentry_irfcommon '\
            "set status = 'approved'"
            "where status = 'first-verification'   and station_id in ("
                    'select id from dataentry_borderstation '\
                    'where operating_country_id in ('\
                            'select id from dataentry_country '\
                            "where name in ('Bangladesh')))"
        ),
        migrations.RunSQL(
            'update dataentry_irfcommon '\
            "set status = 'verified'"
            "where status = 'second-verification'   and station_id in ("
                    'select id from dataentry_borderstation '\
                    'where operating_country_id in ('\
                            'select id from dataentry_country '\
                            "where name in ('Bangladesh')))"
        ),
    ]
