# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0228_auto_20220622_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='form_tag',
            field=models.CharField(default='x', max_length=126),
        ),
        migrations.RunSQL('update dataentry_storage set form_tag = form_model_name')
    ]
