# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0235_auto_20221221_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtype',
            old_name='tag_enalbed',
            new_name='tag_enabled',
        ),
        migrations.AddField(
            model_name='formversion',
            name='file',
            field=models.CharField(default='form_data.json', max_length=126, unique=True),
        ),
    ]
