# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-13 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0236_auto_20230111_1827'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set profile = replace(profile, 'Escaping an exploitative situation', 'Recently enslaved') "\
                            "where station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('India','India Network'))"),
        
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set vulnerability_travel_met_recently = true "\
                            "where (vulnerability_group_missed_call = true or vulnerability_group_facebook = true or vulnerability_group_other_website != '') "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('India','India Network'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set case_notes = case_notes || '\n' || reason_for_intercept "\
                            "where reason_for_intercept != '' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('India','India Network'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set where_going_destination = (case when where_going_destination='' "\
                                "then 'PV doesn\'\'t know' else where_going_destination || ';PV doesn\'\'t know' end) "\
                            "where vulnerability_where_going_doesnt_know = true and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('India','India Network'))"),
        migrations.RunSQL("update dataentry_person "\
                          "set arrested=null "\
                            "where arrested='No' and id in ("\
                                "select di.person_id "\
                                "from dataentry_intercepteecommon di "\
                                    "inner join dataentry_irfcommon dc1 on di.interception_record_id = dc1.id "\
                                    "inner join dataentry_borderstation db on dc1.station_id = db.id "\
                                    "inner join dataentry_country dc on db.operating_country_id = dc.id "\
                                "where dc.name in ('India','India Network'))"),
                
        # Country specific migration
        
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set profile = replace(profile, 'Massage Parlor', 'Spa/massage') "\
                            "where profile like '%Massage Parlor%' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('Kenya'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set profile = replace(profile, 'Impoverished', 'Extremely poor') "\
                            "where profile like '%Impoverished%' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('South Africa'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set profile = replace(profile, 'Foreigner', 'Foreign looking') "\
                            "where profile like '%Foreigner%' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('South Africa'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set industry = replace(industry, 'Hairdressing', 'Hair & beauty') "\
                            "where industry like '%Hairdressing%' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('South Africa'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set industry = replace(industry, 'Waitressing', 'Restaurant') "\
                            "where industry like '%Waitressing%' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('South Africa'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set industry = replace(industry, 'Miner', 'Mine') "\
                            "where industry like '%Miner%' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('South Africa'))"),
        migrations.RunSQL("update dataentry_irfcommon "\
                          "set profile = replace(profile, 'Currently in slavery', 'Recently enslaved') "\
                            "where profile like '%Currently in slavery%' "\
                            "and station_id in ("\
                                "select dbs.id "\
                                "from dataentry_borderstation dbs "\
                                    "inner join dataentry_country dc on dc.id = dbs.operating_country_id "\
                                "where dc.name in ('Ghana'))"),
    ]
