# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0244_auto_20230125_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='irfcommon',
            name='agreement_contract_language',
            field=models.BooleanField(default=False, verbose_name='Contract not in a language understood by the PV'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='agreement_mpa_not_bearing_cost',
            field=models.BooleanField(default=False, verbose_name='Company/MPA not bearing cost to Gulf/Malaysia'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='agreement_no_receipt',
            field=models.BooleanField(default=False, verbose_name='No bhaar pai (receipt) for full amount of payment'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='agreement_paid_above_standard',
            field=models.BooleanField(default=False, verbose_name='Paid more than government standard cost'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='agreement_paid_agent',
            field=models.BooleanField(default=False, verbose_name='Paid money to agent'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_agreement_prepermission_mismatch',
            field=models.BooleanField(default=False, verbose_name='Job agreement and pre-permission details do not match'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_enticed_banned_area',
            field=models.BooleanField(default=False, verbose_name='Being enticed by agent/MPA to go to banned country for migrant worker'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_enticed_non_seasonal',
            field=models.BooleanField(default=False, verbose_name='Being enticed by MPA to go to South Korea or Israel for non-seasonal work'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_facilitated_via_third_country',
            field=models.BooleanField(default=False, verbose_name='Process being fully facilitated by someone to travel to third country via India for work'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_invalid_lt',
            field=models.BooleanField(default=False, verbose_name='No/invalid Lt number and/or demand letter'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_invalid_mpa',
            field=models.BooleanField(default=False, verbose_name='Using an invalid MPA'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_visa_misuse',
            field=models.BooleanField(default=False, verbose_name='Convinced by agent/MPA to work on visa other than work visa'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='control_women_enticed_unsave_area',
            field=models.BooleanField(default=False, verbose_name='Woman being enticed by agent/MPA to go for domestic work in Gulf/Malaysia'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='mpa_agent_not_used',
            field=models.BooleanField(default=False, verbose_name='Check if PV did not use a MPA or agent'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='mpa_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='mpa_phone',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='preparation_did_not_complete',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='preparation_other',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='preparation_unaware_of_process',
            field=models.BooleanField(default=False, verbose_name='Unaware of official employment migration process'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='pv_closest_contact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='pv_lt_number_after_counsel',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='pv_lt_number_before_counsel',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='result_pv_changed_plans',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='result_pv_local_job',
            field=models.BooleanField(default=False, verbose_name='PV decided to change plans and look for a job within Nepal due to SFE staff’s counseling'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='result_pv_other_education',
            field=models.BooleanField(default=False, verbose_name='PV was referred to other education'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='result_pv_tech_training',
            field=models.BooleanField(default=False, verbose_name='PV was referred to technical/vocational training'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_applied_job_doesnt_know_destination',
            field=models.BooleanField(default=False, verbose_name="Applied for job, but doesn't know destination"),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_cost_of_living_higher_than_wages',
            field=models.BooleanField(default=False, verbose_name='Cost of living in destination much higher than wages'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_doesnt_know_job_details',
            field=models.BooleanField(default=False, verbose_name="Doesn't know what job they are applying for"),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_doesnt_speak_local_language',
            field=models.BooleanField(default=False, verbose_name="Doesn't speak local language"),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_going_via_india',
            field=models.BooleanField(default=False, verbose_name='Going to a third country via India'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_mpa_excessive_time',
            field=models.BooleanField(default=False, verbose_name='MPA taking excessive time to process/send migrant'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='vulnerability_using_agent',
            field=models.BooleanField(default=False, verbose_name='Using an agent'),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='agent_how_contacted',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='agent_is_suspect',
            field=models.CharField(max_length=127, null=True,blank=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='agent_who_initiated_contact',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='mpa_how_contacted',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='mpa_is_suspect',
            field=models.CharField(max_length=127, null=True,blank=True),
        ),
        migrations.AddField(
            model_name='irfcommon',
            name='mpa_who_initiated_contact',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
