# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0254_auto_20230530_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationassociation',
            name='persons_in_charge',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='locationassociation',
            name='pvs_visited',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='locationassociation',
            name='suspects_associative',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suspectassociation',
            name='associated_locations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suspectassociation',
            name='associated_pvs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suspectassociation',
            name='associated_suspects',
            field=models.TextField(null=True),
        ),
    ]
