# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-09 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0253_auto_20230419_1642'),
    ]

    operations = [
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','VIEW','COUNTRY',1)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','EDIT','COUNTRY',2)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','ADD','COUNTRY',3)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('STAFF','DELETE','COUNTRY',4)"),
        
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('PROJECT_REQUEST','VIEW','PROJECT',1)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('PROJECT_REQUEST','ADD','PROJECT',2)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('PROJECT_REQUEST','APPROVE','PROJECT',3)"),
        
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('MDF','VIEW','PROJECT',1)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('MDF','EDIT','PROJECT',2)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('MDF','ADD','PROJECT',3)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('MDF','DELETE','PROJECT',4)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('MDF','INITIAL_REVIEW','PROJECT',5)"),
        migrations.RunSQL("insert into dataentry_permission (permission_group, action, min_level, display_order)  values ('MDF','FINAL_REVIEW','PROJECT',6)"),
    ]
