# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-23 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0258_auto_20230509_1844'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_irfcommon set (agent_how_contacted,agent_who_initiated_contact) = (agent_who_initiated_contact,agent_how_contacted)"),
    ]
