# Generated by Django 4.2.10 on 2024-03-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0260_alter_answer_params_alter_audit_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryexchange',
            name='date_time_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.RunSQL("update dataentry_countryexchange set date_time_last_updated='2000-01-01' where year_month < 201601"),
    ]
