# Generated by Django 4.2.10 on 2024-07-12 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataentry', '0261_countryexchange_date_time_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('form_name', models.CharField(max_length=126)),
                ('form_number', models.CharField(max_length=126)),
                ('form_id', models.IntegerField()),
                ('action', models.CharField(max_length=126)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
