# Generated by Django 4.2.10 on 2024-10-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0262_formlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlog',
            name='details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='formlog',
            name='request',
            field=models.JSONField(null=True),
        ),
    ]
