# Generated by Django 4.2.10 on 2024-10-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0262_formlog'),
    ]

    operations = [
        migrations.RunSQL("update dataentry_permission set display_order=3 where permission_group='STAFF' and action='ADD'"),
        migrations.RunSQL("update dataentry_permission set display_order=4, min_level='PROJECT' where permission_group='STAFF' and action='DELETE'"),
        migrations.RunSQL("update dataentry_permission set display_order=5 where permission_group='STAFF' and action='VIEW_REVIEW'"),
        migrations.RunSQL("update dataentry_permission set display_order=6 where permission_group='STAFF' and action='EDIT_REVIEW'"),
        migrations.RunSQL("update dataentry_permission set display_order=7 where permission_group='STAFF' and action='VIEW_CONTRACT'"),
        migrations.RunSQL("update dataentry_permission set display_order=8 where permission_group='STAFF' and action='EDIT_CONTRACT'"),
        
        # Before the reordering of permissions
        #  - The locations that user has for  VIEW_REVIEW must include all the locations that the user has for ADD, but could include additional locations
        #  - The locations that user has for  ADD must include all the locations that the user has for DELETE, but could include additional locations
        # After the reordering of permissions we initially need
        #  - The locations that user has for ADD and DELETE to be the same locations that the user has for VIEW_REVIEW
        # permission ID for ADD is 87
        # permission ID for DELETE is 88
        # permission ID for VIEW_REVIEW is 118
        # set the ADD and DELETE locations to be all of the permission locations currently held for VIEW_REVIEW
        migrations.RunSQL("delete from dataentry_userlocationpermission where permission_id in (87,88)"),
        migrations.RunSQL("insert into dataentry_userlocationpermission (account_id, country_id, station_id, permission_id) "
                          "select account_id, country_id, station_id, 87 "
                          "from dataentry_userlocationpermission "
                          "where permission_id = 118 "),
        migrations.RunSQL("insert into dataentry_userlocationpermission (account_id, country_id, station_id, permission_id) "
                          "select account_id, country_id, station_id, 88 "
                          "from dataentry_userlocationpermission "
                          "where permission_id = 118 "),
        
    ]
