# Generated by Django 4.2.10 on 2024-11-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0264_auto_20241018_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderStationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('attachment', models.FileField(upload_to='project_attachments', verbose_name='Attach scanned forms related to projects')),
                ('option', models.CharField(max_length=126, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.borderstation')),
            ],
        ),
    ]
