# Generated by Django 4.2.10 on 2024-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0264_auto_20241018_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdfcommon',
            name='share_gospel_give_pv',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='vdfcommon',
            name='share_gospel_resource',
            field=models.BooleanField(default=False, verbose_name='Used a resource'),
        ),
    ]
