# Generated by Django 4.2.10 on 2024-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0264_auto_20241018_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_group', models.CharField(max_length=100, unique=True)),
                ('group_display_name', models.CharField(max_length=127)),
                ('hide_display', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='action_display_name',
            field=models.CharField(default='unset', max_length=127, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='hide_action',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RunSQL("update dataentry_permission set action_display_name = action"),
        migrations.RunSQL("insert into dataentry_permissiongroup (permission_group, group_display_name, hide_display) "
                          "select distinct permission_group, permission_group, false "
                          "from dataentry_permission"),
        
        migrations.RunSQL("update dataentry_permissiongroup set group_display_name='GSP_MINI_FORM' where permission_group='GSP'"),
        migrations.RunSQL("update dataentry_permissiongroup set group_display_name='PBS' where permission_group='MDF'"),
        migrations.RunSQL("update dataentry_permissiongroup set group_display_name='EMAIL_NOTIFICATION' where permission_group='NOTIFICATIONS'"),
        migrations.RunSQL("update dataentry_permissiongroup set group_display_name='PROJECT_REQUEST_RECORD' where permission_group='PROJECT_REQUEST'"),
        migrations.RunSQL("update dataentry_permissiongroup set hide_display=true where permission_group='ADDRESSES'"),
        migrations.RunSQL("update dataentry_permissiongroup set hide_display=true where permission_group='BUDGETS'"),
        migrations.RunSQL("update dataentry_permissiongroup set hide_display=true where permission_group='CIF'"),
        migrations.RunSQL("update dataentry_permissiongroup set hide_display=true where permission_group='PERSONS'"),
        migrations.RunSQL("update dataentry_permissiongroup set hide_display=true where permission_group='VDF'"),
        
        migrations.RunSQL("update dataentry_permission set action_display_name='UNVERIFIED_IRF_SUBMITTED' where action='IRF_SUBMITTED'"),
        migrations.RunSQL("update dataentry_permission set action_display_name='IRF_TIEBREAK_DONE' where action='IRF_TIE_RESOLVED'"),
        migrations.RunSQL("update dataentry_permission set action_display_name='IRF_NEEDS_TIEBREAK' where action='IRF_VERIFIED'"),
        migrations.RunSQL("update dataentry_permission set hide_action=true where action='COMMITTEE'"),
        migrations.RunSQL("update dataentry_permission set hide_action=true where action='CONFIRMED_MATCH'"),
        migrations.RunSQL("update dataentry_permission set hide_action=true where action='HSA'"),
        migrations.RunSQL("update dataentry_permission set hide_action=true where action='INVESTIGATION'"),
        migrations.RunSQL("update dataentry_permission set hide_action=true where action='LEGAL'"),
        migrations.RunSQL("update dataentry_permission set hide_action=true where action='MDF'"),
    ]
