# Generated by Django 4.2.10 on 2025-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0265_permissiongroup_permission_action_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_added_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
