# Generated by Django 4.2.10 on 2024-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0266_irfcommon_vulnerability_contract_against_law_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationinformation',
            name='recruitment_agency_name',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='locationinformation',
            name='source_contact_info',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='locationinformation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
