# Generated by Django 4.2.10 on 2025-02-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0265_borderstationattachment'),
        ('dataentry', '0266_person_photo_added_date_time'),
    ]

    operations = [
    ]
