# Generated by Django 4.2.10 on 2025-01-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0265_vdfcommon_share_gospel_give_pv_and_more'),
        ('dataentry', '0266_person_photo_added_date_time'),
    ]

    operations = [
    ]
