# Generated by Django 4.2.10 on 2025-02-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0266_irfcommon_vulnerability_contract_against_law_and_more'),
        ('dataentry', '0267_merge_20250130_2009'),
    ]

    operations = [
    ]
