# Generated by Django 4.2.10 on 2025-01-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0267_locationinformation_recruitment_agency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='merged_location_where_spend_time',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='suspectassociation',
            name='previous_legal_actions',
            field=models.TextField(blank=True, verbose_name='Previous Legal Actions'),
        ),
        migrations.AddField(
            model_name='suspectinformation',
            name='location_where_spend_time',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='suspectinformation',
            name='source_contact_info',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='suspectlegal',
            name='anything_cause_pvs_to_file',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suspectlegal',
            name='police_contact',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='suspectlegal',
            name='what_needed_for_arrest',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suspectinformation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SuspectLegalPv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_name', models.CharField(max_length=126, null=True)),
                ('willing_to_file', models.TextField(null=True)),
                ('hesitation_concern', models.TextField(null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.incident')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.suspect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
