# Generated by Django 4.2.10 on 2025-02-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0267_locationinformation_recruitment_agency_name_and_more'),
        ('dataentry', '0268_merge_20250207_0910'),
    ]

    operations = [
    ]
