
# Generated by Django 4.2.10 on 2025-02-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0268_suspect_merged_location_where_spend_time_and_more'),
        ('dataentry', '0269_merge_20250207_0935'),
    ]

    operations = [
    ]
