# Generated by Django 4.2.10 on 2025-03-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0269_merge_20250207_0935'),
        ('dataentry', '0269_remove_questionlayout_weight_form_client_json_and_more'),
    ]

    operations = [
    ]
