# Generated by Django 4.2.10 on 2025-03-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0270_merge_20250207_1012'),
        ('dataentry', '0270_merge_20250303_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectlegal',
            name='what_caused_pvs_to_be_willing',
            field=models.TextField(null=True),
        ),
    ]
