# Generated by Django 4.2.10 on 2025-04-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0267_merge_20250204_1441'),
        ('dataentry', '0271_suspectlegal_what_caused_pvs_to_be_willing'),
    ]

    operations = [
    ]
