# Generated by Django 4.2.10 on 2025-04-07 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataentry', '0271_suspectlegal_what_caused_pvs_to_be_willing'),
    ]

    def version_number_migration(apps, schema_editor):
        model_names = [
            "dataentry.Audit",
            "dataentry.Incident",
            "dataentry.IrfCommon",
            "dataentry.VdfCommon",
            "dataentry.Suspect",
            "dataentry.LocationForm",
            "dataentry.LocationForm",
            "dataentry.GospelVerification",
            "legal.LegalCharge",
        ]
        version_map = {
            "V2021.11": "2021.11",
            "V2024.9": "2024.09",
            "V2024.8": "2024.08",
            "V2022.9": "2022.09",
            "2022.06": "2022.06",
            "V2022.6": "2022.06",
            "V2022.4": "2022.04",
            "Migrated": "000000_Migrated",  # for version comparison
            "V2022.5": "2022.05",
            "V2022.05": "2022.05",
            "V2022.8": "2022.08",
            "V2021.10": "2021.10",
            "V2021.6": "2021.06",
            "V2023.1": "2023.01",
        }

        for model_name in model_names:
            if model_name == 'dataentry.Form':
                field_name = 'version'
            else:
                field_name = 'form_version'
            model_parts = model_name.split(".")
            model_class = apps.get_model(model_parts[0], model_parts[1])
            entries = model_class.objects.all()
            for entry in entries:
                value = getattr(entry, field_name)
                if value is not None and value != '':
                    if value not in version_map:
                        raise ValueError(f"Version '{value}' for model {model_name} not found in map")
                    else:
                        setattr(entry, field_name, version_map[value])
                        entry.save()



    operations = [
        migrations.RunPython(version_number_migration),
    ]
