# Generated by Django 4.2.10 on 2025-04-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0272_auto_20250407_2320'),
        ('dataentry', '0272_merge_20250404_1654'),
    ]

    operations = [
    ]
