# Generated by Django 4.2.10 on 2025-04-15 07:59

from django.db import migrations, models

COUNTRY_CURRENCY_CODE_MAP = {
    "Argentina": "ARS",
    "Bangladesh": "BDT",
    "Benin": "XOF",
    "Burkina Faso": "XOF",
    "Burundi": "BIF",
    "Cambodia": "KHR",
    "Ecuador": "USD",
    "Ethiopia": "ETB",
    "Ghana": "GHS",
    "India": "INR",
    "India Network": "INR",
    "Indonesia": "IDR",
    "Kenya": "KES",
    "Lesotho": "LSL",
    "Liberia": "LRD",
    "Malawi": "MWK",
    "Mexico": "MXN",
    "Mongolia": "MNT",
    "Mozambique": "MZN",
    "Namibia": "NAD",
    "Nepal": "NPR",
    "Open Source": "",
    "Philippines": "PHP",
    "Rwanda": "RWF",
    "Sierra Leone": "SLL",
    "South Africa": "ZAR",
    "Tanzania": "TZS",
    "Uganda": "UGX",
    "United States": "USD",
    "Zambia": "ZMW",
    "Zimbabwe": "ZWL"
}


def add_currency_codes(apps, schema_editor):
    Country = apps.get_model("dataentry", "Country")
    all_countries = Country.objects.all()
    for country in all_countries:
        currency_iso_code = COUNTRY_CURRENCY_CODE_MAP[country.name]
        country.currency_symbol = currency_iso_code
        country.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dataentry', '0273_merge_20250411_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_iso_code',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.RunPython(add_currency_codes)
    ]
