# Generated by Django 4.2.10 on 2025-04-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0273_merge_20250411_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdfcommon',
            name='service_none',
            field=models.BooleanField(default=False, verbose_name='None'),
        ),
    ]
