# Generated by Django 4.2.10 on 2025-04-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0274_country_currency_iso_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='currency_iso_code',
            new_name='currency_symbol',
        ),
    ]
