# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-25 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "create view id_match_source as "\
            "with id_temp as ("\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media,"\
                        "dc.name as country, irf_number, irf_number as form_number, 'IRF' as form "\
                "from dataentry_person dp "\
                    "inner join dataentry_intercepteecommon di on di.person_id = dp.id "\
                    "inner join dataentry_irfcommon di2 on di2.id = di.interception_record_id "\
                    "inner join dataentry_borderstation db on db.id = di2.station_id "\
                    "inner join dataentry_country dc on dc.id = db.operating_country_id "\
                "union "\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media,"\
                        "dc.name as country,"\
                        "case when position('.' in cif_number) > 0 then substring(cif_number,1,position('.' in cif_number)-1) else substring(cif_number,1,length(cif_number)-1) end as irf_number, cif_number as form_number, 'CIF' as form "\
                "from dataentry_person dp "\
                    "inner join dataentry_cifcommon dc1 on dc1.main_pv_id = dp.id "\
                    "inner join dataentry_borderstation db on db.id = dc1.station_id "\
                    "inner join dataentry_country dc on dc.id = db.operating_country_id "\
                "union "\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media,"\
                        "dc.name as country,"\
                        "case when position('.' in cif_number) > 0 then substring(cif_number,1,position('.' in cif_number)-1) else substring(cif_number,1,length(cif_number)-1) end as irf_number, cif_number as form_number, 'CIF' as form "\
                "from dataentry_person dp "\
                    "inner join dataentry_personboxcommon dp2 on dp2.person_id = dp.id "\
                    "inner join dataentry_cifcommon dc1 on dc1.id = dp2.cif_id "\
                    "inner join dataentry_borderstation db on db.id = dc1.station_id "\
                    "inner join dataentry_country dc on dc.id = db.operating_country_id "\
                "union "\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media,"\
                        "dc.name as country,"\
                        "case when position('.' in cif_number) > 0 then substring(cif_number,1,position('.' in cif_number)-1) else substring(cif_number,1,length(cif_number)-1) end as irf_number, cif_number as form_number, 'CIF' as form "\
                "from dataentry_person dp "\
                    "inner join dataentry_potentialvictimcommon dp2 on dp2.person_id = dp.id "\
                    "inner join dataentry_cifcommon dc1 on dc1.id = dp2.cif_id "\
                    "inner join dataentry_borderstation db on db.id = dc1.station_id "\
                    "inner join dataentry_country dc on dc.id = db.operating_country_id "\
                "union "\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media,"\
                        "dc.name as country, substring(vdf_number,1,length(vdf_number)-1) as irf_number, vdf_number as form_number, 'VDF' as form "\
                "from dataentry_person dp "\
                    "inner join dataentry_vdfcommon dv on dv.victim_id = dp.id "\
                    "inner join dataentry_borderstation db on db.id = dv.station_id "\
                    "inner join dataentry_country dc on dc.id = db.operating_country_id "\
                "union "\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media,"\
                        "dc.name as country, "\
                        "case when substring(legal_case_number,length(legal_case_number),1) between '0' and '9' then legal_case_number else substring(legal_case_number,1,length(legal_case_number)-1) end as irf_number, legal_case_number as form_number, 'LEGAL_CASE' as form "\
                "from dataentry_person dp "\
                    "inner join dataentry_legalcasesuspect dl on dl.person_id = dp.id "\
                    "inner join dataentry_legalcase dl2 on dl2.id = dl.legal_case_id "\
                    "inner join dataentry_borderstation db on db.id = dl2.station_id "\
                    "inner join dataentry_country dc on dc.id = db.operating_country_id "\
                "union "\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media,"\
                        "dc.name as country, "\
                        "case when substring(legal_case_number,length(legal_case_number),1) between '0' and '9' then legal_case_number else substring(legal_case_number,1,length(legal_case_number)-1) end as irf_number, legal_case_number as form_number, 'LEGAL_CASE' as form "\
                "from dataentry_person dp "\
                    "inner join dataentry_legalcasevictim dl on dl.person_id = dp.id "\
                    "inner join dataentry_legalcase dl2 on dl2.id = dl.legal_case_id "\
                    "inner join dataentry_borderstation db on db.id = dl2.station_id "\
                    "inner join dataentry_country dc on dc.id = db.operating_country_id) "\
                "select * "\
                "from id_temp "\
                "union "\
                "select dp.id, full_name, age, gender, phone_contact, birthdate, nationality, social_media, "\
                        "null as country, null as irf_number, null as form_number, null as form "\
                "from dataentry_person dp "\
                "where id not in (select id from id_temp)"),
    ]
