# Generated by Django 4.2.10 on 2024-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotHistoricalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('query', models.TextField(null=True)),
                ('tags', models.JSONField(null=True)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('date_time_entered', models.DateTimeField(auto_now_add=True)),
                ('date_time_last_updated', models.DateTimeField(auto_now=True)),
                ('date_time_added_to_vector_store', models.DateTimeField(null=True)),
            ],
        ),
    ]
