name: tinyhands-default-build-test
run-name: ${{ github.actor }} tinyhands build & test
on: [push]
env: 
   SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}: 
   SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}: 
   SL_USER: ${{secrets.SL_STAGING_SSH_USER}}: 
jobs:
  build-tinyhands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.sh
  test-tinyhands:
    runs-on: ubuntu-latest
    needs: [build-tinyhands]
    steps:
      - run: docker-compose run --rm web ./manage.py test
  deploy-tinyhands:
    runs-on: ubuntu-latest
    needs: [test-tinyhands]
    if: github.ref == 'refs/heads/feature/github-action'
    steps:
      - run: mkdir -p ~/.ssh/
      - run: echo "$SL_PRIVATE_KEY" > ../private.key
      - run: sudo chmod 600 ../private.key
      - run: echo "$SL_HOST" > !/.ssh/known_hosts
      - run: docker push tusoftwarestudio/dreamsuite-nginx:${{ github.sha }}
      - run: docker push tusoftwarestudio/dreamsuite:${{ github.sha }}
      - run: echo ${{ github.sha }} > /dreamsuite_tag
      - run: scp -i ../private.key /dreamsuite_tag $SL_USER@$SL_HOST:/home/thi/tinyhands/dreamsuite_tag
      - run: ssh -i ../private.key /dreamsuite_tag $SL_USER@$SL_HOST 'tinyhands/run.sh'

