name: tinyhands-default-build-test
run-name: ${{ github.actor }} tinyhands build & test
on:
   push:
jobs:
  build-test-tinyhands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.sh
      - run: docker-compose run --rm web ./manage.py test
  deploy-tinyhands:
    runs-on: ubuntu-latest
    needs: [build-test-tinyhands]
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ~/.ssh/
      - run: ./build-containers.sh
      - run: docker login --username $SL_DOCKER_USER --password $SL_DOCKER_PASSWORD
      - run: docker push amunn/searchlight-nginx:${{ github.sha }}
      - run: docker push amunn/searchlight:${{ github.sha }}
      - run: echo ${{ github.sha }} > ../dreamsuite_tag
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with: 
           key: '$SL_PRIVATE_KEY'
           known_hosts: '$SL_KNOWN_HOSTS'
      - run: scp ../dreamsuite_tag $SL_USER@$SL_HOST:/home/$SL_USER/tinyhands/dreamsuite_tag
      - run: ssh $SL_USER@$SL_HOST 'tinyhands/run.sh'
    env: 
      SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}
      SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}
      SL_USER: ${{secrets.SL_STAGING_SSH_USER}}
      SL_KNOWN_HOSTS: ${{secrets.SL_STAGING_KNOWN_HOSTS}}
      SL_DOCKER_USER: ${{secrets.SL_DOCKER_USER}}
      SL_DOCKER_PASSWORD: ${{secrets.SL_DOCKER_PASSWORD}}

