name: tinyhands-default-build-test
run-name: ${{ github.actor }} tinyhands build & test
on: [push]
env: 
   SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}
   SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}
   SL_USER: ${{secrets.SL_STAGING_SSH_USER}}
jobs:
  build-test-tinyhands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.sh
      - run: docker-compose run --rm web ./manage.py test
  deploy-tinyhands:
    runs-on: ubuntu-latest
    needs: [build-test-tinyhands]
    if: github.ref == 'refs/heads/feature/github-action'
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ~/.ssh/
      - run: echo "$SL_PRIVATE_KEY" > ../private.key
      - run: sudo chmod 600 ../private.key
      - run: echo "$SL_HOST" > ~/.ssh/known_hosts
      - run: ./build-containers.sh
      - run: docker login --username $SL_DOCKER_USER --password $SL_DOCKER_PASSWORD
      - run: docker push amunn/searchlight-nginx:${{ github.sha }}
      - run: docker push amunn/searchlight:${{ github.sha }}
      - run: echo ${{ github.sha }} > /dreamsuite_tag
      - run: scp -i ../private.key /dreamsuite_tag $SL_USER@$SL_HOST:/home/thi/tinyhands/dreamsuite_tag
      - run: ssh -i ../private.key /dreamsuite_tag $SL_USER@$SL_HOST 'tinyhands/run.sh'
    env: 
      SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}
      SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}
      SL_USER: ${{secrets.SL_STAGING_SSH_USER}}
      SL_DOCKER_USER: ${{secrets.SL_DOCKER_USER}}
      SL_DOCKER_PASSWORD: ${{secrets.SL_DOCKER_PASSWORD}}

