name: tinyhands-default-build-test
run-name: ${{ github.actor }} tinyhands build & test
on: [push]
jobs:
  build-tinyhands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.sh
  test-tinyhands:
    runs-on: ubuntu-latest
    needs: [build-tinyhands]
    steps:
      - run: docker-compose run --rm web ./manage.py test
  deploy-tinyhands:
    runs-on: ubuntu-latest
    needs: [test-tinyhands]
    if: github.ref == 'refs/heads/feature/github-action'
    steps:
      - run: |
	    mkdir -p ~/.ssh/
	    echo "$SL_PRIVATE_KEY" > ../private.key
	    sudo chmod 600 ../private.key
	    echo "$SL_HOST" > !/.ssh/known_hosts
        shell: bash
	env: 
	   SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}: 
	   SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}: 
	   SL_USER: ${{secrets.SL_STAGING_SSH_USER}}: 


